/* Generated by Nim Compiler v0.14.2 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -O3 -fno-strict-aliasing  -I/home/primat/programs/nim-0.14.2/lib -o /home/primat/projects/tests/nim/intro/nimcache/intro.o /home/primat/projects/tests/nim/intro/nimcache/intro.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <stdio.h>
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
N_NIMCALL(NI, fib_94003_258688446)(NI n0);
N_NIMCALL(NimStringDesc*, nimIntToStr)(NI x0);
static N_INLINE(void, initStackBottomWith)(void* locals0);
N_NOINLINE(void, setStackBottom)(void* thestackbottom0);
NIM_EXTERNC N_NOINLINE(void, systemInit000)(void);
NIM_EXTERNC N_NOINLINE(void, systemDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, introInit000)(void);
NIM_EXTERNC N_NOINLINE(void, introDatInit000)(void);

N_NIMCALL(NI, fib_94003_258688446)(NI n0) {
	NI result0;
{	result0 = (NI)0;
	{
		NI LOC5;
		NI LOC6;
		if (!(((NI) 2) < n0)) goto LA3;
		LOC5 = (NI)0;
		LOC5 = fib_94003_258688446((NI)(n0 - ((NI) 1)));
		LOC6 = (NI)0;
		LOC6 = fib_94003_258688446((NI)(n0 - ((NI) 2)));
		result0 = (NI)(LOC5 + LOC6);
		goto BeforeRet;
	}
	goto LA1;
	LA3: ;
	{
		result0 = ((NI) 1);
		goto BeforeRet;
	}
	LA1: ;
	}BeforeRet: ;
	return result0;
}

static N_INLINE(void, initStackBottomWith)(void* locals0) {
	setStackBottom(locals0);
}
void PreMainInner() {
	systemInit000();
	introDatInit000();
}

void PreMain() {
	void (*volatile inner)();
	systemDatInit000();
	inner = PreMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	introInit000();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)();
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

NIM_EXTERNC N_NOINLINE(void, introInit000)(void) {
	NI LOC1;
	NimStringDesc* LOC2;
	LOC1 = (NI)0;
	LOC1 = fib_94003_258688446(((NI) 50));
	LOC2 = (NimStringDesc*)0;
	LOC2 = nimIntToStr(LOC1);
	printf("%s\012", LOC2? (LOC2)->data:"nil");
	fflush(stdout);
}

NIM_EXTERNC N_NOINLINE(void, introDatInit000)(void) {
}

