/* Generated by Nim Compiler v0.14.2 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -O3 -fno-strict-aliasing  -I/home/primat/programs/nim-0.14.2/lib -o /home/primat/projects/tests/nim/intro/nimcache/stdlib_system.o /home/primat/projects/tests/nim/intro/nimcache/stdlib_system.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#include <sys/mman.h>
#include <stdio.h>
#include <stdlib.h>
#include <setjmp.h>
#include <signal.h>
typedef struct Exception Exception;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct Avlnode30084 Avlnode30084;
typedef struct Gcheap50418 Gcheap50418;
typedef struct Gcstack50416 Gcstack50416;
typedef struct Cellseq47921 Cellseq47921;
typedef struct Cell47905 Cell47905;
typedef struct Memregion30086 Memregion30086;
typedef struct Smallchunk30040 Smallchunk30040;
typedef struct Llchunk30080 Llchunk30080;
typedef struct Bigchunk30042 Bigchunk30042;
typedef struct Intset30014 Intset30014;
typedef struct Trunk30010 Trunk30010;
typedef struct Gcstat50414 Gcstat50414;
typedef struct Cellset47917 Cellset47917;
typedef struct Pagedesc47913 Pagedesc47913;
typedef struct Basechunk30038 Basechunk30038;
typedef struct Freecell30030 Freecell30030;
typedef struct TGenericSeq TGenericSeq;
typedef struct NimStringDesc NimStringDesc;
typedef struct TSafePoint TSafePoint;
typedef struct TNimObject TNimObject;
typedef N_NIMCALL_PTR(NIM_BOOL, TY10009) (Exception* e0);
typedef N_NIMCALL_PTR(NIM_BOOL, TY10014) (Exception* e0);
typedef N_NIMCALL_PTR(void, TY10019) (void);
typedef NU8 Tnimkind3203;
typedef NU8 Tnimtypeflag3209Set;
typedef N_NIMCALL_PTR(void, TY3289) (void* p0, NI op0);
typedef N_NIMCALL_PTR(void*, TY3294) (void* p0);
struct  TNimType  {
NI size;
Tnimkind3203 kind;
Tnimtypeflag3209Set flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3289 marker;
TY3294 deepcopy;
};
typedef Avlnode30084* TY30091[2];
struct  Avlnode30084  {
TY30091 link;
NI key;
NI upperbound;
NI level;
};
struct  Cellseq47921  {
NI len;
NI cap;
Cell47905** d;
};
typedef Smallchunk30040* TY30101[512];
typedef Trunk30010* Trunkbuckets30012[256];
struct  Intset30014  {
Trunkbuckets30012 data;
};
struct  Memregion30086  {
NI minlargeobj;
NI maxlargeobj;
TY30101 freesmallchunks;
Llchunk30080* llmem;
NI currmem;
NI maxmem;
NI freemem;
NI lastsize;
Bigchunk30042* freechunkslist;
Intset30014 chunkstarts;
Avlnode30084* root;
Avlnode30084* deleted;
Avlnode30084* last;
Avlnode30084* freeavlnodes;
NIM_BOOL locked;
};
struct  Gcstat50414  {
NI stackscans;
NI cyclecollections;
NI maxthreshold;
NI maxstacksize;
NI maxstackcells;
NI cycletablesize;
NI64 maxpause;
};
struct  Cellset47917  {
NI counter;
NI max;
Pagedesc47913* head;
Pagedesc47913** data;
};
struct  Gcheap50418  {
Gcstack50416* stack;
void* stackbottom;
NI cyclethreshold;
Cellseq47921 zct;
Cellseq47921 decstack;
Cellseq47921 tempstack;
NI recgclock;
Memregion30086 region;
Gcstat50414 stat;
Cellset47917 marked;
Cellseq47921 additionalroots;
};
struct  Basechunk30038  {
NI prevsize;
NI size;
NIM_BOOL used;
};
struct  Smallchunk30040  {
  Basechunk30038 Sup;
Smallchunk30040* next;
Smallchunk30040* prev;
Freecell30030* freelist;
NI free;
NI acc;
NF data;
};
struct  Bigchunk30042  {
  Basechunk30038 Sup;
Bigchunk30042* next;
Bigchunk30042* prev;
NI align;
NF data;
};
typedef NI TY30019[8];
struct  Trunk30010  {
Trunk30010* next;
NI key;
TY30019 bits;
};
struct  Llchunk30080  {
NI size;
NI acc;
Llchunk30080* next;
};
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct  Freecell30030  {
Freecell30030* next;
NI zerofield;
};
typedef N_NIMCALL_PTR(void, TY19401) (NimStringDesc* msg0);
struct  TNimObject  {
TNimType* m_type;
};
struct  Exception  {
  TNimObject Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
NimStringDesc* trace;
};
typedef NU8 Walkop50410;
struct  Cell47905  {
NI refcount;
TNimType* typ;
};
struct  Pagedesc47913  {
Pagedesc47913* next;
NI key;
TY30019 bits;
};
typedef NU8 Tnimtypeflag3209;
typedef NU8 Tnimnodekind3205;
struct  TNimNode  {
Tnimnodekind3205 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef N_NIMCALL_PTR(void, Globalmarkerproc56402) (void);
typedef TFrame* TY20003[128];
typedef N_NIMCALL_PTR(void, Finalizer) (void* self0);
typedef Globalmarkerproc56402 TY56410[7001];
struct  Gcstack50416  {
Gcstack50416* prev;
Gcstack50416* next;
void* starts;
void* pos;
NI maxstacksize;
};
typedef struct {
N_NIMCALL_PTR(NIM_BOOL, ClPrc) (Exception* e0, void* ClEnv);
void* ClEnv;
} TY18011;
struct  TSafePoint  {
TSafePoint* prev;
NI status;
jmp_buf context;
NIM_BOOL hasRaiseAction;
TY18011 raiseAction;
};
static N_INLINE(void, initallocator_11801_1689653243)(void);
static N_INLINE(void, initStackBottom)(void);
N_NOINLINE(void, setStackBottom)(void* thestackbottom0);
N_NIMCALL(void, initgc_11601_1689653243)(void);
N_NIMCALL(void, init_48012_1689653243)(Cellseq47921* s0, NI cap0);
N_NOCONV(void*, alloc0_7417_1689653243)(NI size0);
N_NIMCALL(void*, alloc0_46616_1689653243)(Memregion30086* allocator0, NI size0);
N_NIMCALL(void*, alloc_46440_1689653243)(Memregion30086* allocator0, NI size0);
N_NIMCALL(void*, rawalloc_37204_1689653243)(Memregion30086* a0, NI requestedsize0);
static N_INLINE(NI, roundup_28601_1689653243)(NI x0, NI v0);
N_NIMCALL(Smallchunk30040*, getsmallchunk_36612_1689653243)(Memregion30086* a0);
N_NIMCALL(Bigchunk30042*, getbigchunk_35814_1689653243)(Memregion30086* a0, NI size0);
static N_INLINE(void, listremove_33602_1689653243)(Bigchunk30042** head0, Bigchunk30042* c0);
N_NIMCALL(void, splitchunk_35609_1689653243)(Memregion30086* a0, Bigchunk30042* c0, NI size0);
static N_INLINE(void, updateprevsize_32668_1689653243)(Memregion30086* a0, Bigchunk30042* c0, NI prevsize0);
static N_INLINE(NIM_BOOL, isaccessible_32615_1689653243)(Memregion30086* a0, void* p0);
N_NIMCALL(NIM_BOOL, contains_31332_1689653243)(Intset30014* s0, NI key0);
N_NIMCALL(Trunk30010*, intsetget_31283_1689653243)(Intset30014* t0, NI key0);
static N_INLINE(NI, pageindex_31776_1689653243)(void* p0);
N_NIMCALL(void, incl_31353_1689653243)(Memregion30086* a0, Intset30014* s0, NI key0);
N_NIMCALL(Trunk30010*, intsetput_31305_1689653243)(Memregion30086* a0, Intset30014* t0, NI key0);
N_NIMCALL(void*, llalloc_30243_1689653243)(Memregion30086* a0, NI size0);
static N_INLINE(void*, osallocpages_29814_1689653243)(NI size0);
N_NOINLINE(void, raiseoutofmem_28234_1689653243)(void);
static N_INLINE(void, inccurrmem_30202_1689653243)(Memregion30086* a0, NI bytes0);
static N_INLINE(NI, pageindex_31771_1689653243)(Basechunk30038* c0);
static N_INLINE(void, listadd_34823_1689653243)(Bigchunk30042** head0, Bigchunk30042* c0);
N_NIMCALL(Bigchunk30042*, requestoschunks_31788_1689653243)(Memregion30086* a0, NI size0);
static N_INLINE(void, listadd_38216_1689653243)(Smallchunk30040** head0, Smallchunk30040* c0);
static N_INLINE(void, listremove_41002_1689653243)(Smallchunk30040** head0, Smallchunk30040* c0);
N_NIMCALL(void, add_31153_1689653243)(Memregion30086* a0, Avlnode30084** t0, NI key0, NI upperbound0);
N_NIMCALL(Avlnode30084*, allocavlnode_30427_1689653243)(Memregion30086* a0, NI key0, NI upperbound0);
N_NIMCALL(void, skew_31134_1689653243)(Avlnode30084** t0);
N_NIMCALL(void, split_31139_1689653243)(Avlnode30084** t0);
N_NIMCALL(void, init_48027_1689653243)(Cellset47917* s0);
N_NIMCALL(void, nimGCvisit)(void* d0, NI op0);
N_NIMCALL(void, dooperation_52418_1689653243)(void* p0, Walkop50410 op0);
static N_INLINE(Cell47905*, usrtocell_52040_1689653243)(void* usr0);
static N_INLINE(void, decref_53601_1689653243)(Cell47905* c0);
static N_INLINE(void, rtladdzct_53201_1689653243)(Cell47905* c0);
N_NOINLINE(void, addzct_52017_1689653243)(Cellseq47921* s0, Cell47905* c0);
static N_INLINE(void, add_47992_1689653243)(Cellseq47921* s0, Cell47905* c0);
N_NOCONV(void*, alloc_7401_1689653243)(NI size0);
N_NOCONV(void, dealloc_7448_1689653243)(void* p0);
N_NIMCALL(void, dealloc_46622_1689653243)(Memregion30086* allocator0, void* p0);
N_NIMCALL(void, rawdealloc_43617_1689653243)(Memregion30086* a0, void* p0);
static N_INLINE(Basechunk30038*, pageaddr_31781_1689653243)(void* p0);
static N_INLINE(NIM_BOOL, issmallchunk_31669_1689653243)(Basechunk30038* c0);
N_NIMCALL(void, freebigchunk_32803_1689653243)(Memregion30086* a0, Bigchunk30042* c_32807_1689653243);
static N_INLINE(NIM_BOOL, chunkunused_31689_1689653243)(Basechunk30038* c0);
N_NIMCALL(void, excl_31364_1689653243)(Intset30014* s0, NI key0);
N_NIMCALL(void, freeoschunks_32407_1689653243)(Memregion30086* a0, void* p0, NI size0);
static N_INLINE(void, osdeallocpages_29825_1689653243)(void* p0, NI size0);
static N_INLINE(void, deccurrmem_30216_1689653243)(Memregion30086* a0, NI bytes0);
N_NIMCALL(void, del_31201_1689653243)(Memregion30086* a0, Avlnode30084** t0, NI x0);
static N_INLINE(void, deallocavlnode_31003_1689653243)(Memregion30086* a0, Avlnode30084* n0);
N_NIMCALL(void, marks_68201_1689653243)(Gcheap50418* gch0, Cell47905* c0);
N_NOINLINE(void, incl_48647_1689653243)(Cellset47917* s0, Cell47905* cell0);
N_NIMCALL(Pagedesc47913*, cellsetput_48441_1689653243)(Cellset47917* t0, NI key0);
static N_INLINE(NI, nexttry_48054_1689653243)(NI h0, NI maxhash0);
N_NIMCALL(void, cellsetenlarge_48403_1689653243)(Cellset47917* t0);
N_NIMCALL(void, cellsetrawinsert_48079_1689653243)(Cellset47917* t0, Pagedesc47913** data0, Pagedesc47913* desc0);
N_NIMCALL(void, forallchildren_52414_1689653243)(Cell47905* cell0, Walkop50410 op0);
static N_INLINE(void*, celltousr_52022_1689653243)(Cell47905* cell0);
N_NIMCALL(void, forallchildrenaux_52422_1689653243)(void* dest0, TNimType* mt0, Walkop50410 op0);
N_NIMCALL(void, forallslotsaux_56432_1689653243)(void* dest0, TNimNode* n0, Walkop50410 op0);
N_NIMCALL(TNimNode*, selectbranch_27807_1689653243)(void* aa0, TNimNode* n0);
N_NIMCALL(NI, getdiscriminant_27404_1689653243)(void* aa0, TNimNode* n0);
N_NIMCALL(NIM_BOOL, containsorincl_48713_1689653243)(Cellset47917* s0, Cell47905* cell0);
N_NIMCALL(Pagedesc47913*, cellsetget_48059_1689653243)(Cellset47917* t0, NI key0);
N_NIMCALL(void, TMP4)(void* p, NI op);
N_NIMCALL(void, TMP5)();
N_NIMCALL(void, nimRegisterGlobalMarker)(Globalmarkerproc56402 markerproc0);
N_NOCONV(void, signalHandler)(int sign0);
N_NIMCALL(void, showerrormessage_19606_1689653243)(NCSTRING data0);
N_NIMCALL(NimStringDesc*, cstrToNimstr)(NCSTRING str0);
N_NIMCALL(NimStringDesc*, toNimStr)(NCSTRING str0, NI len0);
N_NIMCALL(NimStringDesc*, rawNewStringNoInit)(NI space0);
N_NIMCALL(void*, newObjNoInit)(TNimType* typ0, NI size0);
N_NIMCALL(void*, rawnewobj_58001_1689653243)(TNimType* typ0, NI size0, Gcheap50418* gch0);
N_NIMCALL(void, collectct_52407_1689653243)(Gcheap50418* gch0);
N_NOINLINE(NI, stacksize_71601_1689653243)(void);
static N_INLINE(NI, getoccupiedmem_47830_1689653243)(Memregion30086* a0);
N_NIMCALL(void, collectctbody_75409_1689653243)(Gcheap50418* gch0);
static N_INLINE(void, prepareforinteriorpointerchecking_45288_1689653243)(Memregion30086* a0);
N_NIMCALL(NI, lowgauge_31012_1689653243)(Avlnode30084* n0);
N_NIMCALL(NI, highgauge_31029_1689653243)(Avlnode30084* n0);
N_CDECL(void, markstackandregisters_73037_1689653243)(Gcheap50418* gch0);
static N_INLINE(void, gcmark_70610_1689653243)(Gcheap50418* gch0, void* p0);
N_NIMCALL(void*, interiorallocatedptr_45292_1689653243)(Memregion30086* a0, void* p0);
N_NIMCALL(Avlnode30084*, inrange_31081_1689653243)(Avlnode30084* root0, NI key0);
N_NIMCALL(NIM_BOOL, collectzct_70007_1689653243)(Gcheap50418* gch0);
N_NIMCALL(void, preparedealloc_52608_1689653243)(Cell47905* cell0);
N_NIMCALL(void, collectcycles_70011_1689653243)(Gcheap50418* gch0);
N_NIMCALL(void, cellsetreset_56428_1689653243)(Cellset47917* s0);
N_NIMCALL(void, deinit_48035_1689653243)(Cellset47917* s0);
N_NIMCALL(void, markglobals_68413_1689653243)(Gcheap50418* gch0);
N_NIMCALL(void, sweep_68001_1689653243)(Gcheap50418* gch0);
static N_INLINE(NIM_BOOL, iscell_31756_1689653243)(void* p0);
N_NIMCALL(NIM_BOOL, contains_48608_1689653243)(Cellset47917* s0, Cell47905* cell0);
N_NIMCALL(void, freecycliccell_66815_1689653243)(Gcheap50418* gch0, Cell47905* c0);
N_NIMCALL(NI, getoccupiedmem_8055_1689653243)(void);
N_NIMCALL(NI, gettotalmem_8059_1689653243)(void);
N_NIMCALL(NI, getfreemem_8057_1689653243)(void);
N_NIMCALL(void, unmarkstackandregisters_75202_1689653243)(Gcheap50418* gch0);
static N_INLINE(void, addnewobjtozct_57474_1689653243)(Cell47905* res0, Gcheap50418* gch0);
N_NIMCALL(void, writetostderr_19601_1689653243)(NCSTRING msg0);
N_NIMCALL(void, write_15701_1689653243)(FILE* f0, NCSTRING c0);
N_NIMCALL(void, registersignalhandler_23202_1689653243)(void);
N_NIMCALL(NI, getRefcount)(void* p0);
N_NIMCALL(NimStringDesc*, mnewString)(NI len0);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space0);
N_NIMCALL(void*, newObj)(TNimType* typ0, NI size0);
N_NIMCALL(NimStringDesc*, mnewString)(NI len0);
N_NIMCALL(NimStringDesc*, setLengthStr)(NimStringDesc* s0, NI newlen0);
N_NIMCALL(NimStringDesc*, resizeString)(NimStringDesc* dest0, NI addlen0);
static N_INLINE(NI, resize_79001_1689653243)(NI old0);
N_NIMCALL(void*, growobj_66809_1689653243)(void* old0, NI newsize0);
N_NIMCALL(void*, growobj_63803_1689653243)(void* old0, NI newsize0, Gcheap50418* gch0);
STRING_LITERAL(TMP2, "out of memory", 13);
STRING_LITERAL(TMP6, "[GC] cannot register global variable; too many global variables", 63);
NIM_BOOL nimvm_5554_1689653243;
NI nim_program_result;
TY10009 globalraisehook_10013_1689653243;
TY10014 localraisehook_10018_1689653243;
TY10019 outofmemhook_10021_1689653243;
TNimType strdesc_12403_1689653243;
TY19401 errormessagewriter_19404_1689653243;
TFrame* frameptr_19636_1689653243;
TSafePoint* exchandler_19637_1689653243;
Exception* currexception_19639_1689653243;
TNimType NTI3408; /* RootObj */
TNimType NTI3424; /* Exception */
TNimType NTI140; /* cstring */
TNimType NTI138; /* string */
TNimType NTI10010; /* ref Exception */
TY20003 tempframes_20004_1689653243;
Avlnode30084 bottomdata_30120_1689653243;
Avlnode30084* bottom_30121_1689653243;
Gcheap50418 gch_50458_1689653243;
NI globalmarkerslen_56407_1689653243;
TY56410 globalmarkers_56411_1689653243;

static N_INLINE(void, initallocator_11801_1689653243)(void) {
	bottom_30121_1689653243 = (&bottomdata_30120_1689653243);
	(*bottom_30121_1689653243).link[(((NI) 0))- 0] = bottom_30121_1689653243;
	(*bottom_30121_1689653243).link[(((NI) 1))- 0] = bottom_30121_1689653243;
}

N_NOINLINE(void, setStackBottom)(void* thestackbottom0) {
	{
		if (!(gch_50458_1689653243.stackbottom == NIM_NIL)) goto LA3;
		gch_50458_1689653243.stackbottom = thestackbottom0;
	}
	goto LA1;
	LA3: ;
	{
		NI a0;
		NI b0;
		a0 = ((NI) (thestackbottom0));
		b0 = ((NI) (gch_50458_1689653243.stackbottom));
		gch_50458_1689653243.stackbottom = ((void*) (((a0 >= b0) ? a0 : b0)));
	}
	LA1: ;
}

static N_INLINE(void, initStackBottom)(void) {
	void* volatile locals0;
	locals0 = (void*)0;
	locals0 = ((void*) ((&locals0)));
	setStackBottom(locals0);
}

static N_INLINE(NI, roundup_28601_1689653243)(NI x0, NI v0) {
	NI result0;
	result0 = (NI)0;
	result0 = (NI)((NI)(x0 + (NI)(v0 - ((NI) 1))) & (NI)((NU64) ~((NI)(v0 - ((NI) 1)))));
	return result0;
}

static N_INLINE(void, listremove_33602_1689653243)(Bigchunk30042** head0, Bigchunk30042* c0) {
	{
		if (!(c0 == (*head0))) goto LA3;
		(*head0) = (*c0).next;
		{
			if (!!(((*head0) == NIM_NIL))) goto LA7;
			(*(*head0)).prev = NIM_NIL;
		}
		LA7: ;
	}
	goto LA1;
	LA3: ;
	{
		(*(*c0).prev).next = (*c0).next;
		{
			if (!!(((*c0).next == NIM_NIL))) goto LA12;
			(*(*c0).next).prev = (*c0).prev;
		}
		LA12: ;
	}
	LA1: ;
	(*c0).next = NIM_NIL;
	(*c0).prev = NIM_NIL;
}

N_NIMCALL(Trunk30010*, intsetget_31283_1689653243)(Intset30014* t0, NI key0) {
	Trunk30010* result0;
	Trunk30010* it0;
{	result0 = (Trunk30010*)0;
	it0 = (*t0).data[((NI)(key0 & ((NI) 255)))- 0];
	{
		while (1) {
			if (!!((it0 == NIM_NIL))) goto LA2;
			{
				if (!((*it0).key == key0)) goto LA5;
				result0 = it0;
				goto BeforeRet;
			}
			LA5: ;
			it0 = (*it0).next;
		} LA2: ;
	}
	result0 = NIM_NIL;
	}BeforeRet: ;
	return result0;
}

N_NIMCALL(NIM_BOOL, contains_31332_1689653243)(Intset30014* s0, NI key0) {
	NIM_BOOL result0;
	Trunk30010* t0;
	result0 = (NIM_BOOL)0;
	t0 = intsetget_31283_1689653243(s0, (NI)((NU64)(key0) >> (NU64)(((NI) 9))));
	{
		NI u0;
		if (!!((t0 == NIM_NIL))) goto LA3;
		u0 = (NI)(key0 & ((NI) 511));
		result0 = !(((NI)((*t0).bits[((NI)((NU64)(((NI) (u0))) >> (NU64)(((NI) 6))))- 0] & (NI)((NU64)(((NI) 1)) << (NU64)(((NI) ((NI)(((NI) (u0)) & ((NI) 63))))))) == ((NI) 0)));
	}
	goto LA1;
	LA3: ;
	{
		result0 = NIM_FALSE;
	}
	LA1: ;
	return result0;
}

static N_INLINE(NI, pageindex_31776_1689653243)(void* p0) {
	NI result0;
	result0 = (NI)0;
	result0 = (NI)((NU64)(((NI) (p0))) >> (NU64)(((NI) 12)));
	return result0;
}

static N_INLINE(NIM_BOOL, isaccessible_32615_1689653243)(Memregion30086* a0, void* p0) {
	NIM_BOOL result0;
	NI LOC1;
	result0 = (NIM_BOOL)0;
	LOC1 = (NI)0;
	LOC1 = pageindex_31776_1689653243(p0);
	result0 = contains_31332_1689653243((&(*a0).chunkstarts), LOC1);
	return result0;
}

static N_INLINE(void, updateprevsize_32668_1689653243)(Memregion30086* a0, Bigchunk30042* c0, NI prevsize0) {
	Basechunk30038* ri0;
	ri0 = ((Basechunk30038*) ((NI)((NU64)(((NI) (c0))) + (NU64)((*c0).Sup.size))));
	{
		NIM_BOOL LOC3;
		LOC3 = (NIM_BOOL)0;
		LOC3 = isaccessible_32615_1689653243((&(*a0)), ((void*) (ri0)));
		if (!LOC3) goto LA4;
		(*ri0).prevsize = prevsize0;
	}
	LA4: ;
}

N_NOINLINE(void, raiseoutofmem_28234_1689653243)(void) {
	{
		if (!!((outofmemhook_10021_1689653243 == NIM_NIL))) goto LA3;
		outofmemhook_10021_1689653243();
	}
	LA3: ;
	printf("%s\012", ((NimStringDesc*) &TMP2)? (((NimStringDesc*) &TMP2))->data:"nil");
	fflush(stdout);
	exit(((NI) 1));
}

static N_INLINE(void*, osallocpages_29814_1689653243)(NI size0) {
	void* result0;
	result0 = (void*)0;
	result0 = mmap(NIM_NIL, size0, ((int) 3), (NI32)(((NI32) 2) | MAP_ANONYMOUS), ((int) -1), ((NI) 0));
	{
		NIM_BOOL LOC3;
		LOC3 = (NIM_BOOL)0;
		LOC3 = (result0 == NIM_NIL);
		if (LOC3) goto LA4;
		LOC3 = (result0 == ((void*) -1));
		LA4: ;
		if (!LOC3) goto LA5;
		raiseoutofmem_28234_1689653243();
	}
	LA5: ;
	return result0;
}

static N_INLINE(void, inccurrmem_30202_1689653243)(Memregion30086* a0, NI bytes0) {
	(*a0).currmem += bytes0;
}

N_NIMCALL(void*, llalloc_30243_1689653243)(Memregion30086* a0, NI size0) {
	void* result0;
	result0 = (void*)0;
	{
		NIM_BOOL LOC3;
		Llchunk30080* old0;
		void* LOC7;
		LOC3 = (NIM_BOOL)0;
		LOC3 = ((*a0).llmem == NIM_NIL);
		if (LOC3) goto LA4;
		LOC3 = ((*(*a0).llmem).size < size0);
		LA4: ;
		if (!LOC3) goto LA5;
		old0 = (*a0).llmem;
		LOC7 = (void*)0;
		LOC7 = osallocpages_29814_1689653243(((NI) 4096));
		(*a0).llmem = ((Llchunk30080*) (LOC7));
		inccurrmem_30202_1689653243(a0, ((NI) 4096));
		(*(*a0).llmem).size = (NI)(((NI) 4096) - ((NI)sizeof(Llchunk30080)));
		(*(*a0).llmem).acc = ((NI)sizeof(Llchunk30080));
		(*(*a0).llmem).next = old0;
	}
	LA5: ;
	result0 = ((void*) ((NI)(((NI) ((*a0).llmem)) + (*(*a0).llmem).acc)));
	(*(*a0).llmem).size -= size0;
	(*(*a0).llmem).acc += size0;
	zeroMem(result0, ((NI) (size0)));
	return result0;
}

N_NIMCALL(Trunk30010*, intsetput_31305_1689653243)(Memregion30086* a0, Intset30014* t0, NI key0) {
	Trunk30010* result0;
	result0 = (Trunk30010*)0;
	result0 = intsetget_31283_1689653243((&(*t0)), key0);
	{
		void* LOC5;
		if (!(result0 == NIM_NIL)) goto LA3;
		LOC5 = (void*)0;
		LOC5 = llalloc_30243_1689653243(a0, ((NI)sizeof(Trunk30010)));
		result0 = ((Trunk30010*) (LOC5));
		(*result0).next = (*t0).data[((NI)(key0 & ((NI) 255)))- 0];
		(*t0).data[((NI)(key0 & ((NI) 255)))- 0] = result0;
		(*result0).key = key0;
	}
	LA3: ;
	return result0;
}

N_NIMCALL(void, incl_31353_1689653243)(Memregion30086* a0, Intset30014* s0, NI key0) {
	Trunk30010* t0;
	NI u0;
	t0 = intsetput_31305_1689653243(a0, s0, (NI)((NU64)(key0) >> (NU64)(((NI) 9))));
	u0 = (NI)(key0 & ((NI) 511));
	(*t0).bits[((NI)((NU64)(((NI) (u0))) >> (NU64)(((NI) 6))))- 0] = (NI)((*t0).bits[((NI)((NU64)(((NI) (u0))) >> (NU64)(((NI) 6))))- 0] | (NI)((NU64)(((NI) 1)) << (NU64)(((NI) ((NI)(((NI) (u0)) & ((NI) 63)))))));
}

static N_INLINE(NI, pageindex_31771_1689653243)(Basechunk30038* c0) {
	NI result0;
	result0 = (NI)0;
	result0 = (NI)((NU64)(((NI) (c0))) >> (NU64)(((NI) 12)));
	return result0;
}

static N_INLINE(void, listadd_34823_1689653243)(Bigchunk30042** head0, Bigchunk30042* c0) {
	(*c0).next = (*head0);
	{
		if (!!(((*head0) == NIM_NIL))) goto LA3;
		(*(*head0)).prev = c0;
	}
	LA3: ;
	(*head0) = c0;
}

N_NIMCALL(void, splitchunk_35609_1689653243)(Memregion30086* a0, Bigchunk30042* c0, NI size0) {
	Bigchunk30042* rest0;
	Basechunk30038* LOC1;
	NI LOC2;
	rest0 = ((Bigchunk30042*) ((NI)((NU64)(((NI) (c0))) + (NU64)(size0))));
	(*rest0).Sup.size = (NI)((*c0).Sup.size - size0);
	(*rest0).Sup.used = NIM_FALSE;
	(*rest0).next = NIM_NIL;
	(*rest0).prev = NIM_NIL;
	(*rest0).Sup.prevsize = size0;
	updateprevsize_32668_1689653243(a0, c0, (*rest0).Sup.size);
	(*c0).Sup.size = size0;
	LOC1 = (Basechunk30038*)0;
	LOC1 = &rest0->Sup;
	LOC2 = (NI)0;
	LOC2 = pageindex_31771_1689653243(LOC1);
	incl_31353_1689653243(a0, (&(*a0).chunkstarts), LOC2);
	listadd_34823_1689653243(&(*a0).freechunkslist, rest0);
}

N_NIMCALL(Bigchunk30042*, requestoschunks_31788_1689653243)(Memregion30086* a0, NI size0) {
	Bigchunk30042* result0;
	void* LOC1;
	NI nxt0;
	Basechunk30038* next0;
	NI lastsize0;
	NI prv0;
	Basechunk30038* prev0;
	result0 = (Bigchunk30042*)0;
	inccurrmem_30202_1689653243(a0, size0);
	(*a0).freemem += size0;
	LOC1 = (void*)0;
	LOC1 = osallocpages_29814_1689653243(size0);
	result0 = ((Bigchunk30042*) (LOC1));
	(*result0).next = NIM_NIL;
	(*result0).prev = NIM_NIL;
	(*result0).Sup.used = NIM_FALSE;
	(*result0).Sup.size = size0;
	nxt0 = (NI)((NU64)(((NI) (result0))) + (NU64)(size0));
	next0 = ((Basechunk30038*) (nxt0));
	{
		NI LOC4;
		NIM_BOOL LOC5;
		LOC4 = (NI)0;
		LOC4 = pageindex_31771_1689653243(next0);
		LOC5 = (NIM_BOOL)0;
		LOC5 = contains_31332_1689653243((&(*a0).chunkstarts), LOC4);
		if (!LOC5) goto LA6;
		(*next0).prevsize = size0;
	}
	LA6: ;
	{
		if (!!(((*a0).lastsize == ((NI) 0)))) goto LA10;
		lastsize0 = (*a0).lastsize;
	}
	goto LA8;
	LA10: ;
	{
		lastsize0 = ((NI) 4096);
	}
	LA8: ;
	prv0 = (NI)((NU64)(((NI) (result0))) - (NU64)(lastsize0));
	prev0 = ((Basechunk30038*) (prv0));
	{
		NIM_BOOL LOC15;
		NI LOC16;
		LOC15 = (NIM_BOOL)0;
		LOC16 = (NI)0;
		LOC16 = pageindex_31771_1689653243(prev0);
		LOC15 = contains_31332_1689653243((&(*a0).chunkstarts), LOC16);
		if (!(LOC15)) goto LA17;
		LOC15 = ((*prev0).size == lastsize0);
		LA17: ;
		if (!LOC15) goto LA18;
		(*result0).Sup.prevsize = lastsize0;
	}
	goto LA13;
	LA18: ;
	{
		(*result0).Sup.prevsize = ((NI) 0);
	}
	LA13: ;
	(*a0).lastsize = size0;
	return result0;
}

N_NIMCALL(Bigchunk30042*, getbigchunk_35814_1689653243)(Memregion30086* a0, NI size0) {
	Bigchunk30042* result0;
	Basechunk30038* LOC16;
	NI LOC17;
	result0 = (Bigchunk30042*)0;
	result0 = (*a0).freechunkslist;
	{
		{
			while (1) {
				if (!!((result0 == NIM_NIL))) goto LA3;
				{
					if (!((*result0).Sup.size == size0)) goto LA6;
					listremove_33602_1689653243(&(*a0).freechunkslist, result0);
					goto LA1;
				}
				goto LA4;
				LA6: ;
				{
					if (!(size0 < (*result0).Sup.size)) goto LA9;
					listremove_33602_1689653243(&(*a0).freechunkslist, result0);
					splitchunk_35609_1689653243(a0, result0, size0);
					goto LA1;
				}
				goto LA4;
				LA9: ;
				LA4: ;
				result0 = (*result0).next;
			} LA3: ;
		}
		{
			if (!(size0 < ((NI) 524288))) goto LA13;
			result0 = requestoschunks_31788_1689653243(a0, ((NI) 524288));
			splitchunk_35609_1689653243(a0, result0, size0);
		}
		goto LA11;
		LA13: ;
		{
			result0 = requestoschunks_31788_1689653243(a0, size0);
		}
		LA11: ;
	} LA1: ;
	(*result0).Sup.prevsize = ((NI) 0);
	(*result0).Sup.used = NIM_TRUE;
	LOC16 = (Basechunk30038*)0;
	LOC16 = &result0->Sup;
	LOC17 = (NI)0;
	LOC17 = pageindex_31771_1689653243(LOC16);
	incl_31353_1689653243(a0, (&(*a0).chunkstarts), LOC17);
	(*a0).freemem -= size0;
	return result0;
}

N_NIMCALL(Smallchunk30040*, getsmallchunk_36612_1689653243)(Memregion30086* a0) {
	Smallchunk30040* result0;
	Bigchunk30042* res0;
	result0 = (Smallchunk30040*)0;
	res0 = getbigchunk_35814_1689653243(a0, ((NI) 4096));
	result0 = ((Smallchunk30040*) (res0));
	return result0;
}

static N_INLINE(void, listadd_38216_1689653243)(Smallchunk30040** head0, Smallchunk30040* c0) {
	(*c0).next = (*head0);
	{
		if (!!(((*head0) == NIM_NIL))) goto LA3;
		(*(*head0)).prev = c0;
	}
	LA3: ;
	(*head0) = c0;
}

static N_INLINE(void, listremove_41002_1689653243)(Smallchunk30040** head0, Smallchunk30040* c0) {
	{
		if (!(c0 == (*head0))) goto LA3;
		(*head0) = (*c0).next;
		{
			if (!!(((*head0) == NIM_NIL))) goto LA7;
			(*(*head0)).prev = NIM_NIL;
		}
		LA7: ;
	}
	goto LA1;
	LA3: ;
	{
		(*(*c0).prev).next = (*c0).next;
		{
			if (!!(((*c0).next == NIM_NIL))) goto LA12;
			(*(*c0).next).prev = (*c0).prev;
		}
		LA12: ;
	}
	LA1: ;
	(*c0).next = NIM_NIL;
	(*c0).prev = NIM_NIL;
}

N_NIMCALL(Avlnode30084*, allocavlnode_30427_1689653243)(Memregion30086* a0, NI key0, NI upperbound0) {
	Avlnode30084* result0;
	result0 = (Avlnode30084*)0;
	{
		if (!!(((*a0).freeavlnodes == NIM_NIL))) goto LA3;
		result0 = (*a0).freeavlnodes;
		(*a0).freeavlnodes = (*(*a0).freeavlnodes).link[(((NI) 0))- 0];
	}
	goto LA1;
	LA3: ;
	{
		void* LOC6;
		LOC6 = (void*)0;
		LOC6 = llalloc_30243_1689653243(a0, ((NI)sizeof(Avlnode30084)));
		result0 = ((Avlnode30084*) (LOC6));
	}
	LA1: ;
	(*result0).key = key0;
	(*result0).upperbound = upperbound0;
	(*result0).link[(((NI) 0))- 0] = bottom_30121_1689653243;
	(*result0).link[(((NI) 1))- 0] = bottom_30121_1689653243;
	(*result0).level = ((NI) 1);
	return result0;
}

N_NIMCALL(void, skew_31134_1689653243)(Avlnode30084** t0) {
	{
		Avlnode30084* temp0;
		if (!((*(*(*t0)).link[(((NI) 0))- 0]).level == (*(*t0)).level)) goto LA3;
		temp0 = (*t0);
		(*t0) = (*(*t0)).link[(((NI) 0))- 0];
		(*temp0).link[(((NI) 0))- 0] = (*(*t0)).link[(((NI) 1))- 0];
		(*(*t0)).link[(((NI) 1))- 0] = temp0;
	}
	LA3: ;
}

N_NIMCALL(void, split_31139_1689653243)(Avlnode30084** t0) {
	{
		Avlnode30084* temp0;
		if (!((*(*(*(*t0)).link[(((NI) 1))- 0]).link[(((NI) 1))- 0]).level == (*(*t0)).level)) goto LA3;
		temp0 = (*t0);
		(*t0) = (*(*t0)).link[(((NI) 1))- 0];
		(*temp0).link[(((NI) 1))- 0] = (*(*t0)).link[(((NI) 0))- 0];
		(*(*t0)).link[(((NI) 0))- 0] = temp0;
		(*(*t0)).level += ((NI) 1);
	}
	LA3: ;
}

N_NIMCALL(void, add_31153_1689653243)(Memregion30086* a0, Avlnode30084** t0, NI key0, NI upperbound0) {
	{
		if (!((*t0) == bottom_30121_1689653243)) goto LA3;
		(*t0) = allocavlnode_30427_1689653243(a0, key0, upperbound0);
	}
	goto LA1;
	LA3: ;
	{
		{
			if (!((NU64)(key0) < (NU64)((*(*t0)).key))) goto LA8;
			add_31153_1689653243(a0, &(*(*t0)).link[(((NI) 0))- 0], key0, upperbound0);
		}
		goto LA6;
		LA8: ;
		{
			if (!((NU64)((*(*t0)).key) < (NU64)(key0))) goto LA11;
			add_31153_1689653243(a0, &(*(*t0)).link[(((NI) 1))- 0], key0, upperbound0);
		}
		goto LA6;
		LA11: ;
		{
		}
		LA6: ;
		skew_31134_1689653243(t0);
		split_31139_1689653243(t0);
	}
	LA1: ;
}

N_NIMCALL(void*, rawalloc_37204_1689653243)(Memregion30086* a0, NI requestedsize0) {
	void* result0;
	NI size0;
	result0 = (void*)0;
	size0 = roundup_28601_1689653243(requestedsize0, ((NI) 8));
	{
		NI s0;
		Smallchunk30040* c0;
		if (!(size0 <= (NI)(((NI) 4096) - (NI)(((NI)sizeof(Smallchunk30040)) - ((NI) 8))))) goto LA3;
		s0 = (NI)(size0 / ((NI) 8));
		c0 = (*a0).freesmallchunks[(s0)- 0];
		{
			if (!(c0 == NIM_NIL)) goto LA7;
			c0 = getsmallchunk_36612_1689653243(a0);
			(*c0).freelist = NIM_NIL;
			(*c0).Sup.size = size0;
			(*c0).acc = size0;
			(*c0).free = (NI)((NI)(((NI) 4096) - (NI)(((NI)sizeof(Smallchunk30040)) - ((NI) 8))) - size0);
			(*c0).next = NIM_NIL;
			(*c0).prev = NIM_NIL;
			listadd_38216_1689653243(&(*a0).freesmallchunks[(s0)- 0], c0);
			result0 = ((void*) ((&(*c0).data)));
		}
		goto LA5;
		LA7: ;
		{
			{
				if (!((*c0).freelist == NIM_NIL)) goto LA12;
				result0 = ((void*) ((NI)((NU64)(((NI) ((&(*c0).data)))) + (NU64)((*c0).acc))));
				(*c0).acc += size0;
			}
			goto LA10;
			LA12: ;
			{
				result0 = ((void*) ((*c0).freelist));
				(*c0).freelist = (*(*c0).freelist).next;
			}
			LA10: ;
			(*c0).free -= size0;
		}
		LA5: ;
		{
			if (!((*c0).free < size0)) goto LA17;
			listremove_41002_1689653243(&(*a0).freesmallchunks[(s0)- 0], c0);
		}
		LA17: ;
	}
	goto LA1;
	LA3: ;
	{
		Bigchunk30042* c0;
		size0 = roundup_28601_1689653243((NI)(requestedsize0 + (NI)(((NI)sizeof(Bigchunk30042)) - ((NI) 8))), ((NI) 4096));
		c0 = getbigchunk_35814_1689653243(a0, size0);
		result0 = ((void*) ((&(*c0).data)));
		{
			if (!((*a0).root == NIM_NIL)) goto LA22;
			(*a0).root = bottom_30121_1689653243;
		}
		LA22: ;
		add_31153_1689653243(a0, &(*a0).root, ((NI) (result0)), (NI)((NU64)(((NI) (result0))) + (NU64)(size0)));
	}
	LA1: ;
	return result0;
}

N_NIMCALL(void*, alloc_46440_1689653243)(Memregion30086* allocator0, NI size0) {
	void* result0;
	result0 = (void*)0;
	result0 = rawalloc_37204_1689653243(allocator0, (NI)(((NI) (size0)) + ((NI)sizeof(Freecell30030))));
	(*((Freecell30030*) (result0))).zerofield = ((NI) 1);
	result0 = ((void*) ((NI)((NU64)(((NI) (result0))) + (NU64)(((NI)sizeof(Freecell30030))))));
	return result0;
}

N_NIMCALL(void*, alloc0_46616_1689653243)(Memregion30086* allocator0, NI size0) {
	void* result0;
	result0 = (void*)0;
	result0 = alloc_46440_1689653243(allocator0, size0);
	zeroMem(result0, size0);
	return result0;
}

N_NOCONV(void*, alloc0_7417_1689653243)(NI size0) {
	void* result0;
	result0 = (void*)0;
	result0 = alloc0_46616_1689653243((&gch_50458_1689653243.region), size0);
	return result0;
}

N_NIMCALL(void, init_48012_1689653243)(Cellseq47921* s0, NI cap0) {
	void* LOC1;
	(*s0).len = ((NI) 0);
	(*s0).cap = cap0;
	LOC1 = (void*)0;
	LOC1 = alloc0_7417_1689653243(((NI) ((NI)(cap0 * ((NI) 8)))));
	(*s0).d = ((Cell47905**) (LOC1));
}

N_NIMCALL(void, init_48027_1689653243)(Cellset47917* s0) {
	void* LOC1;
	LOC1 = (void*)0;
	LOC1 = alloc0_7417_1689653243(((NI) 8192));
	(*s0).data = ((Pagedesc47913**) (LOC1));
	(*s0).max = ((NI) 1023);
	(*s0).counter = ((NI) 0);
	(*s0).head = NIM_NIL;
}

N_NIMCALL(void, initgc_11601_1689653243)(void) {
	gch_50458_1689653243.cyclethreshold = ((NI) 4194304);
	gch_50458_1689653243.stat.stackscans = ((NI) 0);
	gch_50458_1689653243.stat.cyclecollections = ((NI) 0);
	gch_50458_1689653243.stat.maxthreshold = ((NI) 0);
	gch_50458_1689653243.stat.maxstacksize = ((NI) 0);
	gch_50458_1689653243.stat.maxstackcells = ((NI) 0);
	gch_50458_1689653243.stat.cycletablesize = ((NI) 0);
	init_48012_1689653243((&gch_50458_1689653243.zct), ((NI) 1024));
	init_48012_1689653243((&gch_50458_1689653243.tempstack), ((NI) 1024));
	init_48012_1689653243((&gch_50458_1689653243.decstack), ((NI) 1024));
	init_48027_1689653243((&gch_50458_1689653243.marked));
	init_48012_1689653243((&gch_50458_1689653243.additionalroots), ((NI) 1024));
}

static N_INLINE(Cell47905*, usrtocell_52040_1689653243)(void* usr0) {
	Cell47905* result0;
	result0 = (Cell47905*)0;
	result0 = ((Cell47905*) ((NI)((NU64)(((NI) (usr0))) - (NU64)(((NI)sizeof(Cell47905))))));
	return result0;
}

N_NOCONV(void*, alloc_7401_1689653243)(NI size0) {
	void* result0;
	result0 = (void*)0;
	result0 = alloc_46440_1689653243((&gch_50458_1689653243.region), size0);
	return result0;
}

static N_INLINE(Basechunk30038*, pageaddr_31781_1689653243)(void* p0) {
	Basechunk30038* result0;
	result0 = (Basechunk30038*)0;
	result0 = ((Basechunk30038*) ((NI)(((NI) (p0)) & ((NI) -4096))));
	return result0;
}

static N_INLINE(NIM_BOOL, issmallchunk_31669_1689653243)(Basechunk30038* c0) {
	NIM_BOOL result0;
{	result0 = (NIM_BOOL)0;
	result0 = ((*c0).size <= (NI)(((NI) 4096) - (NI)(((NI)sizeof(Smallchunk30040)) - ((NI) 8))));
	goto BeforeRet;
	}BeforeRet: ;
	return result0;
}

static N_INLINE(NIM_BOOL, chunkunused_31689_1689653243)(Basechunk30038* c0) {
	NIM_BOOL result0;
	result0 = (NIM_BOOL)0;
	result0 = !((*c0).used);
	return result0;
}

N_NIMCALL(void, excl_31364_1689653243)(Intset30014* s0, NI key0) {
	Trunk30010* t0;
	t0 = intsetget_31283_1689653243((&(*s0)), (NI)((NU64)(key0) >> (NU64)(((NI) 9))));
	{
		NI u0;
		if (!!((t0 == NIM_NIL))) goto LA3;
		u0 = (NI)(key0 & ((NI) 511));
		(*t0).bits[((NI)((NU64)(((NI) (u0))) >> (NU64)(((NI) 6))))- 0] = (NI)((*t0).bits[((NI)((NU64)(((NI) (u0))) >> (NU64)(((NI) 6))))- 0] & (NI)((NU64) ~((NI)((NU64)(((NI) 1)) << (NU64)(((NI) ((NI)(((NI) (u0)) & ((NI) 63)))))))));
	}
	LA3: ;
}

static N_INLINE(void, osdeallocpages_29825_1689653243)(void* p0, NI size0) {
	int LOC1;
	LOC1 = (int)0;
	LOC1 = munmap(p0, size0);
}

static N_INLINE(void, deccurrmem_30216_1689653243)(Memregion30086* a0, NI bytes0) {
	(*a0).maxmem = (((*a0).maxmem >= (*a0).currmem) ? (*a0).maxmem : (*a0).currmem);
	(*a0).currmem -= bytes0;
}

N_NIMCALL(void, freeoschunks_32407_1689653243)(Memregion30086* a0, void* p0, NI size0) {
	Basechunk30038* c0;
	NI nxt0;
	Basechunk30038* next0;
	NI LOC7;
	c0 = ((Basechunk30038*) (p0));
	nxt0 = (NI)((NU64)(((NI) (p0))) + (NU64)((*c0).size));
	next0 = ((Basechunk30038*) (nxt0));
	{
		NI LOC3;
		NIM_BOOL LOC4;
		LOC3 = (NI)0;
		LOC3 = pageindex_31771_1689653243(next0);
		LOC4 = (NIM_BOOL)0;
		LOC4 = contains_31332_1689653243((&(*a0).chunkstarts), LOC3);
		if (!LOC4) goto LA5;
		(*next0).prevsize = ((NI) 0);
	}
	LA5: ;
	LOC7 = (NI)0;
	LOC7 = pageindex_31776_1689653243(p0);
	excl_31364_1689653243((&(*a0).chunkstarts), LOC7);
	osdeallocpages_29825_1689653243(p0, size0);
	deccurrmem_30216_1689653243(a0, size0);
	(*a0).freemem -= size0;
}

N_NIMCALL(void, freebigchunk_32803_1689653243)(Memregion30086* a0, Bigchunk30042* c_32807_1689653243) {
	Bigchunk30042* c0;
	Basechunk30038* ri0;
	c0 = c_32807_1689653243;
	(*a0).freemem += (*c0).Sup.size;
	ri0 = ((Basechunk30038*) ((NI)((NU64)(((NI) (c0))) + (NU64)((*c0).Sup.size))));
	{
		NIM_BOOL LOC3;
		LOC3 = (NIM_BOOL)0;
		LOC3 = isaccessible_32615_1689653243((&(*a0)), ((void*) (ri0)));
		if (!(LOC3)) goto LA4;
		LOC3 = chunkunused_31689_1689653243(ri0);
		LA4: ;
		if (!LOC3) goto LA5;
		{
			NIM_BOOL LOC9;
			NI LOC12;
			LOC9 = (NIM_BOOL)0;
			LOC9 = issmallchunk_31669_1689653243(ri0);
			if (!!(LOC9)) goto LA10;
			listremove_33602_1689653243(&(*a0).freechunkslist, ((Bigchunk30042*) (ri0)));
			(*c0).Sup.size += (*ri0).size;
			LOC12 = (NI)0;
			LOC12 = pageindex_31771_1689653243(ri0);
			excl_31364_1689653243((&(*a0).chunkstarts), LOC12);
		}
		LA10: ;
	}
	LA5: ;
	{
		Basechunk30038* le0;
		if (!!(((*c0).Sup.prevsize == ((NI) 0)))) goto LA15;
		le0 = ((Basechunk30038*) ((NI)((NU64)(((NI) (c0))) - (NU64)((*c0).Sup.prevsize))));
		{
			NIM_BOOL LOC19;
			LOC19 = (NIM_BOOL)0;
			LOC19 = isaccessible_32615_1689653243((&(*a0)), ((void*) (le0)));
			if (!(LOC19)) goto LA20;
			LOC19 = chunkunused_31689_1689653243(le0);
			LA20: ;
			if (!LOC19) goto LA21;
			{
				NIM_BOOL LOC25;
				Basechunk30038* LOC28;
				NI LOC29;
				LOC25 = (NIM_BOOL)0;
				LOC25 = issmallchunk_31669_1689653243(le0);
				if (!!(LOC25)) goto LA26;
				listremove_33602_1689653243(&(*a0).freechunkslist, ((Bigchunk30042*) (le0)));
				(*le0).size += (*c0).Sup.size;
				LOC28 = (Basechunk30038*)0;
				LOC28 = &c0->Sup;
				LOC29 = (NI)0;
				LOC29 = pageindex_31771_1689653243(LOC28);
				excl_31364_1689653243((&(*a0).chunkstarts), LOC29);
				c0 = ((Bigchunk30042*) (le0));
			}
			LA26: ;
		}
		LA21: ;
	}
	LA15: ;
	{
		NIM_BOOL LOC32;
		NIM_BOOL LOC33;
		Basechunk30038* LOC38;
		NI LOC39;
		LOC32 = (NIM_BOOL)0;
		LOC33 = (NIM_BOOL)0;
		LOC33 = ((*c0).Sup.size < ((NI) 1048576));
		if (LOC33) goto LA34;
		LOC33 = NIM_FALSE;
		LA34: ;
		LOC32 = LOC33;
		if (LOC32) goto LA35;
		LOC32 = (*a0).locked;
		LA35: ;
		if (!LOC32) goto LA36;
		LOC38 = (Basechunk30038*)0;
		LOC38 = &c0->Sup;
		LOC39 = (NI)0;
		LOC39 = pageindex_31771_1689653243(LOC38);
		incl_31353_1689653243(a0, (&(*a0).chunkstarts), LOC39);
		updateprevsize_32668_1689653243(a0, c0, (*c0).Sup.size);
		listadd_34823_1689653243(&(*a0).freechunkslist, c0);
		(*c0).Sup.used = NIM_FALSE;
	}
	goto LA30;
	LA36: ;
	{
		freeoschunks_32407_1689653243(a0, ((void*) (c0)), (*c0).Sup.size);
	}
	LA30: ;
}

static N_INLINE(void, deallocavlnode_31003_1689653243)(Memregion30086* a0, Avlnode30084* n0) {
	(*n0).link[(((NI) 0))- 0] = (*a0).freeavlnodes;
	(*a0).freeavlnodes = n0;
}

N_NIMCALL(void, del_31201_1689653243)(Memregion30086* a0, Avlnode30084** t0, NI x0) {
{	{
		if (!((*t0) == bottom_30121_1689653243)) goto LA3;
		goto BeforeRet;
	}
	LA3: ;
	(*a0).last = (*t0);
	{
		if (!((NU64)(x0) < (NU64)((*(*t0)).key))) goto LA7;
		del_31201_1689653243(a0, &(*(*t0)).link[(((NI) 0))- 0], x0);
	}
	goto LA5;
	LA7: ;
	{
		(*a0).deleted = (*t0);
		del_31201_1689653243(a0, &(*(*t0)).link[(((NI) 1))- 0], x0);
	}
	LA5: ;
	{
		NIM_BOOL LOC12;
		NIM_BOOL LOC13;
		LOC12 = (NIM_BOOL)0;
		LOC13 = (NIM_BOOL)0;
		LOC13 = ((*t0) == (*a0).last);
		if (!(LOC13)) goto LA14;
		LOC13 = !(((*a0).deleted == bottom_30121_1689653243));
		LA14: ;
		LOC12 = LOC13;
		if (!(LOC12)) goto LA15;
		LOC12 = (x0 == (*(*a0).deleted).key);
		LA15: ;
		if (!LOC12) goto LA16;
		(*(*a0).deleted).key = (*(*t0)).key;
		(*(*a0).deleted).upperbound = (*(*t0)).upperbound;
		(*a0).deleted = bottom_30121_1689653243;
		(*t0) = (*(*t0)).link[(((NI) 1))- 0];
		deallocavlnode_31003_1689653243(a0, (*a0).last);
	}
	goto LA10;
	LA16: ;
	{
		NIM_BOOL LOC19;
		LOC19 = (NIM_BOOL)0;
		LOC19 = ((*(*(*t0)).link[(((NI) 0))- 0]).level < (NI)((*(*t0)).level - ((NI) 1)));
		if (LOC19) goto LA20;
		LOC19 = ((*(*(*t0)).link[(((NI) 1))- 0]).level < (NI)((*(*t0)).level - ((NI) 1)));
		LA20: ;
		if (!LOC19) goto LA21;
		(*(*t0)).level -= ((NI) 1);
		{
			if (!((*(*t0)).level < (*(*(*t0)).link[(((NI) 1))- 0]).level)) goto LA25;
			(*(*(*t0)).link[(((NI) 1))- 0]).level = (*(*t0)).level;
		}
		LA25: ;
		skew_31134_1689653243(t0);
		skew_31134_1689653243(&(*(*t0)).link[(((NI) 1))- 0]);
		skew_31134_1689653243(&(*(*(*t0)).link[(((NI) 1))- 0]).link[(((NI) 1))- 0]);
		split_31139_1689653243(t0);
		split_31139_1689653243(&(*(*t0)).link[(((NI) 1))- 0]);
	}
	goto LA10;
	LA21: ;
	LA10: ;
	}BeforeRet: ;
}

N_NIMCALL(void, rawdealloc_43617_1689653243)(Memregion30086* a0, void* p0) {
	Basechunk30038* c_43801_1689653243;
	c_43801_1689653243 = pageaddr_31781_1689653243(p0);
	{
		NIM_BOOL LOC3;
		Smallchunk30040* c0;
		NI s0;
		Freecell30030* f0;
		LOC3 = (NIM_BOOL)0;
		LOC3 = issmallchunk_31669_1689653243(c_43801_1689653243);
		if (!LOC3) goto LA4;
		c0 = ((Smallchunk30040*) (c_43801_1689653243));
		s0 = (*c0).Sup.size;
		f0 = ((Freecell30030*) (p0));
		(*f0).zerofield = ((NI) 0);
		(*f0).next = (*c0).freelist;
		(*c0).freelist = f0;
		{
			if (!((*c0).free < s0)) goto LA8;
			listadd_38216_1689653243(&(*a0).freesmallchunks[((NI)(s0 / ((NI) 8)))- 0], c0);
			(*c0).free += s0;
		}
		goto LA6;
		LA8: ;
		{
			(*c0).free += s0;
			{
				if (!((*c0).free == (NI)(((NI) 4096) - (NI)(((NI)sizeof(Smallchunk30040)) - ((NI) 8))))) goto LA13;
				listremove_41002_1689653243(&(*a0).freesmallchunks[((NI)(s0 / ((NI) 8)))- 0], c0);
				(*c0).Sup.size = ((NI) 4096);
				freebigchunk_32803_1689653243(a0, ((Bigchunk30042*) (c0)));
			}
			LA13: ;
		}
		LA6: ;
	}
	goto LA1;
	LA4: ;
	{
		Bigchunk30042* c0;
		c0 = ((Bigchunk30042*) (c_43801_1689653243));
		(*a0).deleted = bottom_30121_1689653243;
		del_31201_1689653243(a0, &(*a0).root, ((NI) ((&(*c0).data))));
		freebigchunk_32803_1689653243(a0, c0);
	}
	LA1: ;
}

N_NIMCALL(void, dealloc_46622_1689653243)(Memregion30086* allocator0, void* p0) {
	void* x0;
	x0 = ((void*) ((NI)((NU64)(((NI) (p0))) - (NU64)(((NI)sizeof(Freecell30030))))));
	rawdealloc_43617_1689653243(allocator0, x0);
}

N_NOCONV(void, dealloc_7448_1689653243)(void* p0) {
	dealloc_46622_1689653243((&gch_50458_1689653243.region), p0);
}

static N_INLINE(void, add_47992_1689653243)(Cellseq47921* s0, Cell47905* c0) {
	{
		Cell47905** d0;
		void* LOC5;
		if (!((*s0).cap <= (*s0).len)) goto LA3;
		(*s0).cap = (NI)((NI)((*s0).cap * ((NI) 3)) / ((NI) 2));
		LOC5 = (void*)0;
		LOC5 = alloc_7401_1689653243(((NI) ((NI)((*s0).cap * ((NI) 8)))));
		d0 = ((Cell47905**) (LOC5));
		memcpy(((void*) (d0)), ((void*) ((*s0).d)), ((NI) ((NI)((*s0).len * ((NI) 8)))));
		dealloc_7448_1689653243(((void*) ((*s0).d)));
		(*s0).d = d0;
	}
	LA3: ;
	(*s0).d[((*s0).len)- 0] = c0;
	(*s0).len += ((NI) 1);
}

N_NOINLINE(void, addzct_52017_1689653243)(Cellseq47921* s0, Cell47905* c0) {
	{
		if (!((NI)((*c0).refcount & ((NI) 4)) == ((NI) 0))) goto LA3;
		(*c0).refcount = (NI)((*c0).refcount | ((NI) 4));
		add_47992_1689653243(s0, c0);
	}
	LA3: ;
}

static N_INLINE(void, rtladdzct_53201_1689653243)(Cell47905* c0) {
	addzct_52017_1689653243((&gch_50458_1689653243.zct), c0);
}

static N_INLINE(void, decref_53601_1689653243)(Cell47905* c0) {
	{
		(*c0).refcount -= ((NI) 8);
		if (!((NU64)((*c0).refcount) < (NU64)(((NI) 8)))) goto LA3;
		rtladdzct_53201_1689653243(c0);
	}
	LA3: ;
}

static N_INLINE(NI, nexttry_48054_1689653243)(NI h0, NI maxhash0) {
	NI result0;
	result0 = (NI)0;
	result0 = (NI)((NI)((NI)(((NI) 5) * h0) + ((NI) 1)) & maxhash0);
	return result0;
}

N_NIMCALL(void, cellsetrawinsert_48079_1689653243)(Cellset47917* t0, Pagedesc47913** data0, Pagedesc47913* desc0) {
	NI h0;
	h0 = (NI)(((NI) ((*desc0).key)) & (*t0).max);
	{
		while (1) {
			if (!!((data0[(h0)- 0] == NIM_NIL))) goto LA2;
			h0 = nexttry_48054_1689653243(h0, (*t0).max);
		} LA2: ;
	}
	data0[(h0)- 0] = desc0;
}

N_NIMCALL(void, cellsetenlarge_48403_1689653243)(Cellset47917* t0) {
	NI oldmax0;
	Pagedesc47913** n0;
	void* LOC1;
	oldmax0 = (*t0).max;
	(*t0).max = (NI)((NI)((NI)((*t0).max + ((NI) 1)) * ((NI) 2)) - ((NI) 1));
	LOC1 = (void*)0;
	LOC1 = alloc0_7417_1689653243(((NI) ((NI)((NI)((*t0).max + ((NI) 1)) * ((NI) 8)))));
	n0 = ((Pagedesc47913**) (LOC1));
	{
		NI i_48419_1689653243;
		NI res_48437_1689653243;
		i_48419_1689653243 = (NI)0;
		res_48437_1689653243 = ((NI) 0);
		{
			while (1) {
				if (!(res_48437_1689653243 <= oldmax0)) goto LA4;
				i_48419_1689653243 = res_48437_1689653243;
				{
					if (!!(((*t0).data[(i_48419_1689653243)- 0] == NIM_NIL))) goto LA7;
					cellsetrawinsert_48079_1689653243((&(*t0)), n0, (*t0).data[(i_48419_1689653243)- 0]);
				}
				LA7: ;
				res_48437_1689653243 += ((NI) 1);
			} LA4: ;
		}
	}
	dealloc_7448_1689653243(((void*) ((*t0).data)));
	(*t0).data = n0;
}

N_NIMCALL(Pagedesc47913*, cellsetput_48441_1689653243)(Cellset47917* t0, NI key0) {
	Pagedesc47913* result0;
	NI h0;
	void* LOC19;
{	result0 = (Pagedesc47913*)0;
	h0 = (NI)(((NI) (key0)) & (*t0).max);
	{
		while (1) {
			Pagedesc47913* x0;
			x0 = (*t0).data[(h0)- 0];
			{
				if (!(x0 == NIM_NIL)) goto LA5;
				goto LA1;
			}
			LA5: ;
			{
				if (!((*x0).key == key0)) goto LA9;
				result0 = x0;
				goto BeforeRet;
			}
			LA9: ;
			h0 = nexttry_48054_1689653243(h0, (*t0).max);
		}
	} LA1: ;
	{
		NIM_BOOL LOC13;
		LOC13 = (NIM_BOOL)0;
		LOC13 = ((NI)((NI)((*t0).max + ((NI) 1)) * ((NI) 2)) < (NI)((*t0).counter * ((NI) 3)));
		if (LOC13) goto LA14;
		LOC13 = ((NI)((NI)((*t0).max + ((NI) 1)) - (*t0).counter) < ((NI) 4));
		LA14: ;
		if (!LOC13) goto LA15;
		cellsetenlarge_48403_1689653243(t0);
	}
	LA15: ;
	(*t0).counter += ((NI) 1);
	h0 = (NI)(((NI) (key0)) & (*t0).max);
	{
		while (1) {
			if (!!(((*t0).data[(h0)- 0] == NIM_NIL))) goto LA18;
			h0 = nexttry_48054_1689653243(h0, (*t0).max);
		} LA18: ;
	}
	LOC19 = (void*)0;
	LOC19 = alloc0_7417_1689653243(((NI) (((NI)sizeof(Pagedesc47913)))));
	result0 = ((Pagedesc47913*) (LOC19));
	(*result0).next = (*t0).head;
	(*result0).key = key0;
	(*t0).head = result0;
	(*t0).data[(h0)- 0] = result0;
	}BeforeRet: ;
	return result0;
}

N_NOINLINE(void, incl_48647_1689653243)(Cellset47917* s0, Cell47905* cell0) {
	NI u0;
	Pagedesc47913* t0;
	u0 = ((NI) (cell0));
	t0 = cellsetput_48441_1689653243(s0, (NI)((NU64)(u0) >> (NU64)(((NI) 12))));
	u0 = (NI)((NU64)((NI)((NU64)(u0) % (NU64)(((NI) 4096)))) / (NU64)(((NI) 8)));
	(*t0).bits[((NI)((NU64)(u0) >> (NU64)(((NI) 6))))- 0] = (NI)((*t0).bits[((NI)((NU64)(u0) >> (NU64)(((NI) 6))))- 0] | (NI)((NU64)(((NI) 1)) << (NU64)(((NI) ((NI)(u0 & ((NI) 63)))))));
}

static N_INLINE(void*, celltousr_52022_1689653243)(Cell47905* cell0) {
	void* result0;
	result0 = (void*)0;
	result0 = ((void*) ((NI)((NU64)(((NI) (cell0))) + (NU64)(((NI)sizeof(Cell47905))))));
	return result0;
}

N_NIMCALL(NI, getdiscriminant_27404_1689653243)(void* aa0, TNimNode* n0) {
	NI result0;
	NI d0;
	NI a0;
{	result0 = (NI)0;
	d0 = (NI)0;
	a0 = ((NI) (aa0));
	switch ((*(*n0).typ).size) {
	case ((NI) 1):
	{
		d0 = ((NI)(NU)(NU8)((*((NI8*) ((NI)((NU64)(a0) + (NU64)((*n0).offset)))))));
	}
	break;
	case ((NI) 2):
	{
		d0 = ((NI)(NU)(NU16)((*((NI16*) ((NI)((NU64)(a0) + (NU64)((*n0).offset)))))));
	}
	break;
	case ((NI) 4):
	{
		d0 = ((NI) ((*((NI32*) ((NI)((NU64)(a0) + (NU64)((*n0).offset)))))));
	}
	break;
	default:
	{
	}
	break;
	}
	result0 = d0;
	goto BeforeRet;
	}BeforeRet: ;
	return result0;
}

N_NIMCALL(TNimNode*, selectbranch_27807_1689653243)(void* aa0, TNimNode* n0) {
	TNimNode* result0;
	NI discr0;
	result0 = (TNimNode*)0;
	discr0 = getdiscriminant_27404_1689653243(aa0, n0);
	{
		if (!((NU64)(discr0) < (NU64)((*n0).len))) goto LA3;
		result0 = (*n0).sons[(discr0)- 0];
		{
			if (!(result0 == NIM_NIL)) goto LA7;
			result0 = (*n0).sons[((*n0).len)- 0];
		}
		LA7: ;
	}
	goto LA1;
	LA3: ;
	{
		result0 = (*n0).sons[((*n0).len)- 0];
	}
	LA1: ;
	return result0;
}

N_NIMCALL(void, forallslotsaux_56432_1689653243)(void* dest0, TNimNode* n0, Walkop50410 op0) {
	NI d0;
	d0 = ((NI) (dest0));
	switch ((*n0).kind) {
	case ((Tnimnodekind3205) 1):
	{
		forallchildrenaux_52422_1689653243(((void*) ((NI)((NU64)(d0) + (NU64)((*n0).offset)))), (*n0).typ, op0);
	}
	break;
	case ((Tnimnodekind3205) 2):
	{
		{
			NI i_56457_1689653243;
			NI HEX3Atmp_56606_1689653243;
			NI res_56609_1689653243;
			i_56457_1689653243 = (NI)0;
			HEX3Atmp_56606_1689653243 = (NI)0;
			HEX3Atmp_56606_1689653243 = (NI)((*n0).len - ((NI) 1));
			res_56609_1689653243 = ((NI) 0);
			{
				while (1) {
					if (!(res_56609_1689653243 <= HEX3Atmp_56606_1689653243)) goto LA5;
					i_56457_1689653243 = res_56609_1689653243;
					{
						if (!((*(*n0).sons[(i_56457_1689653243)- 0]).kind == ((Tnimnodekind3205) 1))) goto LA8;
						{
							if (!((289406976 &((NU64)1<<((NU)((*(*(*n0).sons[(i_56457_1689653243)- 0]).typ).kind)&63U)))!=0)) goto LA12;
							dooperation_52418_1689653243((*((void**) ((NI)((NU64)(d0) + (NU64)((*(*n0).sons[(i_56457_1689653243)- 0]).offset))))), op0);
						}
						goto LA10;
						LA12: ;
						{
							forallchildrenaux_52422_1689653243(((void*) ((NI)((NU64)(d0) + (NU64)((*(*n0).sons[(i_56457_1689653243)- 0]).offset)))), (*(*n0).sons[(i_56457_1689653243)- 0]).typ, op0);
						}
						LA10: ;
					}
					goto LA6;
					LA8: ;
					{
						forallslotsaux_56432_1689653243(dest0, (*n0).sons[(i_56457_1689653243)- 0], op0);
					}
					LA6: ;
					res_56609_1689653243 += ((NI) 1);
				} LA5: ;
			}
		}
	}
	break;
	case ((Tnimnodekind3205) 3):
	{
		TNimNode* m0;
		m0 = selectbranch_27807_1689653243(dest0, n0);
		{
			if (!!((m0 == NIM_NIL))) goto LA19;
			forallslotsaux_56432_1689653243(dest0, m0, op0);
		}
		LA19: ;
	}
	break;
	case ((Tnimnodekind3205) 0):
	{
	}
	break;
	}
}

N_NIMCALL(void, forallchildrenaux_52422_1689653243)(void* dest0, TNimType* mt0, Walkop50410 op0) {
	NI d0;
{	d0 = ((NI) (dest0));
	{
		if (!(dest0 == NIM_NIL)) goto LA3;
		goto BeforeRet;
	}
	LA3: ;
	{
		if (!!((((*mt0).flags &(1U<<((NU)(((Tnimtypeflag3209) 0))&7U)))!=0))) goto LA7;
		switch ((*mt0).kind) {
		case ((Tnimkind3203) 22):
		case ((Tnimkind3203) 28):
		case ((Tnimkind3203) 24):
		{
			dooperation_52418_1689653243((*((void**) (d0))), op0);
		}
		break;
		case ((Tnimkind3203) 17):
		case ((Tnimkind3203) 18):
		{
			forallslotsaux_56432_1689653243(dest0, (*mt0).node, op0);
		}
		break;
		case ((Tnimkind3203) 16):
		case ((Tnimkind3203) 4):
		case ((Tnimkind3203) 27):
		{
			{
				NI i_56638_1689653243;
				NI HEX3Atmp_56661_1689653243;
				NI res_56664_1689653243;
				i_56638_1689653243 = (NI)0;
				HEX3Atmp_56661_1689653243 = (NI)0;
				HEX3Atmp_56661_1689653243 = (NI)((NI)((*mt0).size / (*(*mt0).base).size) - ((NI) 1));
				res_56664_1689653243 = ((NI) 0);
				{
					while (1) {
						if (!(res_56664_1689653243 <= HEX3Atmp_56661_1689653243)) goto LA14;
						i_56638_1689653243 = res_56664_1689653243;
						forallchildrenaux_52422_1689653243(((void*) ((NI)((NU64)(d0) + (NU64)((NI)((NU64)(i_56638_1689653243) * (NU64)((*(*mt0).base).size)))))), (*mt0).base, op0);
						res_56664_1689653243 += ((NI) 1);
					} LA14: ;
				}
			}
		}
		break;
		default:
		{
		}
		break;
		}
	}
	LA7: ;
	}BeforeRet: ;
}

N_NIMCALL(void, forallchildren_52414_1689653243)(Cell47905* cell0, Walkop50410 op0) {
	TY3289 marker0;
	marker0 = (*(*cell0).typ).marker;
	{
		void* LOC5;
		if (!!((marker0 == NIM_NIL))) goto LA3;
		LOC5 = (void*)0;
		LOC5 = celltousr_52022_1689653243(cell0);
		marker0(LOC5, ((NI) (op0)));
	}
	goto LA1;
	LA3: ;
	{
		switch ((*(*cell0).typ).kind) {
		case ((Tnimkind3203) 22):
		{
			void* LOC8;
			LOC8 = (void*)0;
			LOC8 = celltousr_52022_1689653243(cell0);
			forallchildrenaux_52422_1689653243(LOC8, (*(*cell0).typ).base, op0);
		}
		break;
		case ((Tnimkind3203) 24):
		{
			NI d0;
			void* LOC10;
			TGenericSeq* s0;
			LOC10 = (void*)0;
			LOC10 = celltousr_52022_1689653243(cell0);
			d0 = ((NI) (LOC10));
			s0 = ((TGenericSeq*) (d0));
			{
				if (!!((s0 == NIM_NIL))) goto LA13;
				{
					NI i_57434_1689653243;
					NI HEX3Atmp_57467_1689653243;
					NI res_57470_1689653243;
					i_57434_1689653243 = (NI)0;
					HEX3Atmp_57467_1689653243 = (NI)0;
					HEX3Atmp_57467_1689653243 = (NI)((*s0).len - ((NI) 1));
					res_57470_1689653243 = ((NI) 0);
					{
						while (1) {
							if (!(res_57470_1689653243 <= HEX3Atmp_57467_1689653243)) goto LA17;
							i_57434_1689653243 = res_57470_1689653243;
							forallchildrenaux_52422_1689653243(((void*) ((NI)((NU64)((NI)((NU64)(d0) + (NU64)((NI)((NU64)(i_57434_1689653243) * (NU64)((*(*(*cell0).typ).base).size))))) + (NU64)(((NI) 16))))), (*(*cell0).typ).base, op0);
							res_57470_1689653243 += ((NI) 1);
						} LA17: ;
					}
				}
			}
			LA13: ;
		}
		break;
		default:
		{
		}
		break;
		}
	}
	LA1: ;
}

N_NIMCALL(Pagedesc47913*, cellsetget_48059_1689653243)(Cellset47917* t0, NI key0) {
	Pagedesc47913* result0;
	NI h0;
{	result0 = (Pagedesc47913*)0;
	h0 = (NI)(((NI) (key0)) & (*t0).max);
	{
		while (1) {
			if (!!(((*t0).data[(h0)- 0] == NIM_NIL))) goto LA2;
			{
				if (!((*(*t0).data[(h0)- 0]).key == key0)) goto LA5;
				result0 = (*t0).data[(h0)- 0];
				goto BeforeRet;
			}
			LA5: ;
			h0 = nexttry_48054_1689653243(h0, (*t0).max);
		} LA2: ;
	}
	result0 = NIM_NIL;
	goto BeforeRet;
	}BeforeRet: ;
	return result0;
}

N_NIMCALL(NIM_BOOL, containsorincl_48713_1689653243)(Cellset47917* s0, Cell47905* cell0) {
	NIM_BOOL result0;
	NI u0;
	Pagedesc47913* t0;
	result0 = (NIM_BOOL)0;
	u0 = ((NI) (cell0));
	t0 = cellsetget_48059_1689653243((&(*s0)), (NI)((NU64)(u0) >> (NU64)(((NI) 12))));
	{
		if (!!((t0 == NIM_NIL))) goto LA3;
		u0 = (NI)((NU64)((NI)((NU64)(u0) % (NU64)(((NI) 4096)))) / (NU64)(((NI) 8)));
		result0 = !(((NI)((*t0).bits[((NI)((NU64)(u0) >> (NU64)(((NI) 6))))- 0] & (NI)((NU64)(((NI) 1)) << (NU64)(((NI) ((NI)(u0 & ((NI) 63))))))) == ((NI) 0)));
		{
			if (!!(result0)) goto LA7;
			(*t0).bits[((NI)((NU64)(u0) >> (NU64)(((NI) 6))))- 0] = (NI)((*t0).bits[((NI)((NU64)(u0) >> (NU64)(((NI) 6))))- 0] | (NI)((NU64)(((NI) 1)) << (NU64)(((NI) ((NI)(u0 & ((NI) 63)))))));
		}
		LA7: ;
	}
	goto LA1;
	LA3: ;
	{
		incl_48647_1689653243(s0, cell0);
		result0 = NIM_FALSE;
	}
	LA1: ;
	return result0;
}

N_NIMCALL(void, marks_68201_1689653243)(Gcheap50418* gch0, Cell47905* c0) {
	incl_48647_1689653243((&(*gch0).marked), c0);
	forallchildren_52414_1689653243(c0, ((Walkop50410) 1));
	{
		while (1) {
			Cell47905* d0;
			if (!(((NI) 0) < (*gch0).tempstack.len)) goto LA2;
			(*gch0).tempstack.len -= ((NI) 1);
			d0 = (*gch0).tempstack.d[((*gch0).tempstack.len)- 0];
			{
				NIM_BOOL LOC5;
				LOC5 = (NIM_BOOL)0;
				LOC5 = containsorincl_48713_1689653243((&(*gch0).marked), d0);
				if (!!(LOC5)) goto LA6;
				forallchildren_52414_1689653243(d0, ((Walkop50410) 1));
			}
			LA6: ;
		} LA2: ;
	}
}

N_NIMCALL(void, dooperation_52418_1689653243)(void* p0, Walkop50410 op0) {
	Cell47905* c0;
{	{
		if (!(p0 == NIM_NIL)) goto LA3;
		goto BeforeRet;
	}
	LA3: ;
	c0 = usrtocell_52040_1689653243(p0);
	switch (op0) {
	case ((Walkop50410) 2):
	{
		decref_53601_1689653243(c0);
	}
	break;
	case ((Walkop50410) 3):
	{
		add_47992_1689653243((&gch_50458_1689653243.tempstack), c0);
	}
	break;
	case ((Walkop50410) 0):
	{
		marks_68201_1689653243((&gch_50458_1689653243), c0);
	}
	break;
	case ((Walkop50410) 1):
	{
		add_47992_1689653243((&gch_50458_1689653243.tempstack), c0);
	}
	break;
	}
	}BeforeRet: ;
}

N_NIMCALL(void, nimGCvisit)(void* d0, NI op0) {
	dooperation_52418_1689653243(d0, ((Walkop50410) (op0)));
}
N_NIMCALL(void, TMP4)(void* p, NI op) {
	Exception* a;
	a = (Exception*)p;
	nimGCvisit((void*)(*a).parent, op);
	nimGCvisit((void*)(*a).message, op);
	nimGCvisit((void*)(*a).trace, op);
}
N_NIMCALL(void, TMP5)() {
	nimGCvisit((void*)currexception_19639_1689653243, 0);
}

N_NIMCALL(void, nimRegisterGlobalMarker)(Globalmarkerproc56402 markerproc0) {
	{
		if (!(globalmarkerslen_56407_1689653243 <= ((NI) 7000))) goto LA3;
		globalmarkers_56411_1689653243[(globalmarkerslen_56407_1689653243)- 0] = markerproc0;
		globalmarkerslen_56407_1689653243 += ((NI) 1);
	}
	goto LA1;
	LA3: ;
	{
		printf("%s\012", ((NimStringDesc*) &TMP6)? (((NimStringDesc*) &TMP6))->data:"nil");
		fflush(stdout);
		exit(((NI) 1));
	}
	LA1: ;
}

N_NOINLINE(NI, stacksize_71601_1689653243)(void) {
	NI result0;
	void* volatile stacktop0;
	result0 = (NI)0;
	stacktop0 = (void*)0;
	result0 = ((NI)(((NI) ((&stacktop0))) - ((NI) (gch_50458_1689653243.stackbottom))) > 0? ((NI)(((NI) ((&stacktop0))) - ((NI) (gch_50458_1689653243.stackbottom)))) : -((NI)(((NI) ((&stacktop0))) - ((NI) (gch_50458_1689653243.stackbottom)))));
	return result0;
}

static N_INLINE(NI, getoccupiedmem_47830_1689653243)(Memregion30086* a0) {
	NI result0;
	result0 = (NI)0;
	result0 = (NI)((*a0).currmem - (*a0).freemem);
	return result0;
}

N_NIMCALL(NI, lowgauge_31012_1689653243)(Avlnode30084* n0) {
	NI result0;
	Avlnode30084* it0;
	result0 = (NI)0;
	it0 = n0;
	{
		while (1) {
			if (!!((it0 == bottom_30121_1689653243))) goto LA2;
			result0 = (*it0).key;
			it0 = (*it0).link[(((NI) 0))- 0];
		} LA2: ;
	}
	return result0;
}

N_NIMCALL(NI, highgauge_31029_1689653243)(Avlnode30084* n0) {
	NI result0;
	Avlnode30084* it0;
	result0 = (NI)0;
	result0 = ((NI) -1);
	it0 = n0;
	{
		while (1) {
			if (!!((it0 == bottom_30121_1689653243))) goto LA2;
			result0 = (*it0).upperbound;
			it0 = (*it0).link[(((NI) 1))- 0];
		} LA2: ;
	}
	return result0;
}

static N_INLINE(void, prepareforinteriorpointerchecking_45288_1689653243)(Memregion30086* a0) {
	(*a0).minlargeobj = lowgauge_31012_1689653243((*a0).root);
	(*a0).maxlargeobj = highgauge_31029_1689653243((*a0).root);
}

N_NIMCALL(Avlnode30084*, inrange_31081_1689653243)(Avlnode30084* root0, NI key0) {
	Avlnode30084* result0;
	Avlnode30084* it0;
{	result0 = (Avlnode30084*)0;
	it0 = root0;
	{
		while (1) {
			if (!!((it0 == bottom_30121_1689653243))) goto LA2;
			{
				NIM_BOOL LOC5;
				LOC5 = (NIM_BOOL)0;
				LOC5 = ((NU64)((*it0).key) <= (NU64)(key0));
				if (!(LOC5)) goto LA6;
				LOC5 = ((NU64)(key0) < (NU64)((*it0).upperbound));
				LA6: ;
				if (!LOC5) goto LA7;
				result0 = it0;
				goto BeforeRet;
			}
			LA7: ;
			it0 = (*it0).link[(((NU64)((*it0).key) < (NU64)(key0)))- 0];
		} LA2: ;
	}
	}BeforeRet: ;
	return result0;
}

N_NIMCALL(void*, interiorallocatedptr_45292_1689653243)(Memregion30086* a0, void* p0) {
	void* result0;
	result0 = (void*)0;
	{
		NIM_BOOL LOC3;
		Basechunk30038* c_45297_1689653243;
		LOC3 = (NIM_BOOL)0;
		LOC3 = isaccessible_32615_1689653243(a0, p0);
		if (!LOC3) goto LA4;
		c_45297_1689653243 = pageaddr_31781_1689653243(p0);
		{
			NIM_BOOL LOC8;
			LOC8 = (NIM_BOOL)0;
			LOC8 = chunkunused_31689_1689653243(c_45297_1689653243);
			if (!!(LOC8)) goto LA9;
			{
				NIM_BOOL LOC13;
				Smallchunk30040* c0;
				NI offset0;
				LOC13 = (NIM_BOOL)0;
				LOC13 = issmallchunk_31669_1689653243(c_45297_1689653243);
				if (!LOC13) goto LA14;
				c0 = ((Smallchunk30040*) (c_45297_1689653243));
				offset0 = (NI)((NU64)(((NI) ((NI)(((NI) (p0)) & ((NI) 4095))))) - (NU64)((NI)(((NI)sizeof(Smallchunk30040)) - ((NI) 8))));
				{
					Freecell30030* d0;
					if (!((NU64)(offset0) < (NU64)((*c0).acc))) goto LA18;
					d0 = ((Freecell30030*) ((NI)((NU64)((NI)((NU64)(((NI) ((&(*c0).data)))) + (NU64)(offset0))) - (NU64)((NI)((NU64)(offset0) % (NU64)((*c0).Sup.size))))));
					{
						if (!((NU64)(((NI) 1)) < (NU64)((*d0).zerofield))) goto LA22;
						result0 = ((void*) (d0));
					}
					LA22: ;
				}
				LA18: ;
			}
			goto LA11;
			LA14: ;
			{
				Bigchunk30042* c0;
				NF* d0;
				c0 = ((Bigchunk30042*) (c_45297_1689653243));
				d0 = (&(*c0).data);
				{
					NIM_BOOL LOC27;
					LOC27 = (NIM_BOOL)0;
					LOC27 = (((void*) (d0)) <= p0);
					if (!(LOC27)) goto LA28;
					LOC27 = ((NU64)(((NI) 1)) < (NU64)((*((Freecell30030*) (d0))).zerofield));
					LA28: ;
					if (!LOC27) goto LA29;
					result0 = ((void*) (d0));
				}
				LA29: ;
			}
			LA11: ;
		}
		LA9: ;
	}
	goto LA1;
	LA4: ;
	{
		NI q0;
		q0 = ((NI) (p0));
		{
			NIM_BOOL LOC34;
			Avlnode30084* avlnode0;
			LOC34 = (NIM_BOOL)0;
			LOC34 = ((NU64)((*a0).minlargeobj) <= (NU64)(q0));
			if (!(LOC34)) goto LA35;
			LOC34 = ((NU64)(q0) <= (NU64)((*a0).maxlargeobj));
			LA35: ;
			if (!LOC34) goto LA36;
			avlnode0 = inrange_31081_1689653243((*a0).root, q0);
			{
				void* k0;
				Bigchunk30042* c0;
				Basechunk30038* LOC42;
				if (!!((avlnode0 == NIM_NIL))) goto LA40;
				k0 = ((void*) ((*avlnode0).key));
				LOC42 = (Basechunk30038*)0;
				LOC42 = pageaddr_31781_1689653243(k0);
				c0 = ((Bigchunk30042*) (LOC42));
				{
					if (!((NU64)(((NI) 1)) < (NU64)((*((Freecell30030*) (k0))).zerofield))) goto LA45;
					result0 = k0;
				}
				LA45: ;
			}
			LA40: ;
		}
		LA36: ;
	}
	LA1: ;
	return result0;
}

static N_INLINE(void, gcmark_70610_1689653243)(Gcheap50418* gch0, void* p0) {
	Cell47905* cell0;
	NI c0;
	cell0 = usrtocell_52040_1689653243(p0);
	c0 = ((NI) (cell0));
	{
		Cell47905* objstart0;
		void* LOC5;
		if (!((NU64)(((NI) 4096)) < (NU64)(c0))) goto LA3;
		LOC5 = (void*)0;
		LOC5 = interiorallocatedptr_45292_1689653243((&(*gch0).region), ((void*) (cell0)));
		objstart0 = ((Cell47905*) (LOC5));
		{
			if (!!((objstart0 == NIM_NIL))) goto LA8;
			(*objstart0).refcount = (NI)((NU64)((*objstart0).refcount) + (NU64)(((NI) 8)));
			add_47992_1689653243((&(*gch0).decstack), objstart0);
		}
		LA8: ;
	}
	LA3: ;
}

N_CDECL(void, markstackandregisters_73037_1689653243)(Gcheap50418* gch0) {
	jmp_buf registers0;
	{
		int LOC3;
		NI max0;
		NI sp0;
		NI regend0;
		LOC3 = (int)0;
		LOC3 = setjmp(registers0);
		if (!(LOC3 == ((NI32) 0))) goto LA4;
		max0 = ((NI) ((*gch0).stackbottom));
		sp0 = ((NI) ((&registers0)));
		regend0 = (NI)((NU64)(sp0) + (NU64)(((NI)sizeof(jmp_buf))));
		{
			while (1) {
				if (!((NU64)(sp0) < (NU64)(regend0))) goto LA7;
				gcmark_70610_1689653243(gch0, (*((void**) (sp0))));
				gcmark_70610_1689653243(gch0, (*((void**) ((NI)((NU64)(sp0) + (NU64)(((NI) 4)))))));
				sp0 = (NI)((NU64)(sp0) + (NU64)(((NI) 8)));
			} LA7: ;
		}
		sp0 = (NI)(sp0 & ((NI) -8));
		{
			while (1) {
				if (!((NU64)(sp0) < (NU64)((NI)(max0 - ((NI) 64))))) goto LA9;
				gcmark_70610_1689653243(gch0, ((void**) (sp0))[(((NI) 0))- 0]);
				gcmark_70610_1689653243(gch0, ((void**) (sp0))[(((NI) 1))- 0]);
				gcmark_70610_1689653243(gch0, ((void**) (sp0))[(((NI) 2))- 0]);
				gcmark_70610_1689653243(gch0, ((void**) (sp0))[(((NI) 3))- 0]);
				gcmark_70610_1689653243(gch0, ((void**) (sp0))[(((NI) 4))- 0]);
				gcmark_70610_1689653243(gch0, ((void**) (sp0))[(((NI) 5))- 0]);
				gcmark_70610_1689653243(gch0, ((void**) (sp0))[(((NI) 6))- 0]);
				gcmark_70610_1689653243(gch0, ((void**) (sp0))[(((NI) 7))- 0]);
				sp0 = (NI)((NU64)(sp0) + (NU64)(((NI) 64)));
			} LA9: ;
		}
		{
			while (1) {
				if (!((NU64)(sp0) <= (NU64)(max0))) goto LA11;
				gcmark_70610_1689653243(gch0, (*((void**) (sp0))));
				sp0 = (NI)((NU64)(sp0) + (NU64)(((NI) 8)));
			} LA11: ;
		}
	}
	LA4: ;
}

N_NIMCALL(void, preparedealloc_52608_1689653243)(Cell47905* cell0) {
	{
		void* LOC5;
		if (!!(((*(*cell0).typ).finalizer == NIM_NIL))) goto LA3;
		gch_50458_1689653243.recgclock += ((NI) 1);
		LOC5 = (void*)0;
		LOC5 = celltousr_52022_1689653243(cell0);
		((Finalizer) ((*(*cell0).typ).finalizer))(LOC5);
		gch_50458_1689653243.recgclock -= ((NI) 1);
	}
	LA3: ;
}

N_NIMCALL(NIM_BOOL, collectzct_70007_1689653243)(Gcheap50418* gch0) {
	NIM_BOOL result0;
	NI* L0;
	result0 = (NIM_BOOL)0;
	L0 = (&(*gch0).zct.len);
	{
		while (1) {
			Cell47905* c0;
			if (!(((NI) 0) < (*L0))) goto LA2;
			c0 = (*gch0).zct.d[(((NI) 0))- 0];
			(*c0).refcount = (NI)((*c0).refcount & ((NI) -5));
			(*gch0).zct.d[(((NI) 0))- 0] = (*gch0).zct.d[((NI)((*L0) - ((NI) 1)))- 0];
			(*L0) -= ((NI) 1);
			{
				if (!((NU64)((*c0).refcount) < (NU64)(((NI) 8)))) goto LA5;
				preparedealloc_52608_1689653243(c0);
				forallchildren_52414_1689653243(c0, ((Walkop50410) 2));
				rawdealloc_43617_1689653243((&(*gch0).region), ((void*) (c0)));
			}
			LA5: ;
		} LA2: ;
	}
	result0 = NIM_TRUE;
	return result0;
}

N_NIMCALL(void, deinit_48035_1689653243)(Cellset47917* s0) {
	Pagedesc47913* it0;
	it0 = (*s0).head;
	{
		while (1) {
			Pagedesc47913* n0;
			if (!!((it0 == NIM_NIL))) goto LA2;
			n0 = (*it0).next;
			dealloc_7448_1689653243(((void*) (it0)));
			it0 = n0;
		} LA2: ;
	}
	(*s0).head = NIM_NIL;
	dealloc_7448_1689653243(((void*) ((*s0).data)));
	(*s0).data = NIM_NIL;
	(*s0).counter = ((NI) 0);
}

N_NIMCALL(void, cellsetreset_56428_1689653243)(Cellset47917* s0) {
	deinit_48035_1689653243(s0);
	init_48027_1689653243(s0);
}

N_NIMCALL(void, markglobals_68413_1689653243)(Gcheap50418* gch0) {
	Cell47905** d0;
	{
		NI i_68434_1689653243;
		NI HEX3Atmp_68455_1689653243;
		NI res_68458_1689653243;
		i_68434_1689653243 = (NI)0;
		HEX3Atmp_68455_1689653243 = (NI)0;
		HEX3Atmp_68455_1689653243 = (globalmarkerslen_56407_1689653243 - 1);
		res_68458_1689653243 = ((NI) 0);
		{
			while (1) {
				if (!(res_68458_1689653243 <= HEX3Atmp_68455_1689653243)) goto LA3;
				i_68434_1689653243 = res_68458_1689653243;
				globalmarkers_56411_1689653243[(i_68434_1689653243)- 0]();
				res_68458_1689653243 += ((NI) 1);
			} LA3: ;
		}
	}
	d0 = (*gch0).additionalroots.d;
	{
		NI i_68453_1689653243;
		NI HEX3Atmp_68463_1689653243;
		NI res_68466_1689653243;
		i_68453_1689653243 = (NI)0;
		HEX3Atmp_68463_1689653243 = (NI)0;
		HEX3Atmp_68463_1689653243 = ((*gch0).additionalroots.len - 1);
		res_68466_1689653243 = ((NI) 0);
		{
			while (1) {
				if (!(res_68466_1689653243 <= HEX3Atmp_68463_1689653243)) goto LA6;
				i_68453_1689653243 = res_68466_1689653243;
				marks_68201_1689653243(gch0, d0[(i_68453_1689653243)- 0]);
				res_68466_1689653243 += ((NI) 1);
			} LA6: ;
		}
	}
}

static N_INLINE(NIM_BOOL, iscell_31756_1689653243)(void* p0) {
	NIM_BOOL result0;
	result0 = (NIM_BOOL)0;
	result0 = ((NU64)(((NI) 1)) < (NU64)((*((Freecell30030*) (p0))).zerofield));
	return result0;
}

N_NIMCALL(NIM_BOOL, contains_48608_1689653243)(Cellset47917* s0, Cell47905* cell0) {
	NIM_BOOL result0;
	NI u0;
	Pagedesc47913* t0;
	result0 = (NIM_BOOL)0;
	u0 = ((NI) (cell0));
	t0 = cellsetget_48059_1689653243(s0, (NI)((NU64)(u0) >> (NU64)(((NI) 12))));
	{
		if (!!((t0 == NIM_NIL))) goto LA3;
		u0 = (NI)((NU64)((NI)((NU64)(u0) % (NU64)(((NI) 4096)))) / (NU64)(((NI) 8)));
		result0 = !(((NI)((*t0).bits[((NI)((NU64)(u0) >> (NU64)(((NI) 6))))- 0] & (NI)((NU64)(((NI) 1)) << (NU64)(((NI) ((NI)(u0 & ((NI) 63))))))) == ((NI) 0)));
	}
	goto LA1;
	LA3: ;
	{
		result0 = NIM_FALSE;
	}
	LA1: ;
	return result0;
}

N_NIMCALL(void, freecycliccell_66815_1689653243)(Gcheap50418* gch0, Cell47905* c0) {
	preparedealloc_52608_1689653243(c0);
	rawdealloc_43617_1689653243((&(*gch0).region), ((void*) (c0)));
}

N_NIMCALL(void, sweep_68001_1689653243)(Gcheap50418* gch0) {
	{
		void* x_68006_1689653243;
		x_68006_1689653243 = (void*)0;
		(*gch0).region.locked = NIM_TRUE;
		{
			NI s_68018_1689653243;
			Intset30014 HEX3Atmp_68020_1689653243;
			s_68018_1689653243 = (NI)0;
			memset((void*)(&HEX3Atmp_68020_1689653243), 0, sizeof(HEX3Atmp_68020_1689653243));
			HEX3Atmp_68020_1689653243 = (*gch0).region.chunkstarts;
			{
				NI h_68022_1689653243;
				NI res_68024_1689653243;
				h_68022_1689653243 = (NI)0;
				res_68024_1689653243 = ((NI) 0);
				{
					while (1) {
						Trunk30010* r_68026_1689653243;
						if (!(res_68024_1689653243 <= ((NI) 255))) goto LA5;
						h_68022_1689653243 = ((NI) (res_68024_1689653243));
						r_68026_1689653243 = HEX3Atmp_68020_1689653243.data[(h_68022_1689653243)- 0];
						{
							while (1) {
								NI i_68028_1689653243;
								if (!!((r_68026_1689653243 == NIM_NIL))) goto LA7;
								i_68028_1689653243 = ((NI) 0);
								{
									while (1) {
										NI w_68030_1689653243;
										NI j_68032_1689653243;
										if (!(i_68028_1689653243 <= ((NI) 7))) goto LA9;
										w_68030_1689653243 = (*r_68026_1689653243).bits[(i_68028_1689653243)- 0];
										j_68032_1689653243 = ((NI) 0);
										{
											while (1) {
												if (!!((w_68030_1689653243 == ((NI) 0)))) goto LA11;
												{
													if (!!((((NI) ((NI)(w_68030_1689653243 & ((NI) 1)))) == ((NI) 0)))) goto LA14;
													s_68018_1689653243 = (NI)((NI)((NU64)((*r_68026_1689653243).key) << (NU64)(((NI) 9))) | (NI)((NU64)((NI)((NU64)(i_68028_1689653243) << (NU64)(((NI) 6)))) + (NU64)(j_68032_1689653243)));
													{
														NIM_BOOL LOC18;
														Basechunk30038* c_68034_1689653243;
														LOC18 = (NIM_BOOL)0;
														LOC18 = contains_31332_1689653243((&(*gch0).region.chunkstarts), s_68018_1689653243);
														if (!LOC18) goto LA19;
														c_68034_1689653243 = ((Basechunk30038*) ((NI)((NU64)(s_68018_1689653243) << (NU64)(((NI) 12)))));
														{
															NIM_BOOL LOC23;
															LOC23 = (NIM_BOOL)0;
															LOC23 = chunkunused_31689_1689653243(c_68034_1689653243);
															if (!!(LOC23)) goto LA24;
															{
																NIM_BOOL LOC28;
																Smallchunk30040* c_68037_1689653243;
																NI size_68040_1689653243;
																NI a_68042_1689653243;
																NI limit_68045_1689653243;
																LOC28 = (NIM_BOOL)0;
																LOC28 = issmallchunk_31669_1689653243(c_68034_1689653243);
																if (!LOC28) goto LA29;
																c_68037_1689653243 = ((Smallchunk30040*) (c_68034_1689653243));
																size_68040_1689653243 = (*c_68037_1689653243).Sup.size;
																a_68042_1689653243 = ((NI) ((&(*c_68037_1689653243).data)));
																limit_68045_1689653243 = (NI)(a_68042_1689653243 + (*c_68037_1689653243).acc);
																{
																	while (1) {
																		if (!((NU64)(a_68042_1689653243) < (NU64)(limit_68045_1689653243))) goto LA32;
																		x_68006_1689653243 = ((void*) (a_68042_1689653243));
																		{
																			NIM_BOOL LOC35;
																			Cell47905* c0;
																			LOC35 = (NIM_BOOL)0;
																			LOC35 = iscell_31756_1689653243(x_68006_1689653243);
																			if (!LOC35) goto LA36;
																			c0 = ((Cell47905*) (x_68006_1689653243));
																			{
																				NIM_BOOL LOC40;
																				LOC40 = (NIM_BOOL)0;
																				LOC40 = contains_48608_1689653243((&(*gch0).marked), c0);
																				if (!!(LOC40)) goto LA41;
																				freecycliccell_66815_1689653243(gch0, c0);
																			}
																			LA41: ;
																		}
																		LA36: ;
																		a_68042_1689653243 = (NI)((NU64)(a_68042_1689653243) + (NU64)(size_68040_1689653243));
																	} LA32: ;
																}
															}
															goto LA26;
															LA29: ;
															{
																Bigchunk30042* c_68048_1689653243;
																c_68048_1689653243 = ((Bigchunk30042*) (c_68034_1689653243));
																x_68006_1689653243 = ((void*) ((&(*c_68048_1689653243).data)));
																{
																	NIM_BOOL LOC46;
																	Cell47905* c_68051_1689653243;
																	LOC46 = (NIM_BOOL)0;
																	LOC46 = iscell_31756_1689653243(x_68006_1689653243);
																	if (!LOC46) goto LA47;
																	c_68051_1689653243 = ((Cell47905*) (x_68006_1689653243));
																	{
																		NIM_BOOL LOC51;
																		LOC51 = (NIM_BOOL)0;
																		LOC51 = contains_48608_1689653243((&(*gch0).marked), c_68051_1689653243);
																		if (!!(LOC51)) goto LA52;
																		freecycliccell_66815_1689653243(gch0, c_68051_1689653243);
																	}
																	LA52: ;
																}
																LA47: ;
															}
															LA26: ;
														}
														LA24: ;
													}
													LA19: ;
												}
												LA14: ;
												j_68032_1689653243 += ((NI) 1);
												w_68030_1689653243 = (NI)((NU64)(w_68030_1689653243) >> (NU64)(((NI) 1)));
											} LA11: ;
										}
										i_68028_1689653243 += ((NI) 1);
									} LA9: ;
								}
								r_68026_1689653243 = (*r_68026_1689653243).next;
							} LA7: ;
						}
						res_68024_1689653243 += ((NI) 1);
					} LA5: ;
				}
			}
		}
		(*gch0).region.locked = NIM_FALSE;
	}
}

N_NIMCALL(void, collectcycles_70011_1689653243)(Gcheap50418* gch0) {
	Cell47905** d0;
	{
		while (1) {
			NIM_BOOL LOC3;
			if (!(((NI) 0) < (*gch0).zct.len)) goto LA2;
			LOC3 = (NIM_BOOL)0;
			LOC3 = collectzct_70007_1689653243(gch0);
		} LA2: ;
	}
	cellsetreset_56428_1689653243((&(*gch0).marked));
	d0 = (*gch0).decstack.d;
	{
		NI i_70412_1689653243;
		NI HEX3Atmp_70603_1689653243;
		NI res_70606_1689653243;
		i_70412_1689653243 = (NI)0;
		HEX3Atmp_70603_1689653243 = (NI)0;
		HEX3Atmp_70603_1689653243 = (NI)((*gch0).decstack.len - ((NI) 1));
		res_70606_1689653243 = ((NI) 0);
		{
			while (1) {
				if (!(res_70606_1689653243 <= HEX3Atmp_70603_1689653243)) goto LA6;
				i_70412_1689653243 = res_70606_1689653243;
				marks_68201_1689653243(gch0, d0[(i_70412_1689653243)- 0]);
				res_70606_1689653243 += ((NI) 1);
			} LA6: ;
		}
	}
	markglobals_68413_1689653243(gch0);
	sweep_68001_1689653243(gch0);
}

N_NIMCALL(NI, gettotalmem_8059_1689653243)(void) {
	NI result0;
{	result0 = (NI)0;
	result0 = gch_50458_1689653243.region.currmem;
	goto BeforeRet;
	}BeforeRet: ;
	return result0;
}

N_NIMCALL(NI, getfreemem_8057_1689653243)(void) {
	NI result0;
	result0 = (NI)0;
	result0 = gch_50458_1689653243.region.freemem;
	return result0;
}

N_NIMCALL(NI, getoccupiedmem_8055_1689653243)(void) {
	NI result0;
	NI LOC1;
	NI LOC2;
{	result0 = (NI)0;
	LOC1 = (NI)0;
	LOC1 = gettotalmem_8059_1689653243();
	LOC2 = (NI)0;
	LOC2 = getfreemem_8057_1689653243();
	result0 = (NI)(LOC1 - LOC2);
	goto BeforeRet;
	}BeforeRet: ;
	return result0;
}

N_NIMCALL(void, unmarkstackandregisters_75202_1689653243)(Gcheap50418* gch0) {
	Cell47905** d0;
	d0 = (*gch0).decstack.d;
	{
		NI i_75216_1689653243;
		NI HEX3Atmp_75402_1689653243;
		NI res_75405_1689653243;
		i_75216_1689653243 = (NI)0;
		HEX3Atmp_75402_1689653243 = (NI)0;
		HEX3Atmp_75402_1689653243 = (NI)((*gch0).decstack.len - ((NI) 1));
		res_75405_1689653243 = ((NI) 0);
		{
			while (1) {
				if (!(res_75405_1689653243 <= HEX3Atmp_75402_1689653243)) goto LA3;
				i_75216_1689653243 = res_75405_1689653243;
				decref_53601_1689653243(d0[(i_75216_1689653243)- 0]);
				res_75405_1689653243 += ((NI) 1);
			} LA3: ;
		}
	}
	(*gch0).decstack.len = ((NI) 0);
}

N_NIMCALL(void, collectctbody_75409_1689653243)(Gcheap50418* gch0) {
	NI LOC1;
	LOC1 = (NI)0;
	LOC1 = stacksize_71601_1689653243();
	(*gch0).stat.maxstacksize = (((*gch0).stat.maxstacksize >= LOC1) ? (*gch0).stat.maxstacksize : LOC1);
	prepareforinteriorpointerchecking_45288_1689653243((&(*gch0).region));
	markstackandregisters_73037_1689653243(gch0);
	(*gch0).stat.maxstackcells = (((*gch0).stat.maxstackcells >= (*gch0).decstack.len) ? (*gch0).stat.maxstackcells : (*gch0).decstack.len);
	(*gch0).stat.stackscans += ((NI) 1);
	{
		NIM_BOOL LOC4;
		LOC4 = (NIM_BOOL)0;
		LOC4 = collectzct_70007_1689653243(gch0);
		if (!LOC4) goto LA5;
		{
			NIM_BOOL LOC9;
			NI LOC10;
			NI LOC14;
			LOC9 = (NIM_BOOL)0;
			LOC10 = (NI)0;
			LOC10 = getoccupiedmem_47830_1689653243((&(*gch0).region));
			LOC9 = ((*gch0).cyclethreshold <= LOC10);
			if (LOC9) goto LA11;
			LOC9 = NIM_FALSE;
			LA11: ;
			if (!LOC9) goto LA12;
			collectcycles_70011_1689653243(gch0);
			(*gch0).stat.cyclecollections += ((NI) 1);
			LOC14 = (NI)0;
			LOC14 = getoccupiedmem_8055_1689653243();
			(*gch0).cyclethreshold = ((((NI) 4194304) >= (NI)(LOC14 * ((NI) 2))) ? ((NI) 4194304) : (NI)(LOC14 * ((NI) 2)));
			(*gch0).stat.maxthreshold = (((*gch0).stat.maxthreshold >= (*gch0).cyclethreshold) ? (*gch0).stat.maxthreshold : (*gch0).cyclethreshold);
		}
		LA12: ;
	}
	LA5: ;
	unmarkstackandregisters_75202_1689653243(gch0);
}

N_NIMCALL(void, collectct_52407_1689653243)(Gcheap50418* gch0) {
	NI stackmarkcosts0;
	NI LOC1;
	LOC1 = (NI)0;
	LOC1 = stacksize_71601_1689653243();
	stackmarkcosts0 = (((NI)(LOC1 / ((NI) 128)) >= ((NI) 500)) ? (NI)(LOC1 / ((NI) 128)) : ((NI) 500));
	{
		NIM_BOOL LOC4;
		NIM_BOOL LOC5;
		NIM_BOOL LOC6;
		NIM_BOOL LOC8;
		NI LOC10;
		LOC4 = (NIM_BOOL)0;
		LOC5 = (NIM_BOOL)0;
		LOC6 = (NIM_BOOL)0;
		LOC6 = (stackmarkcosts0 <= (*gch0).zct.len);
		if (LOC6) goto LA7;
		LOC8 = (NIM_BOOL)0;
		LOC8 = NIM_TRUE;
		if (!(LOC8)) goto LA9;
		LOC10 = (NI)0;
		LOC10 = getoccupiedmem_47830_1689653243((&(*gch0).region));
		LOC8 = ((*gch0).cyclethreshold <= LOC10);
		LA9: ;
		LOC6 = LOC8;
		LA7: ;
		LOC5 = LOC6;
		if (LOC5) goto LA11;
		LOC5 = NIM_FALSE;
		LA11: ;
		LOC4 = LOC5;
		if (!(LOC4)) goto LA12;
		LOC4 = ((*gch0).recgclock == ((NI) 0));
		LA12: ;
		if (!LOC4) goto LA13;
		collectctbody_75409_1689653243(gch0);
	}
	LA13: ;
}

static N_INLINE(void, addnewobjtozct_57474_1689653243)(Cell47905* res0, Gcheap50418* gch0) {
	NI L0;
	Cell47905** d0;
{	L0 = (*gch0).zct.len;
	d0 = (*gch0).zct.d;
	{
		Cell47905* c0;
		if (!(((NI) 8) < L0)) goto LA3;
		c0 = (Cell47905*)0;
		c0 = d0[((NI)(L0 - ((NI) 1)))- 0];
		{
			if (!((NU64)(((NI) 8)) <= (NU64)((*c0).refcount))) goto LA7;
			(*c0).refcount = (NI)((*c0).refcount & ((NI) -5));
			d0[((NI)(L0 - ((NI) 1)))- 0] = res0;
			goto BeforeRet;
		}
		LA7: ;
		c0 = d0[((NI)(L0 - ((NI) 2)))- 0];
		{
			if (!((NU64)(((NI) 8)) <= (NU64)((*c0).refcount))) goto LA11;
			(*c0).refcount = (NI)((*c0).refcount & ((NI) -5));
			d0[((NI)(L0 - ((NI) 2)))- 0] = res0;
			goto BeforeRet;
		}
		LA11: ;
		c0 = d0[((NI)(L0 - ((NI) 3)))- 0];
		{
			if (!((NU64)(((NI) 8)) <= (NU64)((*c0).refcount))) goto LA15;
			(*c0).refcount = (NI)((*c0).refcount & ((NI) -5));
			d0[((NI)(L0 - ((NI) 3)))- 0] = res0;
			goto BeforeRet;
		}
		LA15: ;
		c0 = d0[((NI)(L0 - ((NI) 4)))- 0];
		{
			if (!((NU64)(((NI) 8)) <= (NU64)((*c0).refcount))) goto LA19;
			(*c0).refcount = (NI)((*c0).refcount & ((NI) -5));
			d0[((NI)(L0 - ((NI) 4)))- 0] = res0;
			goto BeforeRet;
		}
		LA19: ;
		c0 = d0[((NI)(L0 - ((NI) 5)))- 0];
		{
			if (!((NU64)(((NI) 8)) <= (NU64)((*c0).refcount))) goto LA23;
			(*c0).refcount = (NI)((*c0).refcount & ((NI) -5));
			d0[((NI)(L0 - ((NI) 5)))- 0] = res0;
			goto BeforeRet;
		}
		LA23: ;
		c0 = d0[((NI)(L0 - ((NI) 6)))- 0];
		{
			if (!((NU64)(((NI) 8)) <= (NU64)((*c0).refcount))) goto LA27;
			(*c0).refcount = (NI)((*c0).refcount & ((NI) -5));
			d0[((NI)(L0 - ((NI) 6)))- 0] = res0;
			goto BeforeRet;
		}
		LA27: ;
		c0 = d0[((NI)(L0 - ((NI) 7)))- 0];
		{
			if (!((NU64)(((NI) 8)) <= (NU64)((*c0).refcount))) goto LA31;
			(*c0).refcount = (NI)((*c0).refcount & ((NI) -5));
			d0[((NI)(L0 - ((NI) 7)))- 0] = res0;
			goto BeforeRet;
		}
		LA31: ;
		c0 = d0[((NI)(L0 - ((NI) 8)))- 0];
		{
			if (!((NU64)(((NI) 8)) <= (NU64)((*c0).refcount))) goto LA35;
			(*c0).refcount = (NI)((*c0).refcount & ((NI) -5));
			d0[((NI)(L0 - ((NI) 8)))- 0] = res0;
			goto BeforeRet;
		}
		LA35: ;
		add_47992_1689653243((&(*gch0).zct), res0);
	}
	goto LA1;
	LA3: ;
	{
		d0[(L0)- 0] = res0;
		(*gch0).zct.len += ((NI) 1);
	}
	LA1: ;
	}BeforeRet: ;
}

N_NIMCALL(void*, rawnewobj_58001_1689653243)(TNimType* typ0, NI size0, Gcheap50418* gch0) {
	void* result0;
	Cell47905* res0;
	void* LOC1;
	result0 = (void*)0;
	collectct_52407_1689653243(gch0);
	LOC1 = (void*)0;
	LOC1 = rawalloc_37204_1689653243((&(*gch0).region), (NI)(size0 + ((NI)sizeof(Cell47905))));
	res0 = ((Cell47905*) (LOC1));
	(*res0).typ = typ0;
	(*res0).refcount = ((NI) 4);
	addnewobjtozct_57474_1689653243(res0, gch0);
	result0 = celltousr_52022_1689653243(res0);
	return result0;
}

N_NIMCALL(void*, newObjNoInit)(TNimType* typ0, NI size0) {
	void* result0;
	result0 = (void*)0;
	result0 = rawnewobj_58001_1689653243(typ0, size0, (&gch_50458_1689653243));
	return result0;
}

N_NIMCALL(NimStringDesc*, rawNewStringNoInit)(NI space0) {
	NimStringDesc* result0;
	NI s0;
	void* LOC5;
	result0 = (NimStringDesc*)0;
	s0 = space0;
	{
		if (!(s0 < ((NI) 7))) goto LA3;
		s0 = ((NI) 7);
	}
	LA3: ;
	LOC5 = (void*)0;
	LOC5 = newObjNoInit((&strdesc_12403_1689653243), (NI)((NI)(((NI)sizeof(TGenericSeq)) + s0) + ((NI) 1)));
	result0 = ((NimStringDesc*) (LOC5));
	(*result0).Sup.reserved = s0;
	return result0;
}

N_NIMCALL(NimStringDesc*, toNimStr)(NCSTRING str0, NI len0) {
	NimStringDesc* result0;
	result0 = (NimStringDesc*)0;
	result0 = rawNewStringNoInit(len0);
	(*result0).Sup.len = len0;
	memcpy(((NCSTRING) ((*result0).data)), str0, (NI)(len0 + ((NI) 1)));
	return result0;
}

N_NIMCALL(NimStringDesc*, cstrToNimstr)(NCSTRING str0) {
	NimStringDesc* result0;
	NI LOC1;
	result0 = (NimStringDesc*)0;
	LOC1 = (NI)0;
	LOC1 = strlen(str0);
	result0 = toNimStr(str0, LOC1);
	return result0;
}

N_NIMCALL(void, write_15701_1689653243)(FILE* f0, NCSTRING c0) {
	fputs(c0, f0);
}

N_NIMCALL(void, writetostderr_19601_1689653243)(NCSTRING msg0) {
	write_15701_1689653243(stderr, msg0);
}

N_NIMCALL(void, showerrormessage_19606_1689653243)(NCSTRING data0) {
	{
		NimStringDesc* LOC5;
		if (!!((errormessagewriter_19404_1689653243 == NIM_NIL))) goto LA3;
		LOC5 = (NimStringDesc*)0;
		LOC5 = cstrToNimstr(data0);
		errormessagewriter_19404_1689653243(LOC5);
	}
	goto LA1;
	LA3: ;
	{
		writetostderr_19601_1689653243(data0);
	}
	LA1: ;
}

N_NOCONV(void, signalHandler)(int sign0) {
	NCSTRING msg0;
	msg0 = (NCSTRING)0;
	{
		if (!(sign0 == SIGINT)) goto LA3;
		msg0 = "SIGINT: Interrupted by Ctrl-C.\012";
	}
	goto LA1;
	LA3: ;
	{
		if (!(sign0 == SIGSEGV)) goto LA6;
		msg0 = "SIGSEGV: Illegal storage access. (Attempt to read from nil?)\012";
	}
	goto LA1;
	LA6: ;
	{
		if (!(sign0 == SIGABRT)) goto LA9;
		msg0 = "SIGABRT: Abnormal termination.\012";
	}
	goto LA1;
	LA9: ;
	{
		if (!(sign0 == SIGFPE)) goto LA12;
		msg0 = "SIGFPE: Arithmetic error.\012";
	}
	goto LA1;
	LA12: ;
	{
		if (!(sign0 == SIGILL)) goto LA15;
		msg0 = "SIGILL: Illegal operation.\012";
	}
	goto LA1;
	LA15: ;
	{
		if (!(sign0 == SIGSEGV)) goto LA18;
		msg0 = "SIGBUS: Illegal storage access. (Attempt to read from nil?)\012";
	}
	goto LA1;
	LA18: ;
	{
		{
			{
				if (!(sign0 == SIGPIPE)) goto LA24;
				msg0 = "SIGPIPE: Pipe closed.\012";
				goto LA21;
			}
			LA24: ;
			msg0 = "unknown signal\012";
		} LA21: ;
	}
	LA1: ;
	showerrormessage_19606_1689653243(msg0);
	exit(((NI) 1));
}

N_NIMCALL(void, registersignalhandler_23202_1689653243)(void) {
	signal(SIGINT, signalHandler);
	signal(SIGSEGV, signalHandler);
	signal(SIGABRT, signalHandler);
	signal(SIGFPE, signalHandler);
	signal(SIGILL, signalHandler);
	signal(SIGSEGV, signalHandler);
	signal(SIGPIPE, signalHandler);
}

N_NIMCALL(NI, getRefcount)(void* p0) {
	NI result0;
	Cell47905* LOC1;
	result0 = (NI)0;
	LOC1 = (Cell47905*)0;
	LOC1 = usrtocell_52040_1689653243(p0);
	result0 = (NI)((NU64)((*LOC1).refcount) >> (NU64)(((NI) 3)));
	return result0;
}

N_NIMCALL(void*, newObj)(TNimType* typ0, NI size0) {
	void* result0;
	result0 = (void*)0;
	result0 = rawnewobj_58001_1689653243(typ0, size0, (&gch_50458_1689653243));
	zeroMem(result0, ((NI) (size0)));
	return result0;
}

N_NIMCALL(NimStringDesc*, rawNewString)(NI space0) {
	NimStringDesc* result0;
	NI s0;
	void* LOC5;
	result0 = (NimStringDesc*)0;
	s0 = space0;
	{
		if (!(s0 < ((NI) 7))) goto LA3;
		s0 = ((NI) 7);
	}
	LA3: ;
	LOC5 = (void*)0;
	LOC5 = newObj((&strdesc_12403_1689653243), (NI)((NI)(((NI)sizeof(TGenericSeq)) + s0) + ((NI) 1)));
	result0 = ((NimStringDesc*) (LOC5));
	(*result0).Sup.reserved = s0;
	return result0;
}

N_NIMCALL(NimStringDesc*, mnewString)(NI len0) {
	NimStringDesc* result0;
	result0 = (NimStringDesc*)0;
	result0 = rawNewString(len0);
	(*result0).Sup.len = len0;
	return result0;
}

static N_INLINE(NI, resize_79001_1689653243)(NI old0) {
	NI result0;
	result0 = (NI)0;
	{
		if (!(old0 <= ((NI) 0))) goto LA3;
		result0 = ((NI) 4);
	}
	goto LA1;
	LA3: ;
	{
		if (!(old0 < ((NI) 65536))) goto LA6;
		result0 = (NI)(old0 * ((NI) 2));
	}
	goto LA1;
	LA6: ;
	{
		result0 = (NI)((NI)(old0 * ((NI) 3)) / ((NI) 2));
	}
	LA1: ;
	return result0;
}

N_NIMCALL(void*, growobj_63803_1689653243)(void* old0, NI newsize0, Gcheap50418* gch0) {
	void* result0;
	Cell47905* ol0;
	Cell47905* res0;
	void* LOC1;
	NI elemsize0;
	NI oldsize0;
	result0 = (void*)0;
	collectct_52407_1689653243(gch0);
	ol0 = usrtocell_52040_1689653243(old0);
	LOC1 = (void*)0;
	LOC1 = rawalloc_37204_1689653243((&(*gch0).region), (NI)(newsize0 + ((NI)sizeof(Cell47905))));
	res0 = ((Cell47905*) (LOC1));
	elemsize0 = ((NI) 1);
	{
		if (!!(((*(*ol0).typ).kind == ((Tnimkind3203) 28)))) goto LA4;
		elemsize0 = (*(*(*ol0).typ).base).size;
	}
	LA4: ;
	oldsize0 = (NI)((NI)((*((TGenericSeq*) (old0))).len * elemsize0) + ((NI) 16));
	memcpy(((void*) (res0)), ((void*) (ol0)), ((NI) ((NI)(oldsize0 + ((NI)sizeof(Cell47905))))));
	zeroMem(((void*) ((NI)((NU64)((NI)((NU64)(((NI) (res0))) + (NU64)(oldsize0))) + (NU64)(((NI)sizeof(Cell47905)))))), ((NI) ((NI)(newsize0 - oldsize0))));
	{
		if (!((NU64)((NI)((NU64)((*ol0).refcount) >> (NU64)(((NI) 3)))) <= (NU64)(((NI) 1)))) goto LA8;
		{
			NI j0;
			Cell47905** d0;
			if (!!(((NI)((*ol0).refcount & ((NI) 4)) == ((NI) 0)))) goto LA12;
			j0 = (NI)((*gch0).zct.len - ((NI) 1));
			d0 = (*gch0).zct.d;
			{
				while (1) {
					if (!(((NI) 0) <= j0)) goto LA15;
					{
						if (!(d0[(j0)- 0] == ol0)) goto LA18;
						d0[(j0)- 0] = res0;
						goto LA14;
					}
					LA18: ;
					j0 -= ((NI) 1);
				} LA15: ;
			} LA14: ;
		}
		LA12: ;
		rawdealloc_43617_1689653243((&(*gch0).region), ((void*) (ol0)));
	}
	goto LA6;
	LA8: ;
	{
		(*res0).refcount = ((NI) 8);
		decref_53601_1689653243(ol0);
	}
	LA6: ;
	result0 = celltousr_52022_1689653243(res0);
	return result0;
}

N_NIMCALL(void*, growobj_66809_1689653243)(void* old0, NI newsize0) {
	void* result0;
	result0 = (void*)0;
	result0 = growobj_63803_1689653243(old0, newsize0, (&gch_50458_1689653243));
	return result0;
}

N_NIMCALL(NimStringDesc*, resizeString)(NimStringDesc* dest0, NI addlen0) {
	NimStringDesc* result0;
	result0 = (NimStringDesc*)0;
	{
		if (!((NI)((*dest0).Sup.len + addlen0) <= (NI)((*dest0).Sup.reserved & ((NI) IL64(9223372036854775807))))) goto LA3;
		result0 = dest0;
	}
	goto LA1;
	LA3: ;
	{
		NI sp0;
		NI LOC6;
		void* LOC7;
		LOC6 = (NI)0;
		LOC6 = resize_79001_1689653243((NI)((*dest0).Sup.reserved & ((NI) IL64(9223372036854775807))));
		sp0 = ((LOC6 >= (NI)((*dest0).Sup.len + addlen0)) ? LOC6 : (NI)((*dest0).Sup.len + addlen0));
		LOC7 = (void*)0;
		LOC7 = growobj_66809_1689653243(((void*) (dest0)), (NI)((NI)(((NI)sizeof(TGenericSeq)) + sp0) + ((NI) 1)));
		result0 = ((NimStringDesc*) (LOC7));
		(*result0).Sup.reserved = sp0;
	}
	LA1: ;
	return result0;
}

N_NIMCALL(NimStringDesc*, setLengthStr)(NimStringDesc* s0, NI newlen0) {
	NimStringDesc* result0;
	NI n0;
	result0 = (NimStringDesc*)0;
	n0 = ((newlen0 >= ((NI) 0)) ? newlen0 : ((NI) 0));
	{
		if (!(n0 <= (NI)((*s0).Sup.reserved & ((NI) IL64(9223372036854775807))))) goto LA3;
		result0 = s0;
	}
	goto LA1;
	LA3: ;
	{
		result0 = resizeString(s0, n0);
	}
	LA1: ;
	(*result0).Sup.len = n0;
	(*result0).data[(n0)- 0] = 0;
	return result0;
}

N_NIMCALL(NimStringDesc*, nimIntToStr)(NI x0) {
	NimStringDesc* result0;
	NI i0;
	NI y0;
	result0 = (NimStringDesc*)0;
	result0 = mnewString(((NI) 32));
	i0 = ((NI) 0);
	y0 = x0;
	{
		while (1) {
			NI d0;
			d0 = (NI)(y0 / ((NI) 10));
			result0->data[i0] = ((NIM_CHAR) (((NI) ((NI)(((NI)(y0 - (NI)(d0 * ((NI) 10))) > 0? ((NI)(y0 - (NI)(d0 * ((NI) 10)))) : -((NI)(y0 - (NI)(d0 * ((NI) 10))))) + ((NI) 48))))));
			i0 += ((NI) 1);
			y0 = d0;
			{
				if (!(y0 == ((NI) 0))) goto LA5;
				goto LA1;
			}
			LA5: ;
		}
	} LA1: ;
	{
		if (!(x0 < ((NI) 0))) goto LA9;
		result0->data[i0] = 45;
		i0 += ((NI) 1);
	}
	LA9: ;
	result0 = setLengthStr(result0, ((NI) (i0)));
	{
		NI j_80339_1689653243;
		NI HEX3Atmp_80353_1689653243;
		NI res_80356_1689653243;
		j_80339_1689653243 = (NI)0;
		HEX3Atmp_80353_1689653243 = (NI)0;
		HEX3Atmp_80353_1689653243 = (NI)((NI)(i0 / ((NI) 2)) - ((NI) 1));
		res_80356_1689653243 = ((NI) 0);
		{
			while (1) {
				NIM_CHAR LOC14;
				if (!(res_80356_1689653243 <= HEX3Atmp_80353_1689653243)) goto LA13;
				j_80339_1689653243 = res_80356_1689653243;
				LOC14 = (NIM_CHAR)0;
				LOC14 = result0->data[j_80339_1689653243];
				result0->data[j_80339_1689653243] = result0->data[(NI)((NI)(i0 - j_80339_1689653243) - ((NI) 1))];
				result0->data[(NI)((NI)(i0 - j_80339_1689653243) - ((NI) 1))] = LOC14;
				res_80356_1689653243 += ((NI) 1);
			} LA13: ;
		}
	}
	return result0;
}
NIM_EXTERNC N_NOINLINE(void, systemInit000)(void) {
	TNimType LOC1;
	nimvm_5554_1689653243 = NIM_FALSE;
	memset((void*)(&LOC1), 0, sizeof(LOC1));
	LOC1.size = ((NI) 8);
	LOC1.kind = ((Tnimkind3203) 28);
	LOC1.flags = 2;
	strdesc_12403_1689653243 = LOC1;
	initallocator_11801_1689653243();
	initStackBottom();
	initgc_11601_1689653243();
nimRegisterGlobalMarker(TMP5);
	registersignalhandler_23202_1689653243();
}

NIM_EXTERNC N_NOINLINE(void, systemDatInit000)(void) {
static TNimNode* TMP3[4];
static TNimNode TMP0[6];
NTI3408.size = sizeof(TNimObject);
NTI3408.kind = 17;
NTI3408.base = 0;
NTI3408.flags = 1;
TMP0[0].len = 0; TMP0[0].kind = 2;
NTI3408.node = &TMP0[0];
NTI3424.size = sizeof(Exception);
NTI3424.kind = 17;
NTI3424.base = (&NTI3408);
TMP3[0] = &TMP0[2];
TMP0[2].kind = 1;
TMP0[2].offset = offsetof(Exception, parent);
TMP0[2].typ = (&NTI10010);
TMP0[2].name = "parent";
TMP3[1] = &TMP0[3];
NTI140.size = sizeof(NCSTRING);
NTI140.kind = 29;
NTI140.base = 0;
NTI140.flags = 3;
TMP0[3].kind = 1;
TMP0[3].offset = offsetof(Exception, name);
TMP0[3].typ = (&NTI140);
TMP0[3].name = "name";
TMP3[2] = &TMP0[4];
NTI138.size = sizeof(NimStringDesc*);
NTI138.kind = 28;
NTI138.base = 0;
NTI138.flags = 2;
TMP0[4].kind = 1;
TMP0[4].offset = offsetof(Exception, message);
TMP0[4].typ = (&NTI138);
TMP0[4].name = "msg";
TMP3[3] = &TMP0[5];
TMP0[5].kind = 1;
TMP0[5].offset = offsetof(Exception, trace);
TMP0[5].typ = (&NTI138);
TMP0[5].name = "trace";
TMP0[1].len = 4; TMP0[1].kind = 2; TMP0[1].sons = &TMP3[0];
NTI3424.node = &TMP0[1];
NTI10010.size = sizeof(Exception*);
NTI10010.kind = 22;
NTI10010.base = (&NTI3424);
NTI10010.marker = TMP4;
}

