/* Generated by Nim Compiler v0.14.2 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/home/primat/programs/nim-0.14.2/lib -o /home/primat/projects/tests/nim/game_1/nimcache/sdl2_image.o /home/primat/projects/tests/nim/game_1/nimcache/sdl2_image.c */
#define NIM_INTBITS 64

#include "nimbase.h"
typedef struct TGenericSeq TGenericSeq;
typedef struct NimStringDesc NimStringDesc;
typedef struct Sdlversion116582 Sdlversion116582;
typedef struct Surface117252 Surface117252;
typedef struct Rwops125831 Rwops125831;
typedef struct TextureptrHEX3Aobjecttype116609 TextureptrHEX3Aobjecttype116609;
typedef struct RendererptrHEX3Aobjecttype116607 RendererptrHEX3Aobjecttype116607;
typedef struct Pixelformat117246 Pixelformat117246;
typedef struct Rect116265 Rect116265;
typedef struct BlitmapptrHEX3Aobjecttype117294 BlitmapptrHEX3Aobjecttype117294;
typedef struct Mem125833 Mem125833;
typedef struct Palette117244 Palette117244;
typedef struct Color117242 Color117242;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef N_CDECL_PTR(Sdlversion116582*, TY128602) (void);
typedef N_CDECL_PTR(int, TY128605) (int flags0);
typedef N_CDECL_PTR(void, TY128608) (void);
typedef N_CDECL_PTR(Surface117252*, TY128610) (Rwops125831* src0, int freesrc0, NCSTRING type_128613_2539608100);
typedef N_CDECL_PTR(Surface117252*, TY128615) (NCSTRING file0);
typedef N_CDECL_PTR(Surface117252*, TY128618) (Rwops125831* src0, int freesrc0);
typedef N_CDECL_PTR(TextureptrHEX3Aobjecttype116609*, TY128622) (RendererptrHEX3Aobjecttype116607* renderer0, NCSTRING file0);
typedef N_CDECL_PTR(TextureptrHEX3Aobjecttype116609*, TY128626) (RendererptrHEX3Aobjecttype116607* renderer0, Rwops125831* src0, int freesrc0);
typedef N_CDECL_PTR(TextureptrHEX3Aobjecttype116609*, TY128631) (RendererptrHEX3Aobjecttype116607* renderer0, Rwops125831* src0, int freesrc0, NCSTRING type_128635_2539608100);
typedef N_CDECL_PTR(int, TY128637) (Rwops125831* src0);
typedef N_CDECL_PTR(int, TY128640) (Rwops125831* src0);
typedef N_CDECL_PTR(int, TY128643) (Rwops125831* src0);
typedef N_CDECL_PTR(int, TY128646) (Rwops125831* src0);
typedef N_CDECL_PTR(int, TY128649) (Rwops125831* src0);
typedef N_CDECL_PTR(int, TY128652) (Rwops125831* src0);
typedef N_CDECL_PTR(int, TY128655) (Rwops125831* src0);
typedef N_CDECL_PTR(int, TY128658) (Rwops125831* src0);
typedef N_CDECL_PTR(int, TY128661) (Rwops125831* src0);
typedef N_CDECL_PTR(int, TY128664) (Rwops125831* src0);
typedef N_CDECL_PTR(int, TY128667) (Rwops125831* src0);
typedef N_CDECL_PTR(int, TY128670) (Rwops125831* src0);
typedef N_CDECL_PTR(int, TY128673) (Rwops125831* src0);
typedef N_CDECL_PTR(int, TY128676) (Rwops125831* src0);
typedef N_CDECL_PTR(Surface117252*, TY128679) (Rwops125831* src0);
typedef N_CDECL_PTR(Surface117252*, TY128682) (Rwops125831* src0);
typedef N_CDECL_PTR(Surface117252*, TY128685) (Rwops125831* src0);
typedef N_CDECL_PTR(Surface117252*, TY128688) (Rwops125831* src0);
typedef N_CDECL_PTR(Surface117252*, TY128691) (Rwops125831* src0);
typedef N_CDECL_PTR(Surface117252*, TY128694) (Rwops125831* src0);
typedef N_CDECL_PTR(Surface117252*, TY128697) (Rwops125831* src0);
typedef N_CDECL_PTR(Surface117252*, TY128700) (Rwops125831* src0);
typedef N_CDECL_PTR(Surface117252*, TY128703) (Rwops125831* src0);
typedef N_CDECL_PTR(Surface117252*, TY128706) (Rwops125831* src0);
typedef N_CDECL_PTR(Surface117252*, TY128709) (Rwops125831* src0);
typedef N_CDECL_PTR(Surface117252*, TY128712) (Rwops125831* src0);
typedef N_CDECL_PTR(Surface117252*, TY128715) (Rwops125831* src0);
typedef N_CDECL_PTR(Surface117252*, TY128718) (Rwops125831* src0);
typedef N_CDECL_PTR(Surface117252*, TY128721) (Rwops125831* src0);
typedef N_CDECL_PTR(Surface117252*, TY128724) (NCSTRING* xpm0);
struct  Sdlversion116582  {
NU8 major;
NU8 minor;
NU8 patch;
};
struct Rect116265 {
int Field0;
int Field1;
int Field2;
int Field3;
};
struct  Surface117252  {
NU32 flags;
Pixelformat117246* format;
NI32 w;
NI32 h;
NI32 pitch;
void* pixels;
void* userdata;
NI32 locked;
void* lockdata;
Rect116265 cliprect;
BlitmapptrHEX3Aobjecttype117294* map;
int refcount;
};
typedef N_CDECL_PTR(NI64, TY125859) (Rwops125831* context0);
typedef N_CDECL_PTR(NI64, TY125863) (Rwops125831* context0, NI64 offset0, int whence0);
typedef N_CDECL_PTR(size_t, TY125869) (Rwops125831* context0, void* destination0, size_t size0, size_t maxnum0);
typedef N_CDECL_PTR(size_t, TY125876) (Rwops125831* context0, void* source0, size_t size0, size_t num0);
typedef N_CDECL_PTR(int, TY125883) (Rwops125831* context0);
struct  Mem125833  {
NU8* base;
NU8* here;
NU8* stop;
};
struct  Rwops125831  {
TY125859 size;
TY125863 seek;
TY125869 read;
TY125876 write;
TY125883 close;
int kind;
Mem125833 mem;
};
struct  TextureptrHEX3Aobjecttype116609  {
char dummy;
};
struct  RendererptrHEX3Aobjecttype116607  {
char dummy;
};
typedef NU8 TY117277[2];
struct  Pixelformat117246  {
NU32 format;
Palette117244* palette;
NU8 Bitsperpixel;
NU8 Bytesperpixel;
TY117277 padding;
NU32 Rmask;
NU32 Gmask;
NU32 Bmask;
NU32 Amask;
NU8 Rloss;
NU8 Gloss;
NU8 Bloss;
NU8 Aloss;
NU8 Rshift;
NU8 Gshift;
NU8 Bshift;
NU8 Ashift;
int refcount;
Pixelformat117246* next;
};
struct  BlitmapptrHEX3Aobjecttype117294  {
char dummy;
};
struct  Palette117244  {
int ncolors;
Color117242* colors;
NU32 version;
int refcount;
};
struct Color117242 {
NU8 Field0;
NU8 Field1;
NU8 Field2;
NU8 Field3;
};
N_NIMCALL(void*, nimLoadLibrary)(NimStringDesc* path0);
N_NOINLINE(void, nimLoadLibraryError)(NimStringDesc* path0);
N_NIMCALL(void*, nimGetProcAddr)(void* lib0, NCSTRING name0);
static N_INLINE(void, nimFrame)(TFrame* s0);
N_NOINLINE(void, stackoverflow_22401_1689653243)(void);
static N_INLINE(void, popFrame)(void);
STRING_LITERAL(TMP177, "libSDL2_image.so", 16);
STRING_LITERAL(TMP178, "libSDL2_image.so.0", 18);
STRING_LITERAL(TMP179, "libSDL2_image-2.0.so", 20);
STRING_LITERAL(TMP180, "libSDL2_image-2.0.so.0", 22);
STRING_LITERAL(TMP181, "libSDL2_image(|-2.0).so(|.0)", 28);
static void* TMP176;
TY128602 Dl_128601;
TY128605 Dl_128604;
TY128608 Dl_128607;
TY128610 Dl_128609;
TY128615 Dl_128614;
TY128618 Dl_128617;
TY128622 Dl_128621;
TY128626 Dl_128625;
TY128631 Dl_128630;
TY128637 Dl_128636;
TY128640 Dl_128639;
TY128643 Dl_128642;
TY128646 Dl_128645;
TY128649 Dl_128648;
TY128652 Dl_128651;
TY128655 Dl_128654;
TY128658 Dl_128657;
TY128661 Dl_128660;
TY128664 Dl_128663;
TY128667 Dl_128666;
TY128670 Dl_128669;
TY128673 Dl_128672;
TY128676 Dl_128675;
TY128679 Dl_128678;
TY128682 Dl_128681;
TY128685 Dl_128684;
TY128688 Dl_128687;
TY128691 Dl_128690;
TY128694 Dl_128693;
TY128697 Dl_128696;
TY128700 Dl_128699;
TY128703 Dl_128702;
TY128706 Dl_128705;
TY128709 Dl_128708;
TY128712 Dl_128711;
TY128715 Dl_128714;
TY128718 Dl_128717;
TY128721 Dl_128720;
TY128724 Dl_128723;
extern TFrame* frameptr_19636_1689653243;

static N_INLINE(void, nimFrame)(TFrame* s0) {
	NI LOC1;
	LOC1 = (NI)0;
	{
		if (!(frameptr_19636_1689653243 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_19636_1689653243).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s0).calldepth = ((NI16) (LOC1));
	(*s0).prev = frameptr_19636_1689653243;
	frameptr_19636_1689653243 = s0;
	{
		if (!((*s0).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_22401_1689653243();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_19636_1689653243 = (*frameptr_19636_1689653243).prev;
}
NIM_EXTERNC N_NOINLINE(void, sdl2_imageInit000)(void) {
	nimfr("image", "image.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, sdl2_imageDatInit000)(void) {
if (!((TMP176 = nimLoadLibrary((NimStringDesc*) &TMP177))
||(TMP176 = nimLoadLibrary((NimStringDesc*) &TMP178))
||(TMP176 = nimLoadLibrary((NimStringDesc*) &TMP179))
||(TMP176 = nimLoadLibrary((NimStringDesc*) &TMP180))
)) nimLoadLibraryError((NimStringDesc*) &TMP181);
	Dl_128601 = (TY128602) nimGetProcAddr(TMP176, "IMG_Linked_Version");
	Dl_128604 = (TY128605) nimGetProcAddr(TMP176, "IMG_Init");
	Dl_128607 = (TY128608) nimGetProcAddr(TMP176, "IMG_Quit");
	Dl_128609 = (TY128610) nimGetProcAddr(TMP176, "IMG_LoadTyped_RW");
	Dl_128614 = (TY128615) nimGetProcAddr(TMP176, "IMG_Load");
	Dl_128617 = (TY128618) nimGetProcAddr(TMP176, "IMG_Load_RW");
	Dl_128621 = (TY128622) nimGetProcAddr(TMP176, "IMG_LoadTexture");
	Dl_128625 = (TY128626) nimGetProcAddr(TMP176, "IMG_LoadTexture_RW");
	Dl_128630 = (TY128631) nimGetProcAddr(TMP176, "IMG_LoadTextureTyped_RW");
	Dl_128636 = (TY128637) nimGetProcAddr(TMP176, "IMG_isICO");
	Dl_128639 = (TY128640) nimGetProcAddr(TMP176, "IMG_isCUR");
	Dl_128642 = (TY128643) nimGetProcAddr(TMP176, "IMG_isBMP");
	Dl_128645 = (TY128646) nimGetProcAddr(TMP176, "IMG_isGIF");
	Dl_128648 = (TY128649) nimGetProcAddr(TMP176, "IMG_isJPG");
	Dl_128651 = (TY128652) nimGetProcAddr(TMP176, "IMG_isLBM");
	Dl_128654 = (TY128655) nimGetProcAddr(TMP176, "IMG_isPCX");
	Dl_128657 = (TY128658) nimGetProcAddr(TMP176, "IMG_isPNG");
	Dl_128660 = (TY128661) nimGetProcAddr(TMP176, "IMG_isPNM");
	Dl_128663 = (TY128664) nimGetProcAddr(TMP176, "IMG_isTIF");
	Dl_128666 = (TY128667) nimGetProcAddr(TMP176, "IMG_isXCF");
	Dl_128669 = (TY128670) nimGetProcAddr(TMP176, "IMG_isXPM");
	Dl_128672 = (TY128673) nimGetProcAddr(TMP176, "IMG_isXV");
	Dl_128675 = (TY128676) nimGetProcAddr(TMP176, "IMG_isWEBP");
	Dl_128678 = (TY128679) nimGetProcAddr(TMP176, "IMG_LoadICO_RW");
	Dl_128681 = (TY128682) nimGetProcAddr(TMP176, "IMG_LoadCUR_RW");
	Dl_128684 = (TY128685) nimGetProcAddr(TMP176, "IMG_LoadBMP_RW");
	Dl_128687 = (TY128688) nimGetProcAddr(TMP176, "IMG_LoadGIF_RW");
	Dl_128690 = (TY128691) nimGetProcAddr(TMP176, "IMG_LoadJPG_RW");
	Dl_128693 = (TY128694) nimGetProcAddr(TMP176, "IMG_LoadLBM_RW");
	Dl_128696 = (TY128697) nimGetProcAddr(TMP176, "IMG_LoadPCX_RW");
	Dl_128699 = (TY128700) nimGetProcAddr(TMP176, "IMG_LoadPNG_RW");
	Dl_128702 = (TY128703) nimGetProcAddr(TMP176, "IMG_LoadPNM_RW");
	Dl_128705 = (TY128706) nimGetProcAddr(TMP176, "IMG_LoadTGA_RW");
	Dl_128708 = (TY128709) nimGetProcAddr(TMP176, "IMG_LoadTIF_RW");
	Dl_128711 = (TY128712) nimGetProcAddr(TMP176, "IMG_LoadXCF_RW");
	Dl_128714 = (TY128715) nimGetProcAddr(TMP176, "IMG_LoadXPM_RW");
	Dl_128717 = (TY128718) nimGetProcAddr(TMP176, "IMG_LoadXV_RW");
	Dl_128720 = (TY128721) nimGetProcAddr(TMP176, "IMG_LoadWEBP_RW");
	Dl_128723 = (TY128724) nimGetProcAddr(TMP176, "IMG_ReadXPMFromArray");
}

