/* Generated by Nim Compiler v0.14.2 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/home/primat/programs/nim-0.14.2/lib -o /home/primat/projects/tests/nim/game_1/nimcache/sdl2_sdl2.o /home/primat/projects/tests/nim/game_1/nimcache/sdl2_sdl2.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
typedef struct Event116155 Event116155;
typedef struct TextureptrHEX3Aobjecttype116609 TextureptrHEX3Aobjecttype116609;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct RendererptrHEX3Aobjecttype116607 RendererptrHEX3Aobjecttype116607;
typedef struct TGenericSeq TGenericSeq;
typedef struct NimStringDesc NimStringDesc;
typedef struct Keyboardeventobj116167 Keyboardeventobj116167;
typedef struct Rect116265 Rect116265;
typedef struct Point116263 Point116263;
typedef struct WindowptrHEX3Aobjecttype116605 WindowptrHEX3Aobjecttype116605;
typedef struct Keysym116261 Keysym116261;
typedef NI32 Eventtype116152;
typedef NU8 TY116342[52];
struct  Event116155  {
Eventtype116152 kind;
TY116342 padding;
};
struct  TextureptrHEX3Aobjecttype116609  {
char dummy;
};
typedef NU8 Tnimkind3203;
typedef NU8 Tnimtypeflag3209Set;
typedef N_NIMCALL_PTR(void, TY3289) (void* p0, NI op0);
typedef N_NIMCALL_PTR(void*, TY3294) (void* p0);
struct  TNimType  {
NI size;
Tnimkind3203 kind;
Tnimtypeflag3209Set flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3289 marker;
TY3294 deepcopy;
};
struct  RendererptrHEX3Aobjecttype116607  {
char dummy;
};
typedef NI32 Bool32116255;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef N_CDECL_PTR(Bool32116255, TY126963) (Event116155* event0);
struct Rect116265 {
int Field0;
int Field1;
int Field2;
int Field3;
};
typedef NI32 Sdlreturn116252;
typedef N_CDECL_PTR(Sdlreturn116252, TY126385) (RendererptrHEX3Aobjecttype116607* renderer0, TextureptrHEX3Aobjecttype116609* texture0, Rect116265* srcrect0, Rect116265* dstrect0, double angle0, Point116263* center0, int flip0);
typedef N_CDECL_PTR(int, TY126407) (RendererptrHEX3Aobjecttype116607* renderer0);
typedef N_CDECL_PTR(void, TY126418) (RendererptrHEX3Aobjecttype116607* renderer0);
typedef N_CDECL_PTR(Sdlreturn116252, TY126166) (int flags0);
typedef N_CDECL_PTR(NCSTRING, TY127012) (void);
typedef N_CDECL_PTR(NIM_BOOL, TY127412) (NCSTRING name0, NCSTRING value0);
typedef N_CDECL_PTR(WindowptrHEX3Aobjecttype116605*, TY126731) (NCSTRING title0, int x0, int y0, int w0, int h0, NU32 flags0);
typedef N_CDECL_PTR(RendererptrHEX3Aobjecttype116607*, TY126206) (WindowptrHEX3Aobjecttype116605* window0, int index0, int flags0);
typedef N_CDECL_PTR(Sdlreturn116252, TY126018) (RendererptrHEX3Aobjecttype116607* renderer0, NU8 r0, NU8 g0, NU8 b0, NU8 a0);
typedef N_CDECL_PTR(void, TY126049) (RendererptrHEX3Aobjecttype116607* renderer0);
typedef N_CDECL_PTR(void, TY126763) (WindowptrHEX3Aobjecttype116605* window0);
typedef N_CDECL_PTR(void, TY126178) (void);
typedef NU8 Tnimnodekind3205;
struct  TNimNode  {
Tnimnodekind3205 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef NI32 Scancode115402;
struct  Keysym116261  {
Scancode115402 scancode;
int sym;
NI16 modstate;
int unicode;
};
struct  Keyboardeventobj116167  {
Eventtype116152 kind;
NU32 timestamp;
NU32 windowid;
NU8 state;
NIM_BOOL repeat;
NU8 pad1;
NU8 pad2;
Keysym116261 keysym;
};
struct Point116263 {
int Field0;
int Field1;
};
struct  WindowptrHEX3Aobjecttype116605  {
char dummy;
};
static N_INLINE(void, nimFrame)(TFrame* s0);
N_NOINLINE(void, stackoverflow_22401_1689653243)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(void*, nimLoadLibrary)(NimStringDesc* path0);
N_NOINLINE(void, nimLoadLibraryError)(NimStringDesc* path0);
N_NIMCALL(void*, nimGetProcAddr)(void* lib0, NCSTRING name0);
N_NIMCALL(void, failedassertimpl_91239_1689653243)(NimStringDesc* msg0);
STRING_LITERAL(TMP197, "libSDL2.so", 10);
STRING_LITERAL(TMP198, "libSDL2.so", 10);
STRING_LITERAL(TMP199, "contains({KeyDown, KeyUp}, event.kind) ", 39);
Event116155 defaultevent_127601_2197055214;
TNimType NTI116609; /* TexturePtr:ObjectType */
TNimType NTI116576; /* TexturePtr */
TNimType NTI116607; /* RendererPtr:ObjectType */
TNimType NTI116574; /* RendererPtr */
extern TFrame* frameptr_19636_1689653243;
static void* TMP196;
TY126963 Dl_126962;
TY126385 Dl_126384;
TY126407 Dl_126406;
TY126418 Dl_126417;
TY126166 Dl_126165;
TY127012 Dl_127011;
TY127412 Dl_127411;
TY126731 Dl_126730;
TY126206 Dl_126205;
TY126018 Dl_126017;
TY126049 Dl_126048;
TY126763 Dl_126762;
TY126178 Dl_126177;

static N_INLINE(void, nimFrame)(TFrame* s0) {
	NI LOC1;
	LOC1 = (NI)0;
	{
		if (!(frameptr_19636_1689653243 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_19636_1689653243).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s0).calldepth = ((NI16) (LOC1));
	(*s0).prev = frameptr_19636_1689653243;
	frameptr_19636_1689653243 = s0;
	{
		if (!((*s0).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_22401_1689653243();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_19636_1689653243 = (*frameptr_19636_1689653243).prev;
}

N_NIMCALL(NIM_BOOL, tobool_116697_2197055214)(Bool32116255 some0) {
	NIM_BOOL result0;
	nimfr("toBool", "sdl2.nim")
	result0 = (NIM_BOOL)0;
	nimln(325, "sdl2.nim");
	result0 = ((NIM_BOOL) (some0));
	popFrame();
	return result0;
}

N_NIMCALL(Keyboardeventobj116167*, key_118003_2197055214)(Event116155* event_117806_2197055214) {
	Keyboardeventobj116167* result0;
	nimfr("key", "sdl2.nim")
{	result0 = (Keyboardeventobj116167*)0;
	nimln(612, "sdl2.nim");
	{
		if (!!(((*event_117806_2197055214).kind == ((Eventtype116152) 768) || (*event_117806_2197055214).kind == ((Eventtype116152) 769)))) goto LA3;
		failedassertimpl_91239_1689653243(((NimStringDesc*) &TMP199));
	}
	LA3: ;
	nimln(613, "sdl2.nim");
	result0 = ((Keyboardeventobj116167*) (event_117806_2197055214));
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result0;
}

N_CDECL(Rect116265, rect_127392_2197055214)(int x0, int y0, int w0, int h0) {
	Rect116265 result0;
	nimfr("rect", "sdl2.nim")
	memset((void*)(&result0), 0, sizeof(result0));
	nimln(1736, "sdl2.nim");
	result0.Field0 = x0;
	nimln(1737, "sdl2.nim");
	result0.Field1 = y0;
	nimln(1738, "sdl2.nim");
	result0.Field2 = w0;
	nimln(1739, "sdl2.nim");
	result0.Field3 = h0;
	popFrame();
	return result0;
}

N_NIMCALL(NIM_BOOL, tobool_116702_2197055214)(Sdlreturn116252 some0) {
	NIM_BOOL result0;
	nimfr("toBool", "sdl2.nim")
	result0 = (NIM_BOOL)0;
	nimln(326, "sdl2.nim");
	result0 = (some0 == ((Sdlreturn116252) 0));
	popFrame();
	return result0;
}
NIM_EXTERNC N_NOINLINE(void, sdl2_sdl2Init000)(void) {
	Event116155 LOC1;
	nimfr("sdl2", "sdl2.nim")
	nimln(1770, "sdl2.nim");
	memset((void*)(&LOC1), 0, sizeof(LOC1));
	LOC1.kind = ((Eventtype116152) 256);
	defaultevent_127601_2197055214 = LOC1;
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, sdl2_sdl2DatInit000)(void) {
static TNimNode TMP141[2];
NTI116609.size = sizeof(TextureptrHEX3Aobjecttype116609);
NTI116609.kind = 18;
NTI116609.base = 0;
NTI116609.flags = 3;
TMP141[0].len = 0; TMP141[0].kind = 2;
NTI116609.node = &TMP141[0];
NTI116576.size = sizeof(TextureptrHEX3Aobjecttype116609*);
NTI116576.kind = 21;
NTI116576.base = (&NTI116609);
NTI116576.flags = 3;
NTI116607.size = sizeof(RendererptrHEX3Aobjecttype116607);
NTI116607.kind = 18;
NTI116607.base = 0;
NTI116607.flags = 3;
TMP141[1].len = 0; TMP141[1].kind = 2;
NTI116607.node = &TMP141[1];
NTI116574.size = sizeof(RendererptrHEX3Aobjecttype116607*);
NTI116574.kind = 21;
NTI116574.base = (&NTI116607);
NTI116574.flags = 3;
if (!((TMP196 = nimLoadLibrary((NimStringDesc*) &TMP197))
)) nimLoadLibraryError((NimStringDesc*) &TMP198);
	Dl_126962 = (TY126963) nimGetProcAddr(TMP196, "SDL_PollEvent");
	Dl_126384 = (TY126385) nimGetProcAddr(TMP196, "SDL_RenderCopyEx");
	Dl_126406 = (TY126407) nimGetProcAddr(TMP196, "SDL_RenderClear");
	Dl_126417 = (TY126418) nimGetProcAddr(TMP196, "SDL_RenderPresent");
	Dl_126165 = (TY126166) nimGetProcAddr(TMP196, "SDL_Init");
	Dl_127011 = (TY127012) nimGetProcAddr(TMP196, "SDL_GetError");
	Dl_127411 = (TY127412) nimGetProcAddr(TMP196, "SDL_SetHint");
	Dl_126730 = (TY126731) nimGetProcAddr(TMP196, "SDL_CreateWindow");
	Dl_126205 = (TY126206) nimGetProcAddr(TMP196, "SDL_CreateRenderer");
	Dl_126017 = (TY126018) nimGetProcAddr(TMP196, "SDL_SetRenderDrawColor");
	Dl_126048 = (TY126049) nimGetProcAddr(TMP196, "SDL_DestroyRenderer");
	Dl_126762 = (TY126763) nimGetProcAddr(TMP196, "SDL_DestroyWindow");
	Dl_126177 = (TY126178) nimGetProcAddr(TMP196, "SDL_Quit");
}

