/* Generated by Nim Compiler v0.14.2 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/home/primat/programs/nim-0.14.2/lib -o /home/primat/projects/tests/nim/game_1/nimcache/stdlib_basic2d.o /home/primat/projects/tests/nim/game_1/nimcache/stdlib_basic2d.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <math.h>
#include <string.h>
typedef struct Matrix2d129021 Matrix2d129021;
typedef struct Point2d129023 Point2d129023;
typedef struct Vector2d129025 Vector2d129025;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct Divbyzeroerror3438 Divbyzeroerror3438;
typedef struct Arithmeticerror3436 Arithmeticerror3436;
typedef struct Exception Exception;
typedef struct TNimObject TNimObject;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct Cell48305 Cell48305;
typedef struct Cellseq48321 Cellseq48321;
typedef struct Gcheap50818 Gcheap50818;
typedef struct Gcstack50816 Gcstack50816;
typedef struct Memregion30486 Memregion30486;
typedef struct Smallchunk30440 Smallchunk30440;
typedef struct Llchunk30480 Llchunk30480;
typedef struct Bigchunk30442 Bigchunk30442;
typedef struct Intset30414 Intset30414;
typedef struct Trunk30410 Trunk30410;
typedef struct Avlnode30484 Avlnode30484;
typedef struct Gcstat50814 Gcstat50814;
typedef struct Cellset48317 Cellset48317;
typedef struct Pagedesc48313 Pagedesc48313;
typedef struct Basechunk30438 Basechunk30438;
typedef struct Freecell30430 Freecell30430;
struct  Matrix2d129021  {
NF ax;
NF ay;
NF bx;
NF by;
NF tx;
NF ty;
};
struct  Point2d129023  {
NF x;
NF y;
};
struct  Vector2d129025  {
NF x;
NF y;
};
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NU8 Floatformatmode113202;
typedef NU8 Tnimkind3203;
typedef NU8 Tnimtypeflag3209Set;
typedef N_NIMCALL_PTR(void, TY3289) (void* p0, NI op0);
typedef N_NIMCALL_PTR(void*, TY3294) (void* p0);
struct  TNimType  {
NI size;
Tnimkind3203 kind;
Tnimtypeflag3209Set flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3289 marker;
TY3294 deepcopy;
};
struct  TNimObject  {
TNimType* m_type;
};
struct  Exception  {
  TNimObject Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
NimStringDesc* trace;
};
struct  Arithmeticerror3436  {
  Exception Sup;
};
struct  Divbyzeroerror3438  {
  Arithmeticerror3436 Sup;
};
typedef NU8 Tnimnodekind3205;
struct  TNimNode  {
Tnimnodekind3205 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct  Cell48305  {
NI refcount;
TNimType* typ;
};
struct  Cellseq48321  {
NI len;
NI cap;
Cell48305** d;
};
typedef Smallchunk30440* TY30501[512];
typedef Trunk30410* Trunkbuckets30412[256];
struct  Intset30414  {
Trunkbuckets30412 data;
};
struct  Memregion30486  {
NI minlargeobj;
NI maxlargeobj;
TY30501 freesmallchunks;
Llchunk30480* llmem;
NI currmem;
NI maxmem;
NI freemem;
NI lastsize;
Bigchunk30442* freechunkslist;
Intset30414 chunkstarts;
Avlnode30484* root;
Avlnode30484* deleted;
Avlnode30484* last;
Avlnode30484* freeavlnodes;
NIM_BOOL locked;
};
struct  Gcstat50814  {
NI stackscans;
NI cyclecollections;
NI maxthreshold;
NI maxstacksize;
NI maxstackcells;
NI cycletablesize;
NI64 maxpause;
};
struct  Cellset48317  {
NI counter;
NI max;
Pagedesc48313* head;
Pagedesc48313** data;
};
struct  Gcheap50818  {
Gcstack50816* stack;
void* stackbottom;
NI cyclethreshold;
Cellseq48321 zct;
Cellseq48321 decstack;
Cellseq48321 tempstack;
NI recgclock;
Memregion30486 region;
Gcstat50814 stat;
Cellset48317 marked;
Cellseq48321 additionalroots;
};
struct  Gcstack50816  {
Gcstack50816* prev;
Gcstack50816* next;
void* starts;
void* pos;
NI maxstacksize;
};
struct  Basechunk30438  {
NI prevsize;
NI size;
NIM_BOOL used;
};
struct  Smallchunk30440  {
  Basechunk30438 Sup;
Smallchunk30440* next;
Smallchunk30440* prev;
Freecell30430* freelist;
NI free;
NI acc;
NF data;
};
struct  Llchunk30480  {
NI size;
NI acc;
Llchunk30480* next;
};
struct  Bigchunk30442  {
  Basechunk30438 Sup;
Bigchunk30442* next;
Bigchunk30442* prev;
NI align;
NF data;
};
typedef NI TY30419[8];
struct  Trunk30410  {
Trunk30410* next;
NI key;
TY30419 bits;
};
typedef Avlnode30484* TY30491[2];
struct  Avlnode30484  {
TY30491 link;
NI key;
NI upperbound;
NI level;
};
struct  Pagedesc48313  {
Pagedesc48313* next;
NI key;
TY30419 bits;
};
struct  Freecell30430  {
Freecell30430* next;
NI zerofield;
};
N_NIMCALL(NimStringDesc*, rtos_129063_2328089844)(NF val0);
N_NIMCALL(NimStringDesc*, nsuformatFloat)(NF f0, Floatformatmode113202 format0, NI precision0, NIM_CHAR decimalsep0);
static N_INLINE(void, nimFrame)(TFrame* s0);
N_NOINLINE(void, stackoverflow_22401_1689653243)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(NF, clamp_129073_1689653243)(NF x0, NF a0, NF b0);
N_NIMCALL(NF, safearccos_129067_2328089844)(NF v0);
static N_INLINE(void, setelements_129113_2328089844)(Matrix2d129021* t0, NF ax0, NF ay0, NF bx0, NF by0, NF tx0, NF ty0);
N_NIMCALL(Matrix2d129021, matrix2d_129039_2328089844)(NF ax0, NF ay0, NF bx0, NF by0, NF tx0, NF ty0);
N_NIMCALL(Matrix2d129021, HEX26_129133_2328089844)(Matrix2d129021* a0, Matrix2d129021* b0);
N_NIMCALL(Matrix2d129021, scale_129139_2328089844)(NF s0);
N_NIMCALL(Matrix2d129021, scale_129148_2328089844)(NF s0, Point2d129023 org0);
N_NIMCALL(Matrix2d129021, stretch_129156_2328089844)(NF sx0, NF sy0);
N_NIMCALL(Matrix2d129021, stretch_129166_2328089844)(NF sx0, NF sy0, Point2d129023 org0);
N_NIMCALL(Matrix2d129021, move_129175_2328089844)(NF dx0, NF dy0);
N_NIMCALL(Matrix2d129021, move_129185_2328089844)(Vector2d129025 v0);
N_NIMCALL(Matrix2d129021, rotate_129194_2328089844)(NF rad0);
N_NIMCALL(Matrix2d129021, rotate_129203_2328089844)(NF rad0, Point2d129023 org0);
N_NIMCALL(Matrix2d129021, mirror_129211_2328089844)(Vector2d129025 v0);
N_NIMCALL(Matrix2d129021, mirror_129225_2328089844)(Point2d129023 org0, Vector2d129025 v0);
N_NIMCALL(Matrix2d129021, skew_129240_2328089844)(NF xskew0, NF yskew0);
N_NIMCALL(NimStringDesc*, HEX24_129248_2328089844)(Matrix2d129021* t0);
static N_INLINE(void, appendString)(NimStringDesc* dest0, NimStringDesc* src0);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space0);
N_NIMCALL(NIM_BOOL, isuniform_129252_2328089844)(Matrix2d129021* t0, NF tol0);
N_NIMCALL(NF, determinant_129257_2328089844)(Matrix2d129021* t0);
N_NIMCALL(NIM_BOOL, ismirroring_129261_2328089844)(Matrix2d129021* m0);
N_NIMCALL(Matrix2d129021, inverse_129265_2328089844)(Matrix2d129021* m0);
N_NIMCALL(void*, newObj)(TNimType* typ0, NI size0);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src0);
static N_INLINE(void, nimGCunrefNoCycle)(void* p0);
static N_INLINE(Cell48305*, usrtocell_52440_1689653243)(void* usr0);
static N_INLINE(void, rtladdzct_53601_1689653243)(Cell48305* c0);
N_NOINLINE(void, addzct_52417_1689653243)(Cellseq48321* s0, Cell48305* c0);
N_NIMCALL(void, raiseException)(Exception* e0, NCSTRING ename0);
N_NIMCALL(NIM_BOOL, equals_129285_2328089844)(Matrix2d129021* m10, Matrix2d129021* m20, NF tol0);
N_NIMCALL(NIM_BOOL, HEX3DHEX7E_129291_2328089844)(Matrix2d129021* m10, Matrix2d129021* m20);
N_NIMCALL(NIM_BOOL, isidentity_129296_2328089844)(Matrix2d129021* m0, NF tol0);
N_NIMCALL(void, apply_129301_2328089844)(Matrix2d129021* m0, NF* x0, NF* y0, NIM_BOOL translate0);
static N_INLINE(Vector2d129025, vector2d_129047_2328089844)(NF x0, NF y0);
N_NIMCALL(Vector2d129025, polarvector2d_129315_2328089844)(NF ang0, NF len0);
N_NIMCALL(Vector2d129025, slopevector2d_129320_2328089844)(NF slope0, NF len0);
static N_INLINE(NF, len_129326_2328089844)(Vector2d129025 v0);
N_NIMCALL(void, lenHEX3D_129330_2328089844)(Vector2d129025* v0, NF newlen0);
static N_INLINE(void, HEX2AHEX3D_113691_1689653243)(NF* x0, NF y0);
static N_INLINE(NF, sqrlen_129360_2328089844)(Vector2d129025 v0);
N_NIMCALL(NF, angle_129364_2328089844)(Vector2d129025 v0);
static N_INLINE(void, HEX2BHEX3D_113701_1689653243)(NF* x0, NF y0);
N_NIMCALL(NimStringDesc*, HEX24_129378_2328089844)(Vector2d129025 v0);
N_NIMCALL(NimStringDesc*, resizeString)(NimStringDesc* dest0, NI addlen0);
N_NIMCALL(Vector2d129025, HEX26_129382_2328089844)(Vector2d129025 v0, Matrix2d129021* m0);
static N_INLINE(void, HEX26HEX3D_129387_2328089844)(Vector2d129025* v0, Matrix2d129021* m0);
N_NIMCALL(NIM_BOOL, trynormalize_129393_2328089844)(Vector2d129025* v0);
static N_INLINE(void, HEX2FHEX3D_91059_1689653243)(NF* x0, NF y0);
static N_INLINE(void, normalize_129401_2328089844)(Vector2d129025* v0);
N_NIMCALL(void, transformnorm_129419_2328089844)(Vector2d129025* v0, Matrix2d129021* t0);
N_NIMCALL(void, transforminv_129440_2328089844)(Vector2d129025* v0, Matrix2d129021* t0);
N_NIMCALL(void, transformnorminv_129461_2328089844)(Vector2d129025* v0, Matrix2d129021* t0);
static N_INLINE(void, rotate90_129467_2328089844)(Vector2d129025* v0);
static N_INLINE(void, rotate180_129481_2328089844)(Vector2d129025* v0);
static N_INLINE(void, rotate270_129485_2328089844)(Vector2d129025* v0);
N_NIMCALL(void, rotate_129499_2328089844)(Vector2d129025* v0, NF rad0);
static N_INLINE(void, scale_129507_2328089844)(Vector2d129025* v0, NF fac0);
static N_INLINE(void, stretch_129532_2328089844)(Vector2d129025* v0, NF facx0, NF facy0);
N_NIMCALL(void, mirror_129558_2328089844)(Vector2d129025* v0, Vector2d129025 mirrvec0);
N_NIMCALL(Vector2d129025, HEX2D_129573_2328089844)(Vector2d129025 v0);
static N_INLINE(Vector2d129025, HEX2B_129589_2328089844)(Vector2d129025 a_129578_2328089844, Vector2d129025 b_129580_2328089844);
static N_INLINE(Vector2d129025, HEX2B_129592_2328089844)(Vector2d129025 a_129582_2328089844, NF b_129584_2328089844);
static N_INLINE(Vector2d129025, HEX2B_129595_2328089844)(NF a_129586_2328089844, Vector2d129025 b_129588_2328089844);
static N_INLINE(Vector2d129025, HEX2D_129610_2328089844)(Vector2d129025 a_129599_2328089844, Vector2d129025 b_129601_2328089844);
static N_INLINE(Vector2d129025, HEX2D_129613_2328089844)(Vector2d129025 a_129603_2328089844, NF b_129605_2328089844);
static N_INLINE(Vector2d129025, HEX2D_129616_2328089844)(NF a_129607_2328089844, Vector2d129025 b_129609_2328089844);
static N_INLINE(Vector2d129025, HEX2A_129631_2328089844)(Vector2d129025 a_129620_2328089844, Vector2d129025 b_129622_2328089844);
static N_INLINE(Vector2d129025, HEX2A_129634_2328089844)(Vector2d129025 a_129624_2328089844, NF b_129626_2328089844);
static N_INLINE(Vector2d129025, HEX2A_129637_2328089844)(NF a_129628_2328089844, Vector2d129025 b_129630_2328089844);
static N_INLINE(Vector2d129025, HEX2F_129652_2328089844)(Vector2d129025 a_129641_2328089844, Vector2d129025 b_129643_2328089844);
static N_INLINE(Vector2d129025, HEX2F_129655_2328089844)(Vector2d129025 a_129645_2328089844, NF b_129647_2328089844);
static N_INLINE(Vector2d129025, HEX2F_129658_2328089844)(NF a_129649_2328089844, Vector2d129025 b_129651_2328089844);
static N_INLINE(void, HEX2BHEX3D_129669_2328089844)(Vector2d129025* a_129662_2328089844, Vector2d129025 b_129664_2328089844);
static N_INLINE(void, HEX2BHEX3D_129692_2328089844)(Vector2d129025* a_129666_2328089844, NF b_129668_2328089844);
static N_INLINE(void, HEX2DHEX3D_129727_1689653243)(NF* x0, NF y0);
static N_INLINE(void, HEX2DHEX3D_129723_2328089844)(Vector2d129025* a_129716_2328089844, Vector2d129025 b_129718_2328089844);
static N_INLINE(void, HEX2DHEX3D_129746_2328089844)(Vector2d129025* a_129720_2328089844, NF b_129722_2328089844);
static N_INLINE(void, HEX2AHEX3D_129777_2328089844)(Vector2d129025* a_129770_2328089844, Vector2d129025 b_129772_2328089844);
static N_INLINE(void, HEX2AHEX3D_129800_2328089844)(Vector2d129025* a_129774_2328089844, NF b_129776_2328089844);
static N_INLINE(void, HEX2FHEX3D_129831_2328089844)(Vector2d129025* a_129824_2328089844, Vector2d129025 b_129826_2328089844);
static N_INLINE(void, HEX2FHEX3D_129836_2328089844)(Vector2d129025* a_129828_2328089844, NF b_129830_2328089844);
N_NIMCALL(NF, dot_129841_2328089844)(Vector2d129025 v10, Vector2d129025 v20);
N_NIMCALL(NF, cross_129846_2328089844)(Vector2d129025 v10, Vector2d129025 v20);
N_NIMCALL(NIM_BOOL, equals_129851_2328089844)(Vector2d129025 v10, Vector2d129025 v20, NF tol0);
N_NIMCALL(NIM_BOOL, HEX3DHEX7E_129857_2328089844)(Vector2d129025 v10, Vector2d129025 v20);
N_NIMCALL(NF, angleto_129862_2328089844)(Vector2d129025 v10, Vector2d129025 v20);
N_NIMCALL(NF, angleccw_129871_2328089844)(Vector2d129025 v10, Vector2d129025 v20);
N_NIMCALL(NF, anglecw_129877_2328089844)(Vector2d129025 v10, Vector2d129025 v20);
N_NIMCALL(NF, turnangle_129883_2328089844)(Vector2d129025 v10, Vector2d129025 v20);
N_NIMCALL(Vector2d129025, bisect_129889_2328089844)(Vector2d129025 v10, Vector2d129025 v20);
static N_INLINE(Point2d129023, point2d_129051_2328089844)(NF x0, NF y0);
N_NIMCALL(NF, sqrdist_129908_2328089844)(Point2d129023 a0, Point2d129023 b0);
static N_INLINE(NF, dist_129915_2328089844)(Point2d129023 a0, Point2d129023 b0);
N_NIMCALL(NF, angle_129920_2328089844)(Point2d129023 a0, Point2d129023 b0);
N_NIMCALL(NimStringDesc*, HEX24_129939_2328089844)(Point2d129023 p0);
static N_INLINE(Point2d129023, HEX26_129943_2328089844)(Point2d129023 p0, Matrix2d129021* t0);
static N_INLINE(void, HEX26HEX3D_129948_2328089844)(Point2d129023* p0, Matrix2d129021* t0);
static N_INLINE(void, transforminv_129954_2328089844)(Point2d129023* p0, Matrix2d129021* t0);
static N_INLINE(Point2d129023, HEX2B_129975_2328089844)(Point2d129023 p0, Vector2d129025 v0);
static N_INLINE(void, HEX2BHEX3D_129980_2328089844)(Point2d129023* p0, Vector2d129025 v0);
static N_INLINE(Point2d129023, HEX2D_130005_2328089844)(Point2d129023 p0, Vector2d129025 v0);
static N_INLINE(Vector2d129025, HEX2D_130010_2328089844)(Point2d129023 p10, Point2d129023 p20);
static N_INLINE(void, HEX2DHEX3D_130015_2328089844)(Point2d129023* p0, Vector2d129025 v0);
static N_INLINE(NIM_BOOL, equals_130040_2328089844)(Point2d129023 p10, Point2d129023 p20, NF tol0);
static N_INLINE(NIM_BOOL, HEX3DHEX7E_130046_2328089844)(Point2d129023 p10, Point2d129023 p20);
N_NIMCALL(Point2d129023, polar_130051_2328089844)(Point2d129023 p0, NF ang0, NF dist0);
N_NIMCALL(void, rotate_130057_2328089844)(Point2d129023* p0, NF rad0);
N_NIMCALL(void, rotate_130065_2328089844)(Point2d129023* p0, NF rad0, Point2d129023 org0);
static N_INLINE(void, scale_130074_2328089844)(Point2d129023* p0, NF fac0);
static N_INLINE(void, scale_130099_2328089844)(Point2d129023* p0, NF fac0, Point2d129023 org0);
static N_INLINE(void, stretch_130105_2328089844)(Point2d129023* p0, NF facx0, NF facy0);
static N_INLINE(void, stretch_130131_2328089844)(Point2d129023* p0, NF facx0, NF facy0, Point2d129023 org0);
static N_INLINE(void, move_130138_2328089844)(Point2d129023* p0, NF dx0, NF dy0);
static N_INLINE(void, move_130164_2328089844)(Point2d129023* p0, Vector2d129025 v0);
N_NIMCALL(NF, sgnarea_130189_2328089844)(Point2d129023 a0, Point2d129023 b0, Point2d129023 c0);
N_NIMCALL(NF, area_130195_2328089844)(Point2d129023 a0, Point2d129023 b0, Point2d129023 c0);
N_NIMCALL(Point2d129023, closestpoint_130201_2328089844)(Point2d129023 p0, Point2d129023* pts0, NI pts0Len0);
N_NIMCALL(void, failedassertimpl_91239_1689653243)(NimStringDesc* msg0);
N_NOINLINE(void, raiseIndexError)(void);
static N_INLINE(NI, addInt)(NI a0, NI b0);
N_NOINLINE(void, raiseOverflow)(void);
N_NIMCALL(NF, mod_130428_1009420244)(NF x0, NF y0);
N_NIMCALL(NF, normangle_130423_2328089844)(NF ang0);
static N_INLINE(NF, degtorad_130436_2328089844)(NF deg0);
static N_INLINE(NF, radtodeg_130440_2328089844)(NF rad0);
STRING_LITERAL(TMP184, ",", 1);
STRING_LITERAL(TMP185, "Cannot invert a zero determinant matrix", 39);
STRING_LITERAL(TMP186, "Cannot normalize zero length vector", 35);
STRING_LITERAL(TMP187, "Matrix is not invertible", 24);
STRING_LITERAL(TMP188, "\012  0 < len(pts) ", 16);
Matrix2d129021 Idmatrix_129055_2328089844;
Point2d129023 Origo_129056_2328089844;
Vector2d129025 Xaxis_129057_2328089844;
Vector2d129025 Yaxis_129058_2328089844;
extern TFrame* frameptr_19636_1689653243;
extern TNimType NTI24493; /* ref DivByZeroError */
extern TNimType NTI3438; /* DivByZeroError */
extern Gcheap50818 gch_50858_1689653243;
TNimType NTI129023; /* Point2d */
extern TNimType NTI124; /* float */
TNimType NTI129025; /* Vector2d */

static N_INLINE(void, nimFrame)(TFrame* s0) {
	NI LOC1;
	LOC1 = (NI)0;
	{
		if (!(frameptr_19636_1689653243 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_19636_1689653243).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s0).calldepth = ((NI16) (LOC1));
	(*s0).prev = frameptr_19636_1689653243;
	frameptr_19636_1689653243 = s0;
	{
		if (!((*s0).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_22401_1689653243();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_19636_1689653243 = (*frameptr_19636_1689653243).prev;
}

N_NIMCALL(NimStringDesc*, rtos_129063_2328089844)(NF val0) {
	NimStringDesc* result0;
	nimfr("rtos", "basic2d.nim")
{	result0 = (NimStringDesc*)0;
	nimln(110, "basic2d.nim");
	result0 = nsuformatFloat(val0, ((Floatformatmode113202) 0), ((NI) 0), 46);
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result0;
}

N_NIMCALL(NF, safearccos_129067_2328089844)(NF v0) {
	NF result0;
	NF LOC1;
	nimfr("safeArccos", "basic2d.nim")
{	result0 = (NF)0;
	nimln(116, "basic2d.nim");
	LOC1 = (NF)0;
	LOC1 = clamp_129073_1689653243(v0, -1.0000000000000000e+00, 1.0000000000000000e+00);
	result0 = acos(LOC1);
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result0;
}

static N_INLINE(void, setelements_129113_2328089844)(Matrix2d129021* t0, NF ax0, NF ay0, NF bx0, NF by0, NF tx0, NF ty0) {
	nimfr("setElements", "basic2d.nim")
	nimln(137, "basic2d.nim");
	(*t0).ax = ax0;
	nimln(138, "basic2d.nim");
	(*t0).ay = ay0;
	nimln(139, "basic2d.nim");
	(*t0).bx = bx0;
	nimln(140, "basic2d.nim");
	(*t0).by = by0;
	nimln(141, "basic2d.nim");
	(*t0).tx = tx0;
	nimln(142, "basic2d.nim");
	(*t0).ty = ty0;
	popFrame();
}

N_NIMCALL(Matrix2d129021, matrix2d_129039_2328089844)(NF ax0, NF ay0, NF bx0, NF by0, NF tx0, NF ty0) {
	Matrix2d129021 result0;
	nimfr("matrix2d", "basic2d.nim")
	nimln(145, "basic2d.nim");
	setelements_129113_2328089844((&result0), ax0, ay0, bx0, by0, tx0, ty0);
	popFrame();
	return result0;
}

N_NIMCALL(Matrix2d129021, HEX26_129133_2328089844)(Matrix2d129021* a0, Matrix2d129021* b0) {
	Matrix2d129021 result0;
	nimfr("&", "basic2d.nim")
	nimln(153, "basic2d.nim");
	nimln(154, "basic2d.nim");
	nimln(155, "basic2d.nim");
	nimln(156, "basic2d.nim");
	nimln(157, "basic2d.nim");
	nimln(158, "basic2d.nim");
	nimln(159, "basic2d.nim");
	setelements_129113_2328089844((&result0), ((NF)(((NF)((*a0).ax) * (NF)((*b0).ax))) + (NF)(((NF)((*a0).ay) * (NF)((*b0).bx)))), ((NF)(((NF)((*a0).ax) * (NF)((*b0).ay))) + (NF)(((NF)((*a0).ay) * (NF)((*b0).by)))), ((NF)(((NF)((*a0).bx) * (NF)((*b0).ax))) + (NF)(((NF)((*a0).by) * (NF)((*b0).bx)))), ((NF)(((NF)((*a0).bx) * (NF)((*b0).ay))) + (NF)(((NF)((*a0).by) * (NF)((*b0).by)))), ((NF)(((NF)(((NF)((*a0).tx) * (NF)((*b0).ax))) + (NF)(((NF)((*a0).ty) * (NF)((*b0).bx))))) + (NF)((*b0).tx)), ((NF)(((NF)(((NF)((*a0).tx) * (NF)((*b0).ay))) + (NF)(((NF)((*a0).ty) * (NF)((*b0).by))))) + (NF)((*b0).ty)));
	popFrame();
	return result0;
}

N_NIMCALL(Matrix2d129021, scale_129139_2328089844)(NF s0) {
	Matrix2d129021 result0;
	nimfr("scale", "basic2d.nim")
	nimln(164, "basic2d.nim");
	setelements_129113_2328089844((&result0), s0, 0.0, 0.0, s0, 0.0, 0.0);
	popFrame();
	return result0;
}

N_NIMCALL(Matrix2d129021, scale_129148_2328089844)(NF s0, Point2d129023 org0) {
	Matrix2d129021 result0;
	nimfr("scale", "basic2d.nim")
	nimln(168, "basic2d.nim");
	setelements_129113_2328089844((&result0), s0, 0.0, 0.0, s0, ((NF)(org0.x) - (NF)(((NF)(s0) * (NF)(org0.x)))), ((NF)(org0.y) - (NF)(((NF)(s0) * (NF)(org0.y)))));
	popFrame();
	return result0;
}

N_NIMCALL(Matrix2d129021, stretch_129156_2328089844)(NF sx0, NF sy0) {
	Matrix2d129021 result0;
	nimfr("stretch", "basic2d.nim")
	nimln(173, "basic2d.nim");
	setelements_129113_2328089844((&result0), sx0, 0.0, 0.0, sy0, 0.0, 0.0);
	popFrame();
	return result0;
}

N_NIMCALL(Matrix2d129021, stretch_129166_2328089844)(NF sx0, NF sy0, Point2d129023 org0) {
	Matrix2d129021 result0;
	nimfr("stretch", "basic2d.nim")
	nimln(179, "basic2d.nim");
	setelements_129113_2328089844((&result0), sx0, 0.0, 0.0, sy0, ((NF)(org0.x) - (NF)(((NF)(sx0) * (NF)(org0.x)))), ((NF)(org0.y) - (NF)(((NF)(sy0) * (NF)(org0.y)))));
	popFrame();
	return result0;
}

N_NIMCALL(Matrix2d129021, move_129175_2328089844)(NF dx0, NF dy0) {
	Matrix2d129021 result0;
	nimfr("move", "basic2d.nim")
	nimln(183, "basic2d.nim");
	setelements_129113_2328089844((&result0), 1.0000000000000000e+00, 0.0, 0.0, 1.0000000000000000e+00, dx0, dy0);
	popFrame();
	return result0;
}

N_NIMCALL(Matrix2d129021, move_129185_2328089844)(Vector2d129025 v0) {
	Matrix2d129021 result0;
	nimfr("move", "basic2d.nim")
	nimln(187, "basic2d.nim");
	setelements_129113_2328089844((&result0), 1.0000000000000000e+00, 0.0, 0.0, 1.0000000000000000e+00, v0.x, v0.y);
	popFrame();
	return result0;
}

N_NIMCALL(Matrix2d129021, rotate_129194_2328089844)(NF rad0) {
	Matrix2d129021 result0;
	NF s0;
	NF c0;
	nimfr("rotate", "basic2d.nim")
	nimln(193, "basic2d.nim");
	s0 = sin(rad0);
	nimln(194, "basic2d.nim");
	c0 = cos(rad0);
	nimln(195, "basic2d.nim");
	setelements_129113_2328089844((&result0), c0, s0, -(s0), c0, 0.0, 0.0);
	popFrame();
	return result0;
}

N_NIMCALL(Matrix2d129021, rotate_129203_2328089844)(NF rad0, Point2d129023 org0) {
	Matrix2d129021 result0;
	NF s0;
	NF c0;
	nimfr("rotate", "basic2d.nim")
	nimln(202, "basic2d.nim");
	s0 = sin(rad0);
	nimln(203, "basic2d.nim");
	c0 = cos(rad0);
	nimln(204, "basic2d.nim");
	setelements_129113_2328089844((&result0), c0, s0, -(s0), c0, ((NF)(((NF)(org0.x) + (NF)(((NF)(s0) * (NF)(org0.y))))) - (NF)(((NF)(c0) * (NF)(org0.x)))), ((NF)(((NF)(org0.y) - (NF)(((NF)(c0) * (NF)(org0.y))))) - (NF)(((NF)(s0) * (NF)(org0.x)))));
	popFrame();
	return result0;
}

N_NIMCALL(Matrix2d129021, mirror_129211_2328089844)(Vector2d129025 v0) {
	Matrix2d129021 result0;
	NF sqx0;
	NF sqy0;
	NF nd0;
	NF xy20;
	NF sqd0;
	nimfr("mirror", "basic2d.nim")
{	nimln(211, "basic2d.nim");
	sqx0 = ((NF)(v0.x) * (NF)(v0.x));
	nimln(212, "basic2d.nim");
	sqy0 = ((NF)(v0.y) * (NF)(v0.y));
	nimln(213, "basic2d.nim");
	nd0 = ((NF)(1.0000000000000000e+00) / (NF)(((NF)(sqx0) + (NF)(sqy0))));
	nimln(214, "basic2d.nim");
	xy20 = ((NF)(((NF)(((NF)(v0.x) * (NF)(v0.y))) * (NF)(2.0000000000000000e+00))) * (NF)(nd0));
	nimln(215, "basic2d.nim");
	sqd0 = ((NF)(nd0) * (NF)(((NF)(sqx0) - (NF)(sqy0))));
	nimln(217, "basic2d.nim");
	{
		NIM_BOOL LOC3;
		LOC3 = (NIM_BOOL)0;
		LOC3 = (nd0 == INF);
		if (LOC3) goto LA4;
		LOC3 = (nd0 == -INF);
		LA4: ;
		if (!LOC3) goto LA5;
		nimln(218, "basic2d.nim");
		result0 = Idmatrix_129055_2328089844;
		goto BeforeRet;
	}
	LA5: ;
	nimln(220, "basic2d.nim");
	nimln(222, "basic2d.nim");
	setelements_129113_2328089844((&result0), sqd0, xy20, xy20, -(sqd0), 0.0, 0.0);
	}BeforeRet: ;
	popFrame();
	return result0;
}

N_NIMCALL(Matrix2d129021, mirror_129225_2328089844)(Point2d129023 org0, Vector2d129025 v0) {
	Matrix2d129021 result0;
	NF sqx0;
	NF sqy0;
	NF nd0;
	NF xy20;
	NF sqd0;
	nimfr("mirror", "basic2d.nim")
{	nimln(230, "basic2d.nim");
	sqx0 = ((NF)(v0.x) * (NF)(v0.x));
	nimln(231, "basic2d.nim");
	sqy0 = ((NF)(v0.y) * (NF)(v0.y));
	nimln(232, "basic2d.nim");
	nd0 = ((NF)(1.0000000000000000e+00) / (NF)(((NF)(sqx0) + (NF)(sqy0))));
	nimln(233, "basic2d.nim");
	xy20 = ((NF)(((NF)(((NF)(v0.x) * (NF)(v0.y))) * (NF)(2.0000000000000000e+00))) * (NF)(nd0));
	nimln(234, "basic2d.nim");
	sqd0 = ((NF)(nd0) * (NF)(((NF)(sqx0) - (NF)(sqy0))));
	nimln(236, "basic2d.nim");
	{
		NIM_BOOL LOC3;
		LOC3 = (NIM_BOOL)0;
		LOC3 = (nd0 == INF);
		if (LOC3) goto LA4;
		LOC3 = (nd0 == -INF);
		LA4: ;
		if (!LOC3) goto LA5;
		nimln(237, "basic2d.nim");
		result0 = Idmatrix_129055_2328089844;
		goto BeforeRet;
	}
	LA5: ;
	nimln(239, "basic2d.nim");
	nimln(241, "basic2d.nim");
	nimln(242, "basic2d.nim");
	setelements_129113_2328089844((&result0), sqd0, xy20, xy20, -(sqd0), ((NF)(((NF)(org0.x) - (NF)(((NF)(org0.y) * (NF)(xy20))))) - (NF)(((NF)(org0.x) * (NF)(sqd0)))), ((NF)(((NF)(org0.y) - (NF)(((NF)(org0.x) * (NF)(xy20))))) + (NF)(((NF)(org0.y) * (NF)(sqd0)))));
	}BeforeRet: ;
	popFrame();
	return result0;
}

N_NIMCALL(Matrix2d129021, skew_129240_2328089844)(NF xskew0, NF yskew0) {
	Matrix2d129021 result0;
	NF LOC1;
	NF LOC2;
	NF LOC3;
	NF LOC4;
	nimfr("skew", "basic2d.nim")
	nimln(250, "basic2d.nim");
	LOC1 = (NF)0;
	LOC1 = cos(yskew0);
	LOC2 = (NF)0;
	LOC2 = sin(yskew0);
	LOC3 = (NF)0;
	LOC3 = sin(xskew0);
	LOC4 = (NF)0;
	LOC4 = cos(xskew0);
	setelements_129113_2328089844((&result0), LOC1, LOC2, -(LOC3), LOC4, 0.0, 0.0);
	popFrame();
	return result0;
}

static N_INLINE(void, appendString)(NimStringDesc* dest0, NimStringDesc* src0) {
	memcpy(((NCSTRING) ((&(*dest0).data[((*dest0).Sup.len)- 0]))), ((NCSTRING) ((*src0).data)), (NI)((*src0).Sup.len + ((NI) 1)));
	(*dest0).Sup.len += (*src0).Sup.len;
}

N_NIMCALL(NimStringDesc*, HEX24_129248_2328089844)(Matrix2d129021* t0) {
	NimStringDesc* result0;
	NimStringDesc* LOC1;
	NimStringDesc* LOC2;
	NimStringDesc* LOC3;
	NimStringDesc* LOC4;
	NimStringDesc* LOC5;
	NimStringDesc* LOC6;
	NimStringDesc* LOC7;
	nimfr("$", "basic2d.nim")
{	nimln(255, "basic2d.nim");
	nimln(257, "basic2d.nim");
	LOC1 = (NimStringDesc*)0;
	nimln(255, "basic2d.nim");
	LOC2 = (NimStringDesc*)0;
	LOC2 = rtos_129063_2328089844((*t0).ax);
	LOC3 = (NimStringDesc*)0;
	LOC3 = rtos_129063_2328089844((*t0).ay);
	nimln(256, "basic2d.nim");
	LOC4 = (NimStringDesc*)0;
	LOC4 = rtos_129063_2328089844((*t0).bx);
	LOC5 = (NimStringDesc*)0;
	LOC5 = rtos_129063_2328089844((*t0).by);
	nimln(257, "basic2d.nim");
	LOC6 = (NimStringDesc*)0;
	LOC6 = rtos_129063_2328089844((*t0).tx);
	LOC7 = (NimStringDesc*)0;
	LOC7 = rtos_129063_2328089844((*t0).ty);
	LOC1 = rawNewString(LOC2->Sup.len + LOC3->Sup.len + LOC4->Sup.len + LOC5->Sup.len + LOC6->Sup.len + LOC7->Sup.len + 5);
appendString(LOC1, LOC2);
appendString(LOC1, ((NimStringDesc*) &TMP184));
appendString(LOC1, LOC3);
appendString(LOC1, ((NimStringDesc*) &TMP184));
appendString(LOC1, LOC4);
appendString(LOC1, ((NimStringDesc*) &TMP184));
appendString(LOC1, LOC5);
appendString(LOC1, ((NimStringDesc*) &TMP184));
appendString(LOC1, LOC6);
appendString(LOC1, ((NimStringDesc*) &TMP184));
appendString(LOC1, LOC7);
	result0 = LOC1;
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result0;
}

N_NIMCALL(NIM_BOOL, isuniform_129252_2328089844)(Matrix2d129021* t0, NF tol0) {
	NIM_BOOL result0;
	nimfr("isUniform", "basic2d.nim")
{	result0 = (NIM_BOOL)0;
	nimln(267, "basic2d.nim");
	{
		if (!((((NF)(((NF)((*t0).ax) * (NF)((*t0).bx))) + (NF)(((NF)((*t0).ay) * (NF)((*t0).by)))) > 0? (((NF)(((NF)((*t0).ax) * (NF)((*t0).bx))) + (NF)(((NF)((*t0).ay) * (NF)((*t0).by))))) : -(((NF)(((NF)((*t0).ax) * (NF)((*t0).bx))) + (NF)(((NF)((*t0).ay) * (NF)((*t0).by)))))) <= tol0)) goto LA3;
		nimln(269, "basic2d.nim");
		{
			if (!((((NF)(((NF)(((NF)((*t0).ax) * (NF)((*t0).ax))) + (NF)(((NF)((*t0).ay) * (NF)((*t0).ay))))) - (NF)(((NF)(((NF)((*t0).bx) * (NF)((*t0).bx))) + (NF)(((NF)((*t0).by) * (NF)((*t0).by)))))) > 0? (((NF)(((NF)(((NF)((*t0).ax) * (NF)((*t0).ax))) + (NF)(((NF)((*t0).ay) * (NF)((*t0).ay))))) - (NF)(((NF)(((NF)((*t0).bx) * (NF)((*t0).bx))) + (NF)(((NF)((*t0).by) * (NF)((*t0).by))))))) : -(((NF)(((NF)(((NF)((*t0).ax) * (NF)((*t0).ax))) + (NF)(((NF)((*t0).ay) * (NF)((*t0).ay))))) - (NF)(((NF)(((NF)((*t0).bx) * (NF)((*t0).bx))) + (NF)(((NF)((*t0).by) * (NF)((*t0).by)))))))) <= tol0)) goto LA7;
			nimln(270, "basic2d.nim");
			result0 = NIM_TRUE;
			goto BeforeRet;
		}
		LA7: ;
	}
	LA3: ;
	nimln(271, "basic2d.nim");
	result0 = NIM_FALSE;
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result0;
}

N_NIMCALL(NF, determinant_129257_2328089844)(Matrix2d129021* t0) {
	NF result0;
	nimfr("determinant", "basic2d.nim")
{	result0 = (NF)0;
	nimln(277, "basic2d.nim");
	result0 = ((NF)(((NF)((*t0).ax) * (NF)((*t0).by))) - (NF)(((NF)((*t0).bx) * (NF)((*t0).ay))));
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result0;
}

N_NIMCALL(NIM_BOOL, ismirroring_129261_2328089844)(Matrix2d129021* m0) {
	NIM_BOOL result0;
	NF LOC1;
	nimfr("isMirroring", "basic2d.nim")
{	result0 = (NIM_BOOL)0;
	nimln(282, "basic2d.nim");
	LOC1 = (NF)0;
	LOC1 = determinant_129257_2328089844(m0);
	result0 = (LOC1 < 0.0);
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result0;
}

static N_INLINE(Cell48305*, usrtocell_52440_1689653243)(void* usr0) {
	Cell48305* result0;
	nimfr("usrToCell", "gc.nim")
	result0 = (Cell48305*)0;
	nimln(131, "gc.nim");
	result0 = ((Cell48305*) ((NI)((NU64)(((NI) (usr0))) - (NU64)(((NI)sizeof(Cell48305))))));
	popFrame();
	return result0;
}

static N_INLINE(void, rtladdzct_53601_1689653243)(Cell48305* c0) {
	nimfr("rtlAddZCT", "gc.nim")
	nimln(211, "gc.nim");
	addzct_52417_1689653243((&gch_50858_1689653243.zct), c0);
	popFrame();
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p0) {
	Cell48305* c0;
	nimfr("nimGCunrefNoCycle", "gc.nim")
	nimln(253, "gc.nim");
	c0 = usrtocell_52440_1689653243(p0);
	nimln(255, "gc.nim");
	{
		nimln(177, "gc.nim");
		(*c0).refcount -= ((NI) 8);
		nimln(178, "gc.nim");
		if (!((NU64)((*c0).refcount) < (NU64)(((NI) 8)))) goto LA3;
		nimln(256, "gc.nim");
		rtladdzct_53601_1689653243(c0);
	}
	LA3: ;
	popFrame();
}

N_NIMCALL(Matrix2d129021, inverse_129265_2328089844)(Matrix2d129021* m0) {
	Matrix2d129021 result0;
	NF d0;
	nimfr("inverse", "basic2d.nim")
	nimln(288, "basic2d.nim");
	d0 = determinant_129257_2328089844(m0);
	nimln(289, "basic2d.nim");
	{
		Divbyzeroerror3438* e_129273_2328089844;
		NimStringDesc* LOC5;
		if (!(d0 == 0.0)) goto LA3;
		e_129273_2328089844 = (Divbyzeroerror3438*)0;
		nimln(2514, "system.nim");
		e_129273_2328089844 = (Divbyzeroerror3438*) newObj((&NTI24493), sizeof(Divbyzeroerror3438));
		(*e_129273_2328089844).Sup.Sup.Sup.m_type = (&NTI3438);
		nimln(2515, "system.nim");
		LOC5 = (NimStringDesc*)0;
		LOC5 = (*e_129273_2328089844).Sup.Sup.message; (*e_129273_2328089844).Sup.Sup.message = copyStringRC1(((NimStringDesc*) &TMP185));
		if (LOC5) nimGCunrefNoCycle(LOC5);
		nimln(290, "basic2d.nim");
		raiseException((Exception*)e_129273_2328089844, "DivByZeroError");
	}
	LA3: ;
	nimln(292, "basic2d.nim");
	nimln(293, "basic2d.nim");
	nimln(294, "basic2d.nim");
	nimln(295, "basic2d.nim");
	nimln(296, "basic2d.nim");
	setelements_129113_2328089844((&result0), ((NF)((*m0).by) / (NF)(d0)), ((NF)(-((*m0).ay)) / (NF)(d0)), ((NF)(-((*m0).bx)) / (NF)(d0)), ((NF)((*m0).ax) / (NF)(d0)), ((NF)(((NF)(((NF)((*m0).bx) * (NF)((*m0).ty))) - (NF)(((NF)((*m0).by) * (NF)((*m0).tx))))) / (NF)(d0)), ((NF)(((NF)(((NF)((*m0).ay) * (NF)((*m0).tx))) - (NF)(((NF)((*m0).ax) * (NF)((*m0).ty))))) / (NF)(d0)));
	popFrame();
	return result0;
}

N_NIMCALL(NIM_BOOL, equals_129285_2328089844)(Matrix2d129021* m10, Matrix2d129021* m20, NF tol0) {
	NIM_BOOL result0;
	NIM_BOOL LOC1;
	NIM_BOOL LOC2;
	NIM_BOOL LOC3;
	NIM_BOOL LOC4;
	NIM_BOOL LOC5;
	nimfr("equals", "basic2d.nim")
{	result0 = (NIM_BOOL)0;
	nimln(301, "basic2d.nim");
	nimln(306, "basic2d.nim");
	LOC1 = (NIM_BOOL)0;
	nimln(305, "basic2d.nim");
	LOC2 = (NIM_BOOL)0;
	nimln(304, "basic2d.nim");
	LOC3 = (NIM_BOOL)0;
	nimln(303, "basic2d.nim");
	LOC4 = (NIM_BOOL)0;
	nimln(302, "basic2d.nim");
	LOC5 = (NIM_BOOL)0;
	LOC5 = ((((NF)((*m10).ax) - (NF)((*m20).ax)) > 0? (((NF)((*m10).ax) - (NF)((*m20).ax))) : -(((NF)((*m10).ax) - (NF)((*m20).ax)))) <= tol0);
	if (!(LOC5)) goto LA6;
	nimln(303, "basic2d.nim");
	LOC5 = ((((NF)((*m10).ay) - (NF)((*m20).ay)) > 0? (((NF)((*m10).ay) - (NF)((*m20).ay))) : -(((NF)((*m10).ay) - (NF)((*m20).ay)))) <= tol0);
	LA6: ;
	LOC4 = LOC5;
	if (!(LOC4)) goto LA7;
	nimln(304, "basic2d.nim");
	LOC4 = ((((NF)((*m10).bx) - (NF)((*m20).bx)) > 0? (((NF)((*m10).bx) - (NF)((*m20).bx))) : -(((NF)((*m10).bx) - (NF)((*m20).bx)))) <= tol0);
	LA7: ;
	LOC3 = LOC4;
	if (!(LOC3)) goto LA8;
	nimln(305, "basic2d.nim");
	LOC3 = ((((NF)((*m10).by) - (NF)((*m20).by)) > 0? (((NF)((*m10).by) - (NF)((*m20).by))) : -(((NF)((*m10).by) - (NF)((*m20).by)))) <= tol0);
	LA8: ;
	LOC2 = LOC3;
	if (!(LOC2)) goto LA9;
	nimln(306, "basic2d.nim");
	LOC2 = ((((NF)((*m10).tx) - (NF)((*m20).tx)) > 0? (((NF)((*m10).tx) - (NF)((*m20).tx))) : -(((NF)((*m10).tx) - (NF)((*m20).tx)))) <= tol0);
	LA9: ;
	LOC1 = LOC2;
	if (!(LOC1)) goto LA10;
	nimln(307, "basic2d.nim");
	LOC1 = ((((NF)((*m10).ty) - (NF)((*m20).ty)) > 0? (((NF)((*m10).ty) - (NF)((*m20).ty))) : -(((NF)((*m10).ty) - (NF)((*m20).ty)))) <= tol0);
	LA10: ;
	result0 = LOC1;
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result0;
}

N_NIMCALL(NIM_BOOL, HEX3DHEX7E_129291_2328089844)(Matrix2d129021* m10, Matrix2d129021* m20) {
	NIM_BOOL result0;
	nimfr("=~", "basic2d.nim")
	result0 = (NIM_BOOL)0;
	nimln(310, "basic2d.nim");
	nimln(312, "basic2d.nim");
	result0 = equals_129285_2328089844(m10, m20, 9.9999999999999995e-07);
	popFrame();
	return result0;
}

N_NIMCALL(NIM_BOOL, isidentity_129296_2328089844)(Matrix2d129021* m0, NF tol0) {
	NIM_BOOL result0;
	nimfr("isIdentity", "basic2d.nim")
{	result0 = (NIM_BOOL)0;
	nimln(317, "basic2d.nim");
	result0 = equals_129285_2328089844(m0, (&Idmatrix_129055_2328089844), tol0);
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result0;
}

N_NIMCALL(void, apply_129301_2328089844)(Matrix2d129021* m0, NF* x0, NF* y0, NIM_BOOL translate0) {
	nimfr("apply", "basic2d.nim")
	nimln(322, "basic2d.nim");
	{
		NF newx0;
		if (!translate0) goto LA3;
		nimln(323, "basic2d.nim");
		newx0 = ((NF)(((NF)(((NF)((*x0)) * (NF)((*m0).ax))) + (NF)(((NF)((*y0)) * (NF)((*m0).bx))))) + (NF)((*m0).tx));
		nimln(324, "basic2d.nim");
		(*y0) = ((NF)(((NF)(((NF)((*x0)) * (NF)((*m0).ay))) + (NF)(((NF)((*y0)) * (NF)((*m0).by))))) + (NF)((*m0).ty));
		nimln(325, "basic2d.nim");
		(*x0) = newx0;
	}
	goto LA1;
	LA3: ;
	{
		NF newx0;
		nimln(327, "basic2d.nim");
		newx0 = ((NF)(((NF)((*x0)) * (NF)((*m0).ax))) + (NF)(((NF)((*y0)) * (NF)((*m0).bx))));
		nimln(328, "basic2d.nim");
		(*y0) = ((NF)(((NF)((*x0)) * (NF)((*m0).ay))) + (NF)(((NF)((*y0)) * (NF)((*m0).by))));
		nimln(329, "basic2d.nim");
		(*x0) = newx0;
	}
	LA1: ;
	popFrame();
}

static N_INLINE(Vector2d129025, vector2d_129047_2328089844)(NF x0, NF y0) {
	Vector2d129025 result0;
	nimfr("vector2d", "basic2d.nim")
	nimln(337, "basic2d.nim");
	result0.x = x0;
	nimln(338, "basic2d.nim");
	result0.y = y0;
	popFrame();
	return result0;
}

N_NIMCALL(Vector2d129025, polarvector2d_129315_2328089844)(NF ang0, NF len0) {
	Vector2d129025 result0;
	NF LOC1;
	NF LOC2;
	nimfr("polarVector2d", "basic2d.nim")
	nimln(342, "basic2d.nim");
	LOC1 = (NF)0;
	LOC1 = cos(ang0);
	result0.x = ((NF)(LOC1) * (NF)(len0));
	nimln(343, "basic2d.nim");
	LOC2 = (NF)0;
	LOC2 = sin(ang0);
	result0.y = ((NF)(LOC2) * (NF)(len0));
	popFrame();
	return result0;
}

N_NIMCALL(Vector2d129025, slopevector2d_129320_2328089844)(NF slope0, NF len0) {
	Vector2d129025 result0;
	NF ang0;
	NF LOC1;
	NF LOC2;
	nimfr("slopeVector2d", "basic2d.nim")
	nimln(348, "basic2d.nim");
	ang0 = atan(slope0);
	nimln(349, "basic2d.nim");
	LOC1 = (NF)0;
	LOC1 = cos(ang0);
	result0.x = ((NF)(LOC1) * (NF)(len0));
	nimln(350, "basic2d.nim");
	LOC2 = (NF)0;
	LOC2 = sin(ang0);
	result0.y = ((NF)(LOC2) * (NF)(len0));
	popFrame();
	return result0;
}

static N_INLINE(NF, len_129326_2328089844)(Vector2d129025 v0) {
	NF result0;
	nimfr("len", "basic2d.nim")
	result0 = (NF)0;
	nimln(353, "basic2d.nim");
	nimln(354, "basic2d.nim");
	result0 = sqrt(((NF)(((NF)(v0.x) * (NF)(v0.x))) + (NF)(((NF)(v0.y) * (NF)(v0.y)))));
	popFrame();
	return result0;
}

static N_INLINE(void, HEX2AHEX3D_113691_1689653243)(NF* x0, NF y0) {
	nimfr("*=", "system.nim")
	nimln(3324, "system.nim");
	(*x0) = ((NF)((*x0)) * (NF)(y0));
	popFrame();
}

N_NIMCALL(void, lenHEX3D_129330_2328089844)(Vector2d129025* v0, NF newlen0) {
	NF fac0;
	NF LOC1;
	nimfr("len=", "basic2d.nim")
{	nimln(358, "basic2d.nim");
	LOC1 = (NF)0;
	LOC1 = len_129326_2328089844((*v0));
	fac0 = ((NF)(newlen0) / (NF)(LOC1));
	nimln(360, "basic2d.nim");
	{
		if (!(newlen0 == 0.0)) goto LA4;
		nimln(361, "basic2d.nim");
		(*v0).x = 0.0;
		nimln(362, "basic2d.nim");
		(*v0).y = 0.0;
		nimln(363, "basic2d.nim");
		goto BeforeRet;
	}
	LA4: ;
	nimln(365, "basic2d.nim");
	{
		NIM_BOOL LOC8;
		LOC8 = (NIM_BOOL)0;
		LOC8 = (fac0 == INF);
		if (LOC8) goto LA9;
		LOC8 = (fac0 == -INF);
		LA9: ;
		if (!LOC8) goto LA10;
		nimln(368, "basic2d.nim");
		(*v0).x = newlen0;
		nimln(369, "basic2d.nim");
		(*v0).y = 0.0;
	}
	goto LA6;
	LA10: ;
	{
		nimln(371, "basic2d.nim");
		HEX2AHEX3D_113691_1689653243((&(*v0).x), fac0);
		nimln(372, "basic2d.nim");
		HEX2AHEX3D_113691_1689653243((&(*v0).y), fac0);
	}
	LA6: ;
	}BeforeRet: ;
	popFrame();
}

static N_INLINE(NF, sqrlen_129360_2328089844)(Vector2d129025 v0) {
	NF result0;
	nimfr("sqrLen", "basic2d.nim")
	result0 = (NF)0;
	nimln(375, "basic2d.nim");
	nimln(377, "basic2d.nim");
	result0 = ((NF)(((NF)(v0.x) * (NF)(v0.x))) + (NF)(((NF)(v0.y) * (NF)(v0.y))));
	popFrame();
	return result0;
}

static N_INLINE(void, HEX2BHEX3D_113701_1689653243)(NF* x0, NF y0) {
	nimfr("+=", "system.nim")
	nimln(3314, "system.nim");
	(*x0) = ((NF)((*x0)) + (NF)(y0));
	popFrame();
}

N_NIMCALL(NF, angle_129364_2328089844)(Vector2d129025 v0) {
	NF result0;
	nimfr("angle", "basic2d.nim")
	result0 = (NF)0;
	nimln(382, "basic2d.nim");
	result0 = atan2(v0.y, v0.x);
	nimln(383, "basic2d.nim");
	{
		if (!(result0 < 0.0)) goto LA3;
		HEX2BHEX3D_113701_1689653243((&result0), 6.2831853071795862e+00);
	}
	LA3: ;
	popFrame();
	return result0;
}

N_NIMCALL(NimStringDesc*, HEX24_129378_2328089844)(Vector2d129025 v0) {
	NimStringDesc* result0;
	NimStringDesc* LOC1;
	nimfr("$", "basic2d.nim")
	result0 = (NimStringDesc*)0;
	nimln(387, "basic2d.nim");
	result0 = rtos_129063_2328089844(v0.x);
	nimln(388, "basic2d.nim");
	result0 = resizeString(result0, 1);
appendString(result0, ((NimStringDesc*) &TMP184));
	nimln(389, "basic2d.nim");
	LOC1 = (NimStringDesc*)0;
	LOC1 = rtos_129063_2328089844(v0.y);
	result0 = resizeString(result0, LOC1->Sup.len + 0);
appendString(result0, LOC1);
	popFrame();
	return result0;
}

N_NIMCALL(Vector2d129025, HEX26_129382_2328089844)(Vector2d129025 v0, Matrix2d129021* m0) {
	Vector2d129025 result0;
	nimfr("&", "basic2d.nim")
	nimln(400, "basic2d.nim");
	result0.x = ((NF)(((NF)(v0.x) * (NF)((*m0).ax))) + (NF)(((NF)(v0.y) * (NF)((*m0).bx))));
	nimln(401, "basic2d.nim");
	result0.y = ((NF)(((NF)(v0.x) * (NF)((*m0).ay))) + (NF)(((NF)(v0.y) * (NF)((*m0).by))));
	popFrame();
	return result0;
}

static N_INLINE(void, HEX26HEX3D_129387_2328089844)(Vector2d129025* v0, Matrix2d129021* m0) {
	NF newx0;
	nimfr("&=", "basic2d.nim")
	nimln(412, "basic2d.nim");
	newx0 = ((NF)(((NF)((*v0).x) * (NF)((*m0).ax))) + (NF)(((NF)((*v0).y) * (NF)((*m0).bx))));
	nimln(413, "basic2d.nim");
	(*v0).y = ((NF)(((NF)((*v0).x) * (NF)((*m0).ay))) + (NF)(((NF)((*v0).y) * (NF)((*m0).by))));
	nimln(414, "basic2d.nim");
	(*v0).x = newx0;
	popFrame();
}

static N_INLINE(void, HEX2FHEX3D_91059_1689653243)(NF* x0, NF y0) {
	nimfr("/=", "system.nim")
	nimln(3328, "system.nim");
	(*x0) = ((NF)((*x0)) / (NF)(y0));
	popFrame();
}

N_NIMCALL(NIM_BOOL, trynormalize_129393_2328089844)(Vector2d129025* v0) {
	NIM_BOOL result0;
	NF mag0;
	nimfr("tryNormalize", "basic2d.nim")
{	result0 = (NIM_BOOL)0;
	nimln(422, "basic2d.nim");
	mag0 = len_129326_2328089844((*v0));
	nimln(424, "basic2d.nim");
	{
		if (!(mag0 == 0.0)) goto LA3;
		nimln(425, "basic2d.nim");
		result0 = NIM_FALSE;
		goto BeforeRet;
	}
	LA3: ;
	nimln(427, "basic2d.nim");
	HEX2FHEX3D_91059_1689653243((&(*v0).x), mag0);
	nimln(428, "basic2d.nim");
	HEX2FHEX3D_91059_1689653243((&(*v0).y), mag0);
	nimln(429, "basic2d.nim");
	result0 = NIM_TRUE;
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result0;
}

static N_INLINE(void, normalize_129401_2328089844)(Vector2d129025* v0) {
	nimfr("normalize", "basic2d.nim")
	nimln(435, "basic2d.nim");
	{
		NIM_BOOL LOC3;
		Divbyzeroerror3438* e_129408_2328089844;
		NimStringDesc* LOC6;
		LOC3 = (NIM_BOOL)0;
		LOC3 = trynormalize_129393_2328089844(v0);
		if (!!(LOC3)) goto LA4;
		e_129408_2328089844 = (Divbyzeroerror3438*)0;
		nimln(2514, "system.nim");
		e_129408_2328089844 = (Divbyzeroerror3438*) newObj((&NTI24493), sizeof(Divbyzeroerror3438));
		(*e_129408_2328089844).Sup.Sup.Sup.m_type = (&NTI3438);
		nimln(2515, "system.nim");
		LOC6 = (NimStringDesc*)0;
		LOC6 = (*e_129408_2328089844).Sup.Sup.message; (*e_129408_2328089844).Sup.Sup.message = copyStringRC1(((NimStringDesc*) &TMP186));
		if (LOC6) nimGCunrefNoCycle(LOC6);
		nimln(436, "basic2d.nim");
		raiseException((Exception*)e_129408_2328089844, "DivByZeroError");
	}
	LA4: ;
	popFrame();
}

N_NIMCALL(void, transformnorm_129419_2328089844)(Vector2d129025* v0, Matrix2d129021* t0) {
	NF d0;
	NF newx0;
	nimfr("transformNorm", "basic2d.nim")
	nimln(450, "basic2d.nim");
	d0 = determinant_129257_2328089844(t0);
	nimln(451, "basic2d.nim");
	{
		Divbyzeroerror3438* e_129428_2328089844;
		NimStringDesc* LOC5;
		if (!(d0 == 0.0)) goto LA3;
		e_129428_2328089844 = (Divbyzeroerror3438*)0;
		nimln(2514, "system.nim");
		e_129428_2328089844 = (Divbyzeroerror3438*) newObj((&NTI24493), sizeof(Divbyzeroerror3438));
		(*e_129428_2328089844).Sup.Sup.Sup.m_type = (&NTI3438);
		nimln(2515, "system.nim");
		LOC5 = (NimStringDesc*)0;
		LOC5 = (*e_129428_2328089844).Sup.Sup.message; (*e_129428_2328089844).Sup.Sup.message = copyStringRC1(((NimStringDesc*) &TMP187));
		if (LOC5) nimGCunrefNoCycle(LOC5);
		nimln(452, "basic2d.nim");
		raiseException((Exception*)e_129428_2328089844, "DivByZeroError");
	}
	LA3: ;
	nimln(453, "basic2d.nim");
	newx0 = ((NF)(((NF)(((NF)((*t0).by) * (NF)((*v0).x))) - (NF)(((NF)((*t0).ay) * (NF)((*v0).y))))) / (NF)(d0));
	nimln(454, "basic2d.nim");
	(*v0).y = ((NF)(((NF)(((NF)((*t0).ax) * (NF)((*v0).y))) - (NF)(((NF)((*t0).bx) * (NF)((*v0).x))))) / (NF)(d0));
	nimln(455, "basic2d.nim");
	(*v0).x = newx0;
	popFrame();
}

N_NIMCALL(void, transforminv_129440_2328089844)(Vector2d129025* v0, Matrix2d129021* t0) {
	NF d0;
	NF newx0;
	nimfr("transformInv", "basic2d.nim")
	nimln(463, "basic2d.nim");
	d0 = determinant_129257_2328089844(t0);
	nimln(465, "basic2d.nim");
	{
		Divbyzeroerror3438* e_129449_2328089844;
		NimStringDesc* LOC5;
		if (!(d0 == 0.0)) goto LA3;
		e_129449_2328089844 = (Divbyzeroerror3438*)0;
		nimln(2514, "system.nim");
		e_129449_2328089844 = (Divbyzeroerror3438*) newObj((&NTI24493), sizeof(Divbyzeroerror3438));
		(*e_129449_2328089844).Sup.Sup.Sup.m_type = (&NTI3438);
		nimln(2515, "system.nim");
		LOC5 = (NimStringDesc*)0;
		LOC5 = (*e_129449_2328089844).Sup.Sup.message; (*e_129449_2328089844).Sup.Sup.message = copyStringRC1(((NimStringDesc*) &TMP187));
		if (LOC5) nimGCunrefNoCycle(LOC5);
		nimln(466, "basic2d.nim");
		raiseException((Exception*)e_129449_2328089844, "DivByZeroError");
	}
	LA3: ;
	nimln(468, "basic2d.nim");
	newx0 = ((NF)(((NF)(((NF)((*t0).by) * (NF)((*v0).x))) - (NF)(((NF)((*t0).bx) * (NF)((*v0).y))))) / (NF)(d0));
	nimln(469, "basic2d.nim");
	(*v0).y = ((NF)(((NF)(((NF)((*t0).ax) * (NF)((*v0).y))) - (NF)(((NF)((*t0).ay) * (NF)((*v0).x))))) / (NF)(d0));
	nimln(470, "basic2d.nim");
	(*v0).x = newx0;
	popFrame();
}

N_NIMCALL(void, transformnorminv_129461_2328089844)(Vector2d129025* v0, Matrix2d129021* t0) {
	NF newx0;
	nimfr("transformNormInv", "basic2d.nim")
	nimln(485, "basic2d.nim");
	newx0 = ((NF)(((NF)((*t0).ay) * (NF)((*v0).y))) + (NF)(((NF)((*t0).ax) * (NF)((*v0).x))));
	nimln(486, "basic2d.nim");
	(*v0).y = ((NF)(((NF)((*t0).by) * (NF)((*v0).y))) + (NF)(((NF)((*t0).bx) * (NF)((*v0).x))));
	nimln(487, "basic2d.nim");
	(*v0).x = newx0;
	popFrame();
}

static N_INLINE(void, rotate90_129467_2328089844)(Vector2d129025* v0) {
	NF LOC1;
	nimfr("rotate90", "basic2d.nim")
	nimln(492, "basic2d.nim");
	LOC1 = (NF)0;
	LOC1 = (*v0).x;
	(*v0).x = (*v0).y;
	(*v0).y = LOC1;
	nimln(493, "basic2d.nim");
	(*v0).x = -((*v0).x);
	popFrame();
}

static N_INLINE(void, rotate180_129481_2328089844)(Vector2d129025* v0) {
	nimfr("rotate180", "basic2d.nim")
	nimln(498, "basic2d.nim");
	(*v0).x = -((*v0).x);
	nimln(499, "basic2d.nim");
	(*v0).y = -((*v0).y);
	popFrame();
}

static N_INLINE(void, rotate270_129485_2328089844)(Vector2d129025* v0) {
	NF LOC1;
	nimfr("rotate270", "basic2d.nim")
	nimln(504, "basic2d.nim");
	LOC1 = (NF)0;
	LOC1 = (*v0).x;
	(*v0).x = (*v0).y;
	(*v0).y = LOC1;
	nimln(505, "basic2d.nim");
	(*v0).y = -((*v0).y);
	popFrame();
}

N_NIMCALL(void, rotate_129499_2328089844)(Vector2d129025* v0, NF rad0) {
	NF s0;
	NF c0;
	NF newx0;
	nimfr("rotate", "basic2d.nim")
	nimln(510, "basic2d.nim");
	s0 = sin(rad0);
	nimln(511, "basic2d.nim");
	c0 = cos(rad0);
	nimln(512, "basic2d.nim");
	newx0 = ((NF)(((NF)(c0) * (NF)((*v0).x))) - (NF)(((NF)(s0) * (NF)((*v0).y))));
	nimln(513, "basic2d.nim");
	(*v0).y = ((NF)(((NF)(c0) * (NF)((*v0).y))) + (NF)(((NF)(s0) * (NF)((*v0).x))));
	nimln(514, "basic2d.nim");
	(*v0).x = newx0;
	popFrame();
}

static N_INLINE(void, scale_129507_2328089844)(Vector2d129025* v0, NF fac0) {
	nimfr("scale", "basic2d.nim")
	nimln(518, "basic2d.nim");
	HEX2AHEX3D_113691_1689653243((&(*v0).x), fac0);
	nimln(519, "basic2d.nim");
	HEX2AHEX3D_113691_1689653243((&(*v0).y), fac0);
	popFrame();
}

static N_INLINE(void, stretch_129532_2328089844)(Vector2d129025* v0, NF facx0, NF facy0) {
	nimfr("stretch", "basic2d.nim")
	nimln(524, "basic2d.nim");
	HEX2AHEX3D_113691_1689653243((&(*v0).x), facx0);
	nimln(525, "basic2d.nim");
	HEX2AHEX3D_113691_1689653243((&(*v0).y), facy0);
	popFrame();
}

N_NIMCALL(void, mirror_129558_2328089844)(Vector2d129025* v0, Vector2d129025 mirrvec0) {
	NF sqx0;
	NF sqy0;
	NF nd0;
	NF xy20;
	NF sqd0;
	NF newx0;
	nimfr("mirror", "basic2d.nim")
{	nimln(530, "basic2d.nim");
	sqx0 = ((NF)(mirrvec0.x) * (NF)(mirrvec0.x));
	nimln(531, "basic2d.nim");
	sqy0 = ((NF)(mirrvec0.y) * (NF)(mirrvec0.y));
	nimln(532, "basic2d.nim");
	nd0 = ((NF)(1.0000000000000000e+00) / (NF)(((NF)(sqx0) + (NF)(sqy0))));
	nimln(533, "basic2d.nim");
	xy20 = ((NF)(((NF)(((NF)(mirrvec0.x) * (NF)(mirrvec0.y))) * (NF)(2.0000000000000000e+00))) * (NF)(nd0));
	nimln(534, "basic2d.nim");
	sqd0 = ((NF)(nd0) * (NF)(((NF)(sqx0) - (NF)(sqy0))));
	nimln(536, "basic2d.nim");
	{
		NIM_BOOL LOC3;
		LOC3 = (NIM_BOOL)0;
		LOC3 = (nd0 == INF);
		if (LOC3) goto LA4;
		LOC3 = (nd0 == -INF);
		LA4: ;
		if (!LOC3) goto LA5;
		nimln(537, "basic2d.nim");
		goto BeforeRet;
	}
	LA5: ;
	nimln(539, "basic2d.nim");
	newx0 = ((NF)(((NF)(xy20) * (NF)((*v0).y))) + (NF)(((NF)(sqd0) * (NF)((*v0).x))));
	nimln(540, "basic2d.nim");
	(*v0).y = ((NF)(((NF)((*v0).x) * (NF)(xy20))) - (NF)(((NF)(sqd0) * (NF)((*v0).y))));
	nimln(541, "basic2d.nim");
	(*v0).x = newx0;
	}BeforeRet: ;
	popFrame();
}

N_NIMCALL(Vector2d129025, HEX2D_129573_2328089844)(Vector2d129025 v0) {
	Vector2d129025 result0;
	nimfr("-", "basic2d.nim")
	memset((void*)(&result0), 0, sizeof(result0));
	nimln(546, "basic2d.nim");
	result0.x = -(v0.x);
	nimln(547, "basic2d.nim");
	result0.y = -(v0.y);
	popFrame();
	return result0;
}

static N_INLINE(Vector2d129025, HEX2B_129589_2328089844)(Vector2d129025 a_129578_2328089844, Vector2d129025 b_129580_2328089844) {
	Vector2d129025 result0;
	nimfr("+", "basic2d.nim")
	nimln(121, "basic2d.nim");
	result0 = vector2d_129047_2328089844(((NF)(a_129578_2328089844.x) + (NF)(b_129580_2328089844.x)), ((NF)(a_129578_2328089844.y) + (NF)(b_129580_2328089844.y)));
	popFrame();
	return result0;
}

static N_INLINE(Vector2d129025, HEX2B_129592_2328089844)(Vector2d129025 a_129582_2328089844, NF b_129584_2328089844) {
	Vector2d129025 result0;
	nimfr("+", "basic2d.nim")
	nimln(122, "basic2d.nim");
	result0 = vector2d_129047_2328089844(((NF)(a_129582_2328089844.x) + (NF)(b_129584_2328089844)), ((NF)(a_129582_2328089844.y) + (NF)(b_129584_2328089844)));
	popFrame();
	return result0;
}

static N_INLINE(Vector2d129025, HEX2B_129595_2328089844)(NF a_129586_2328089844, Vector2d129025 b_129588_2328089844) {
	Vector2d129025 result0;
	nimfr("+", "basic2d.nim")
	nimln(123, "basic2d.nim");
	result0 = vector2d_129047_2328089844(((NF)(a_129586_2328089844) + (NF)(b_129588_2328089844.x)), ((NF)(a_129586_2328089844) + (NF)(b_129588_2328089844.y)));
	popFrame();
	return result0;
}

static N_INLINE(Vector2d129025, HEX2D_129610_2328089844)(Vector2d129025 a_129599_2328089844, Vector2d129025 b_129601_2328089844) {
	Vector2d129025 result0;
	nimfr("-", "basic2d.nim")
	nimln(121, "basic2d.nim");
	result0 = vector2d_129047_2328089844(((NF)(a_129599_2328089844.x) - (NF)(b_129601_2328089844.x)), ((NF)(a_129599_2328089844.y) - (NF)(b_129601_2328089844.y)));
	popFrame();
	return result0;
}

static N_INLINE(Vector2d129025, HEX2D_129613_2328089844)(Vector2d129025 a_129603_2328089844, NF b_129605_2328089844) {
	Vector2d129025 result0;
	nimfr("-", "basic2d.nim")
	nimln(122, "basic2d.nim");
	result0 = vector2d_129047_2328089844(((NF)(a_129603_2328089844.x) - (NF)(b_129605_2328089844)), ((NF)(a_129603_2328089844.y) - (NF)(b_129605_2328089844)));
	popFrame();
	return result0;
}

static N_INLINE(Vector2d129025, HEX2D_129616_2328089844)(NF a_129607_2328089844, Vector2d129025 b_129609_2328089844) {
	Vector2d129025 result0;
	nimfr("-", "basic2d.nim")
	nimln(123, "basic2d.nim");
	result0 = vector2d_129047_2328089844(((NF)(a_129607_2328089844) - (NF)(b_129609_2328089844.x)), ((NF)(a_129607_2328089844) - (NF)(b_129609_2328089844.y)));
	popFrame();
	return result0;
}

static N_INLINE(Vector2d129025, HEX2A_129631_2328089844)(Vector2d129025 a_129620_2328089844, Vector2d129025 b_129622_2328089844) {
	Vector2d129025 result0;
	nimfr("*", "basic2d.nim")
	nimln(121, "basic2d.nim");
	result0 = vector2d_129047_2328089844(((NF)(a_129620_2328089844.x) * (NF)(b_129622_2328089844.x)), ((NF)(a_129620_2328089844.y) * (NF)(b_129622_2328089844.y)));
	popFrame();
	return result0;
}

static N_INLINE(Vector2d129025, HEX2A_129634_2328089844)(Vector2d129025 a_129624_2328089844, NF b_129626_2328089844) {
	Vector2d129025 result0;
	nimfr("*", "basic2d.nim")
	nimln(122, "basic2d.nim");
	result0 = vector2d_129047_2328089844(((NF)(a_129624_2328089844.x) * (NF)(b_129626_2328089844)), ((NF)(a_129624_2328089844.y) * (NF)(b_129626_2328089844)));
	popFrame();
	return result0;
}

static N_INLINE(Vector2d129025, HEX2A_129637_2328089844)(NF a_129628_2328089844, Vector2d129025 b_129630_2328089844) {
	Vector2d129025 result0;
	nimfr("*", "basic2d.nim")
	nimln(123, "basic2d.nim");
	result0 = vector2d_129047_2328089844(((NF)(a_129628_2328089844) * (NF)(b_129630_2328089844.x)), ((NF)(a_129628_2328089844) * (NF)(b_129630_2328089844.y)));
	popFrame();
	return result0;
}

static N_INLINE(Vector2d129025, HEX2F_129652_2328089844)(Vector2d129025 a_129641_2328089844, Vector2d129025 b_129643_2328089844) {
	Vector2d129025 result0;
	nimfr("/", "basic2d.nim")
	nimln(121, "basic2d.nim");
	result0 = vector2d_129047_2328089844(((NF)(a_129641_2328089844.x) / (NF)(b_129643_2328089844.x)), ((NF)(a_129641_2328089844.y) / (NF)(b_129643_2328089844.y)));
	popFrame();
	return result0;
}

static N_INLINE(Vector2d129025, HEX2F_129655_2328089844)(Vector2d129025 a_129645_2328089844, NF b_129647_2328089844) {
	Vector2d129025 result0;
	nimfr("/", "basic2d.nim")
	nimln(122, "basic2d.nim");
	result0 = vector2d_129047_2328089844(((NF)(a_129645_2328089844.x) / (NF)(b_129647_2328089844)), ((NF)(a_129645_2328089844.y) / (NF)(b_129647_2328089844)));
	popFrame();
	return result0;
}

static N_INLINE(Vector2d129025, HEX2F_129658_2328089844)(NF a_129649_2328089844, Vector2d129025 b_129651_2328089844) {
	Vector2d129025 result0;
	nimfr("/", "basic2d.nim")
	nimln(123, "basic2d.nim");
	result0 = vector2d_129047_2328089844(((NF)(a_129649_2328089844) / (NF)(b_129651_2328089844.x)), ((NF)(a_129649_2328089844) / (NF)(b_129651_2328089844.y)));
	popFrame();
	return result0;
}

static N_INLINE(void, HEX2BHEX3D_129669_2328089844)(Vector2d129025* a_129662_2328089844, Vector2d129025 b_129664_2328089844) {
	nimfr("+=", "basic2d.nim")
	nimln(127, "basic2d.nim");
	HEX2BHEX3D_113701_1689653243((&(*a_129662_2328089844).x), b_129664_2328089844.x);
	HEX2BHEX3D_113701_1689653243((&(*a_129662_2328089844).y), b_129664_2328089844.y);
	popFrame();
}

static N_INLINE(void, HEX2BHEX3D_129692_2328089844)(Vector2d129025* a_129666_2328089844, NF b_129668_2328089844) {
	nimfr("+=", "basic2d.nim")
	nimln(128, "basic2d.nim");
	HEX2BHEX3D_113701_1689653243((&(*a_129666_2328089844).x), b_129668_2328089844);
	HEX2BHEX3D_113701_1689653243((&(*a_129666_2328089844).y), b_129668_2328089844);
	popFrame();
}

static N_INLINE(void, HEX2DHEX3D_129727_1689653243)(NF* x0, NF y0) {
	nimfr("-=", "system.nim")
	nimln(3319, "system.nim");
	(*x0) = ((NF)((*x0)) - (NF)(y0));
	popFrame();
}

static N_INLINE(void, HEX2DHEX3D_129723_2328089844)(Vector2d129025* a_129716_2328089844, Vector2d129025 b_129718_2328089844) {
	nimfr("-=", "basic2d.nim")
	nimln(127, "basic2d.nim");
	HEX2DHEX3D_129727_1689653243((&(*a_129716_2328089844).x), b_129718_2328089844.x);
	HEX2DHEX3D_129727_1689653243((&(*a_129716_2328089844).y), b_129718_2328089844.y);
	popFrame();
}

static N_INLINE(void, HEX2DHEX3D_129746_2328089844)(Vector2d129025* a_129720_2328089844, NF b_129722_2328089844) {
	nimfr("-=", "basic2d.nim")
	nimln(128, "basic2d.nim");
	HEX2DHEX3D_129727_1689653243((&(*a_129720_2328089844).x), b_129722_2328089844);
	HEX2DHEX3D_129727_1689653243((&(*a_129720_2328089844).y), b_129722_2328089844);
	popFrame();
}

static N_INLINE(void, HEX2AHEX3D_129777_2328089844)(Vector2d129025* a_129770_2328089844, Vector2d129025 b_129772_2328089844) {
	nimfr("*=", "basic2d.nim")
	nimln(127, "basic2d.nim");
	HEX2AHEX3D_113691_1689653243((&(*a_129770_2328089844).x), b_129772_2328089844.x);
	HEX2AHEX3D_113691_1689653243((&(*a_129770_2328089844).y), b_129772_2328089844.y);
	popFrame();
}

static N_INLINE(void, HEX2AHEX3D_129800_2328089844)(Vector2d129025* a_129774_2328089844, NF b_129776_2328089844) {
	nimfr("*=", "basic2d.nim")
	nimln(128, "basic2d.nim");
	HEX2AHEX3D_113691_1689653243((&(*a_129774_2328089844).x), b_129776_2328089844);
	HEX2AHEX3D_113691_1689653243((&(*a_129774_2328089844).y), b_129776_2328089844);
	popFrame();
}

static N_INLINE(void, HEX2FHEX3D_129831_2328089844)(Vector2d129025* a_129824_2328089844, Vector2d129025 b_129826_2328089844) {
	nimfr("/=", "basic2d.nim")
	nimln(127, "basic2d.nim");
	HEX2FHEX3D_91059_1689653243((&(*a_129824_2328089844).x), b_129826_2328089844.x);
	HEX2FHEX3D_91059_1689653243((&(*a_129824_2328089844).y), b_129826_2328089844.y);
	popFrame();
}

static N_INLINE(void, HEX2FHEX3D_129836_2328089844)(Vector2d129025* a_129828_2328089844, NF b_129830_2328089844) {
	nimfr("/=", "basic2d.nim")
	nimln(128, "basic2d.nim");
	HEX2FHEX3D_91059_1689653243((&(*a_129828_2328089844).x), b_129830_2328089844);
	HEX2FHEX3D_91059_1689653243((&(*a_129828_2328089844).y), b_129830_2328089844);
	popFrame();
}

N_NIMCALL(NF, dot_129841_2328089844)(Vector2d129025 v10, Vector2d129025 v20) {
	NF result0;
	nimfr("dot", "basic2d.nim")
{	result0 = (NF)0;
	nimln(563, "basic2d.nim");
	result0 = ((NF)(((NF)(v10.x) * (NF)(v20.x))) + (NF)(((NF)(v10.y) * (NF)(v20.y))));
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result0;
}

N_NIMCALL(NF, cross_129846_2328089844)(Vector2d129025 v10, Vector2d129025 v20) {
	NF result0;
	nimfr("cross", "basic2d.nim")
{	result0 = (NF)0;
	nimln(569, "basic2d.nim");
	result0 = ((NF)(((NF)(v10.x) * (NF)(v20.y))) - (NF)(((NF)(v10.y) * (NF)(v20.x))));
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result0;
}

N_NIMCALL(NIM_BOOL, equals_129851_2328089844)(Vector2d129025 v10, Vector2d129025 v20, NF tol0) {
	NIM_BOOL result0;
	NIM_BOOL LOC1;
	nimfr("equals", "basic2d.nim")
{	result0 = (NIM_BOOL)0;
	nimln(573, "basic2d.nim");
	LOC1 = (NIM_BOOL)0;
	LOC1 = ((((NF)(v20.x) - (NF)(v10.x)) > 0? (((NF)(v20.x) - (NF)(v10.x))) : -(((NF)(v20.x) - (NF)(v10.x)))) <= tol0);
	if (!(LOC1)) goto LA2;
	LOC1 = ((((NF)(v20.y) - (NF)(v10.y)) > 0? (((NF)(v20.y) - (NF)(v10.y))) : -(((NF)(v20.y) - (NF)(v10.y)))) <= tol0);
	LA2: ;
	result0 = LOC1;
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result0;
}

N_NIMCALL(NIM_BOOL, HEX3DHEX7E_129857_2328089844)(Vector2d129025 v10, Vector2d129025 v20) {
	NIM_BOOL result0;
	nimfr("=~", "basic2d.nim")
	result0 = (NIM_BOOL)0;
	nimln(576, "basic2d.nim");
	nimln(578, "basic2d.nim");
	result0 = equals_129851_2328089844(v10, v20, 9.9999999999999995e-07);
	popFrame();
	return result0;
}

N_NIMCALL(NF, angleto_129862_2328089844)(Vector2d129025 v10, Vector2d129025 v20) {
	NF result0;
	Vector2d129025 nv10;
	Vector2d129025 nv20;
	NF LOC9;
	nimfr("angleTo", "basic2d.nim")
{	result0 = (NF)0;
	nimln(584, "basic2d.nim");
	nv10 = v10;
	nimln(585, "basic2d.nim");
	nv20 = v20;
	nimln(586, "basic2d.nim");
	{
		NIM_BOOL LOC3;
		NIM_BOOL LOC4;
		NIM_BOOL LOC6;
		LOC3 = (NIM_BOOL)0;
		LOC4 = (NIM_BOOL)0;
		LOC4 = trynormalize_129393_2328089844((&nv10));
		LOC3 = !(LOC4);
		if (LOC3) goto LA5;
		LOC6 = (NIM_BOOL)0;
		LOC6 = trynormalize_129393_2328089844((&nv20));
		LOC3 = !(LOC6);
		LA5: ;
		if (!LOC3) goto LA7;
		nimln(587, "basic2d.nim");
		result0 = 0.0;
		goto BeforeRet;
	}
	LA7: ;
	nimln(588, "basic2d.nim");
	LOC9 = (NF)0;
	LOC9 = dot_129841_2328089844(nv10, nv20);
	result0 = safearccos_129067_2328089844(LOC9);
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result0;
}

N_NIMCALL(NF, angleccw_129871_2328089844)(Vector2d129025 v10, Vector2d129025 v20) {
	NF result0;
	NF a0;
	nimfr("angleCCW", "basic2d.nim")
{	result0 = (NF)0;
	nimln(593, "basic2d.nim");
	a0 = angleto_129862_2328089844(v10, v20);
	nimln(594, "basic2d.nim");
	{
		NF LOC3;
		nimln(347, "system.nim");
		nimln(594, "basic2d.nim");
		LOC3 = (NF)0;
		LOC3 = cross_129846_2328089844(v10, v20);
		if (!(0.0 <= LOC3)) goto LA4;
		nimln(595, "basic2d.nim");
		result0 = a0;
		goto BeforeRet;
	}
	LA4: ;
	nimln(596, "basic2d.nim");
	result0 = ((NF)(6.2831853071795862e+00) - (NF)(a0));
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result0;
}

N_NIMCALL(NF, anglecw_129877_2328089844)(Vector2d129025 v10, Vector2d129025 v20) {
	NF result0;
	NF a0;
	nimfr("angleCW", "basic2d.nim")
{	result0 = (NF)0;
	nimln(601, "basic2d.nim");
	a0 = angleto_129862_2328089844(v10, v20);
	nimln(602, "basic2d.nim");
	{
		NF LOC3;
		LOC3 = (NF)0;
		LOC3 = cross_129846_2328089844(v10, v20);
		if (!(LOC3 <= 0.0)) goto LA4;
		nimln(603, "basic2d.nim");
		result0 = a0;
		goto BeforeRet;
	}
	LA4: ;
	nimln(604, "basic2d.nim");
	result0 = ((NF)(6.2831853071795862e+00) - (NF)(a0));
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result0;
}

N_NIMCALL(NF, turnangle_129883_2328089844)(Vector2d129025 v10, Vector2d129025 v20) {
	NF result0;
	NF a0;
	nimfr("turnAngle", "basic2d.nim")
{	result0 = (NF)0;
	nimln(609, "basic2d.nim");
	a0 = angleto_129862_2328089844(v10, v20);
	nimln(610, "basic2d.nim");
	{
		NF LOC3;
		LOC3 = (NF)0;
		LOC3 = cross_129846_2328089844(v10, v20);
		if (!(LOC3 <= 0.0)) goto LA4;
		nimln(611, "basic2d.nim");
		result0 = -(a0);
		goto BeforeRet;
	}
	LA4: ;
	nimln(612, "basic2d.nim");
	result0 = a0;
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result0;
}

N_NIMCALL(Vector2d129025, bisect_129889_2328089844)(Vector2d129025 v10, Vector2d129025 v20) {
	Vector2d129025 result0;
	NF vmag10;
	NF vmag20;
	NF x10;
	NF y10;
	NF x20;
	NF y20;
	nimfr("bisect", "basic2d.nim")
{	nimln(620, "basic2d.nim");
	vmag10 = len_129326_2328089844(v10);
	nimln(621, "basic2d.nim");
	vmag20 = len_129326_2328089844(v20);
	nimln(625, "basic2d.nim");
	{
		if (!(vmag10 == 0.0)) goto LA3;
		nimln(626, "basic2d.nim");
		{
			if (!(vmag20 == 0.0)) goto LA7;
			nimln(627, "basic2d.nim");
			result0 = Xaxis_129057_2328089844;
			goto BeforeRet;
		}
		LA7: ;
		nimln(628, "basic2d.nim");
		vmag10 = 1.0000000000000000e+00;
	}
	LA3: ;
	nimln(629, "basic2d.nim");
	{
		if (!(vmag20 == 0.0)) goto LA11;
		vmag20 = 1.0000000000000000e+00;
	}
	LA11: ;
	nimln(632, "basic2d.nim");
	x10 = ((NF)(v10.x) / (NF)(vmag10));
	nimln(633, "basic2d.nim");
	y10 = ((NF)(v10.y) / (NF)(vmag10));
	nimln(634, "basic2d.nim");
	x20 = ((NF)(v20.x) / (NF)(vmag20));
	nimln(635, "basic2d.nim");
	y20 = ((NF)(v20.y) / (NF)(vmag20));
	nimln(637, "basic2d.nim");
	result0.x = ((NF)(((NF)(x10) + (NF)(x20))) * (NF)(5.0000000000000000e-01));
	nimln(638, "basic2d.nim");
	result0.y = ((NF)(((NF)(y10) + (NF)(y20))) * (NF)(5.0000000000000000e-01));
	nimln(640, "basic2d.nim");
	{
		NIM_BOOL LOC15;
		LOC15 = (NIM_BOOL)0;
		LOC15 = trynormalize_129393_2328089844((&result0));
		if (!!(LOC15)) goto LA16;
		nimln(644, "basic2d.nim");
		result0.x = -(y10);
		nimln(645, "basic2d.nim");
		result0.y = x10;
	}
	LA16: ;
	}BeforeRet: ;
	popFrame();
	return result0;
}

static N_INLINE(Point2d129023, point2d_129051_2328089844)(NF x0, NF y0) {
	Point2d129023 result0;
	nimfr("point2d", "basic2d.nim")
	nimln(654, "basic2d.nim");
	result0.x = x0;
	nimln(655, "basic2d.nim");
	result0.y = y0;
	popFrame();
	return result0;
}

N_NIMCALL(NF, sqrdist_129908_2328089844)(Point2d129023 a0, Point2d129023 b0) {
	NF result0;
	NF dx0;
	NF dy0;
	nimfr("sqrDist", "basic2d.nim")
	result0 = (NF)0;
	nimln(659, "basic2d.nim");
	dx0 = ((NF)(b0.x) - (NF)(a0.x));
	nimln(660, "basic2d.nim");
	dy0 = ((NF)(b0.y) - (NF)(a0.y));
	nimln(661, "basic2d.nim");
	result0 = ((NF)(((NF)(dx0) * (NF)(dx0))) + (NF)(((NF)(dy0) * (NF)(dy0))));
	popFrame();
	return result0;
}

static N_INLINE(NF, dist_129915_2328089844)(Point2d129023 a0, Point2d129023 b0) {
	NF result0;
	NF LOC1;
	nimfr("dist", "basic2d.nim")
	result0 = (NF)0;
	nimln(665, "basic2d.nim");
	LOC1 = (NF)0;
	LOC1 = sqrdist_129908_2328089844(a0, b0);
	result0 = sqrt(LOC1);
	popFrame();
	return result0;
}

N_NIMCALL(NF, angle_129920_2328089844)(Point2d129023 a0, Point2d129023 b0) {
	NF result0;
	NF dx0;
	NF dy0;
	nimfr("angle", "basic2d.nim")
	result0 = (NF)0;
	nimln(669, "basic2d.nim");
	dx0 = ((NF)(b0.x) - (NF)(a0.x));
	nimln(670, "basic2d.nim");
	dy0 = ((NF)(b0.y) - (NF)(a0.y));
	nimln(671, "basic2d.nim");
	result0 = atan2(dy0, dx0);
	nimln(672, "basic2d.nim");
	{
		if (!(result0 < 0.0)) goto LA3;
		nimln(673, "basic2d.nim");
		HEX2BHEX3D_113701_1689653243((&result0), 6.2831853071795862e+00);
	}
	LA3: ;
	popFrame();
	return result0;
}

N_NIMCALL(NimStringDesc*, HEX24_129939_2328089844)(Point2d129023 p0) {
	NimStringDesc* result0;
	NimStringDesc* LOC1;
	nimfr("$", "basic2d.nim")
	result0 = (NimStringDesc*)0;
	nimln(677, "basic2d.nim");
	result0 = rtos_129063_2328089844(p0.x);
	nimln(678, "basic2d.nim");
	result0 = resizeString(result0, 1);
appendString(result0, ((NimStringDesc*) &TMP184));
	nimln(679, "basic2d.nim");
	LOC1 = (NimStringDesc*)0;
	LOC1 = rtos_129063_2328089844(p0.y);
	result0 = resizeString(result0, LOC1->Sup.len + 0);
appendString(result0, LOC1);
	popFrame();
	return result0;
}

static N_INLINE(Point2d129023, HEX26_129943_2328089844)(Point2d129023 p0, Matrix2d129021* t0) {
	Point2d129023 result0;
	nimfr("&", "basic2d.nim")
	nimln(688, "basic2d.nim");
	result0.x = ((NF)(((NF)(((NF)(p0.x) * (NF)((*t0).ax))) + (NF)(((NF)(p0.y) * (NF)((*t0).bx))))) + (NF)((*t0).tx));
	nimln(689, "basic2d.nim");
	result0.y = ((NF)(((NF)(((NF)(p0.x) * (NF)((*t0).ay))) + (NF)(((NF)(p0.y) * (NF)((*t0).by))))) + (NF)((*t0).ty));
	popFrame();
	return result0;
}

static N_INLINE(void, HEX26HEX3D_129948_2328089844)(Point2d129023* p0, Matrix2d129021* t0) {
	NF newx0;
	nimfr("&=", "basic2d.nim")
	nimln(693, "basic2d.nim");
	newx0 = ((NF)(((NF)(((NF)((*p0).x) * (NF)((*t0).ax))) + (NF)(((NF)((*p0).y) * (NF)((*t0).bx))))) + (NF)((*t0).tx));
	nimln(694, "basic2d.nim");
	(*p0).y = ((NF)(((NF)(((NF)((*p0).x) * (NF)((*t0).ay))) + (NF)(((NF)((*p0).y) * (NF)((*t0).by))))) + (NF)((*t0).ty));
	nimln(695, "basic2d.nim");
	(*p0).x = newx0;
	popFrame();
}

static N_INLINE(void, transforminv_129954_2328089844)(Point2d129023* p0, Matrix2d129021* t0) {
	NF d0;
	NF newx0;
	nimfr("transformInv", "basic2d.nim")
	nimln(706, "basic2d.nim");
	d0 = determinant_129257_2328089844(t0);
	nimln(707, "basic2d.nim");
	{
		Divbyzeroerror3438* e_129963_2328089844;
		NimStringDesc* LOC5;
		if (!(d0 == 0.0)) goto LA3;
		e_129963_2328089844 = (Divbyzeroerror3438*)0;
		nimln(2514, "system.nim");
		e_129963_2328089844 = (Divbyzeroerror3438*) newObj((&NTI24493), sizeof(Divbyzeroerror3438));
		(*e_129963_2328089844).Sup.Sup.Sup.m_type = (&NTI3438);
		nimln(2515, "system.nim");
		LOC5 = (NimStringDesc*)0;
		LOC5 = (*e_129963_2328089844).Sup.Sup.message; (*e_129963_2328089844).Sup.Sup.message = copyStringRC1(((NimStringDesc*) &TMP185));
		if (LOC5) nimGCunrefNoCycle(LOC5);
		nimln(708, "basic2d.nim");
		raiseException((Exception*)e_129963_2328089844, "DivByZeroError");
	}
	LA3: ;
	nimln(710, "basic2d.nim");
	newx0 = ((NF)(((NF)(((NF)(((NF)(((NF)((*t0).bx) * (NF)((*t0).ty))) - (NF)(((NF)((*t0).by) * (NF)((*t0).tx))))) + (NF)(((NF)((*p0).x) * (NF)((*t0).by))))) - (NF)(((NF)((*p0).y) * (NF)((*t0).bx))))) / (NF)(d0));
	nimln(711, "basic2d.nim");
	(*p0).y = ((NF)(-(((NF)(((NF)(((NF)(((NF)((*t0).ax) * (NF)((*t0).ty))) - (NF)(((NF)((*t0).ay) * (NF)((*t0).tx))))) + (NF)(((NF)((*p0).x) * (NF)((*t0).ay))))) - (NF)(((NF)((*p0).y) * (NF)((*t0).ax)))))) / (NF)(d0));
	nimln(712, "basic2d.nim");
	(*p0).x = newx0;
	popFrame();
}

static N_INLINE(Point2d129023, HEX2B_129975_2328089844)(Point2d129023 p0, Vector2d129025 v0) {
	Point2d129023 result0;
	nimfr("+", "basic2d.nim")
	nimln(718, "basic2d.nim");
	result0.x = ((NF)(p0.x) + (NF)(v0.x));
	nimln(719, "basic2d.nim");
	result0.y = ((NF)(p0.y) + (NF)(v0.y));
	popFrame();
	return result0;
}

static N_INLINE(void, HEX2BHEX3D_129980_2328089844)(Point2d129023* p0, Vector2d129025 v0) {
	nimfr("+=", "basic2d.nim")
	nimln(723, "basic2d.nim");
	HEX2BHEX3D_113701_1689653243((&(*p0).x), v0.x);
	nimln(724, "basic2d.nim");
	HEX2BHEX3D_113701_1689653243((&(*p0).y), v0.y);
	popFrame();
}

static N_INLINE(Point2d129023, HEX2D_130005_2328089844)(Point2d129023 p0, Vector2d129025 v0) {
	Point2d129023 result0;
	nimfr("-", "basic2d.nim")
	nimln(729, "basic2d.nim");
	result0.x = ((NF)(p0.x) - (NF)(v0.x));
	nimln(730, "basic2d.nim");
	result0.y = ((NF)(p0.y) - (NF)(v0.y));
	popFrame();
	return result0;
}

static N_INLINE(Vector2d129025, HEX2D_130010_2328089844)(Point2d129023 p10, Point2d129023 p20) {
	Vector2d129025 result0;
	nimfr("-", "basic2d.nim")
	nimln(734, "basic2d.nim");
	result0.x = ((NF)(p10.x) - (NF)(p20.x));
	nimln(735, "basic2d.nim");
	result0.y = ((NF)(p10.y) - (NF)(p20.y));
	popFrame();
	return result0;
}

static N_INLINE(void, HEX2DHEX3D_130015_2328089844)(Point2d129023* p0, Vector2d129025 v0) {
	nimfr("-=", "basic2d.nim")
	nimln(739, "basic2d.nim");
	HEX2DHEX3D_129727_1689653243((&(*p0).x), v0.x);
	nimln(740, "basic2d.nim");
	HEX2DHEX3D_129727_1689653243((&(*p0).y), v0.y);
	popFrame();
}

static N_INLINE(NIM_BOOL, equals_130040_2328089844)(Point2d129023 p10, Point2d129023 p20, NF tol0) {
	NIM_BOOL result0;
	NIM_BOOL LOC1;
	nimfr("equals", "basic2d.nim")
{	result0 = (NIM_BOOL)0;
	nimln(744, "basic2d.nim");
	LOC1 = (NIM_BOOL)0;
	LOC1 = ((((NF)(p20.x) - (NF)(p10.x)) > 0? (((NF)(p20.x) - (NF)(p10.x))) : -(((NF)(p20.x) - (NF)(p10.x)))) <= tol0);
	if (!(LOC1)) goto LA2;
	LOC1 = ((((NF)(p20.y) - (NF)(p10.y)) > 0? (((NF)(p20.y) - (NF)(p10.y))) : -(((NF)(p20.y) - (NF)(p10.y)))) <= tol0);
	LA2: ;
	result0 = LOC1;
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result0;
}

static N_INLINE(NIM_BOOL, HEX3DHEX7E_130046_2328089844)(Point2d129023 p10, Point2d129023 p20) {
	NIM_BOOL result0;
	nimfr("=~", "basic2d.nim")
	result0 = (NIM_BOOL)0;
	nimln(747, "basic2d.nim");
	nimln(749, "basic2d.nim");
	result0 = equals_130040_2328089844(p10, p20, 9.9999999999999995e-07);
	popFrame();
	return result0;
}

N_NIMCALL(Point2d129023, polar_130051_2328089844)(Point2d129023 p0, NF ang0, NF dist0) {
	Point2d129023 result0;
	NF LOC1;
	NF LOC2;
	nimfr("polar", "basic2d.nim")
	nimln(753, "basic2d.nim");
	LOC1 = (NF)0;
	LOC1 = cos(ang0);
	result0.x = ((NF)(p0.x) + (NF)(((NF)(LOC1) * (NF)(dist0))));
	nimln(754, "basic2d.nim");
	LOC2 = (NF)0;
	LOC2 = sin(ang0);
	result0.y = ((NF)(p0.y) + (NF)(((NF)(LOC2) * (NF)(dist0))));
	popFrame();
	return result0;
}

N_NIMCALL(void, rotate_130057_2328089844)(Point2d129023* p0, NF rad0) {
	NF c0;
	NF s0;
	NF newx0;
	nimfr("rotate", "basic2d.nim")
	nimln(759, "basic2d.nim");
	c0 = cos(rad0);
	nimln(760, "basic2d.nim");
	s0 = sin(rad0);
	nimln(761, "basic2d.nim");
	newx0 = ((NF)(((NF)((*p0).x) * (NF)(c0))) - (NF)(((NF)((*p0).y) * (NF)(s0))));
	nimln(762, "basic2d.nim");
	(*p0).y = ((NF)(((NF)((*p0).y) * (NF)(c0))) + (NF)(((NF)((*p0).x) * (NF)(s0))));
	nimln(763, "basic2d.nim");
	(*p0).x = newx0;
	popFrame();
}

N_NIMCALL(void, rotate_130065_2328089844)(Point2d129023* p0, NF rad0, Point2d129023 org0) {
	NF c0;
	NF s0;
	NF newx0;
	nimfr("rotate", "basic2d.nim")
	nimln(769, "basic2d.nim");
	c0 = cos(rad0);
	nimln(770, "basic2d.nim");
	s0 = sin(rad0);
	nimln(771, "basic2d.nim");
	newx0 = ((NF)(((NF)(((NF)(((NF)((*p0).x) - (NF)(org0.x))) * (NF)(c0))) - (NF)(((NF)(((NF)((*p0).y) - (NF)(org0.y))) * (NF)(s0))))) + (NF)(org0.x));
	nimln(772, "basic2d.nim");
	(*p0).y = ((NF)(((NF)(((NF)(((NF)((*p0).y) - (NF)(org0.y))) * (NF)(c0))) + (NF)(((NF)(((NF)((*p0).x) - (NF)(org0.x))) * (NF)(s0))))) + (NF)(org0.y));
	nimln(773, "basic2d.nim");
	(*p0).x = newx0;
	popFrame();
}

static N_INLINE(void, scale_130074_2328089844)(Point2d129023* p0, NF fac0) {
	nimfr("scale", "basic2d.nim")
	nimln(777, "basic2d.nim");
	HEX2AHEX3D_113691_1689653243((&(*p0).x), fac0);
	nimln(778, "basic2d.nim");
	HEX2AHEX3D_113691_1689653243((&(*p0).y), fac0);
	popFrame();
}

static N_INLINE(void, scale_130099_2328089844)(Point2d129023* p0, NF fac0, Point2d129023 org0) {
	nimfr("scale", "basic2d.nim")
	nimln(782, "basic2d.nim");
	(*p0).x = ((NF)(((NF)(((NF)((*p0).x) - (NF)(org0.x))) * (NF)(fac0))) + (NF)(org0.x));
	nimln(783, "basic2d.nim");
	(*p0).y = ((NF)(((NF)(((NF)((*p0).y) - (NF)(org0.y))) * (NF)(fac0))) + (NF)(org0.y));
	popFrame();
}

static N_INLINE(void, stretch_130105_2328089844)(Point2d129023* p0, NF facx0, NF facy0) {
	nimfr("stretch", "basic2d.nim")
	nimln(788, "basic2d.nim");
	HEX2AHEX3D_113691_1689653243((&(*p0).x), facx0);
	nimln(789, "basic2d.nim");
	HEX2AHEX3D_113691_1689653243((&(*p0).y), facy0);
	popFrame();
}

static N_INLINE(void, stretch_130131_2328089844)(Point2d129023* p0, NF facx0, NF facy0, Point2d129023 org0) {
	nimfr("stretch", "basic2d.nim")
	nimln(794, "basic2d.nim");
	(*p0).x = ((NF)(((NF)(((NF)((*p0).x) - (NF)(org0.x))) * (NF)(facx0))) + (NF)(org0.x));
	nimln(795, "basic2d.nim");
	(*p0).y = ((NF)(((NF)(((NF)((*p0).y) - (NF)(org0.y))) * (NF)(facy0))) + (NF)(org0.y));
	popFrame();
}

static N_INLINE(void, move_130138_2328089844)(Point2d129023* p0, NF dx0, NF dy0) {
	nimfr("move", "basic2d.nim")
	nimln(799, "basic2d.nim");
	HEX2BHEX3D_113701_1689653243((&(*p0).x), dx0);
	nimln(800, "basic2d.nim");
	HEX2BHEX3D_113701_1689653243((&(*p0).y), dy0);
	popFrame();
}

static N_INLINE(void, move_130164_2328089844)(Point2d129023* p0, Vector2d129025 v0) {
	nimfr("move", "basic2d.nim")
	nimln(804, "basic2d.nim");
	HEX2BHEX3D_113701_1689653243((&(*p0).x), v0.x);
	nimln(805, "basic2d.nim");
	HEX2BHEX3D_113701_1689653243((&(*p0).y), v0.y);
	popFrame();
}

N_NIMCALL(NF, sgnarea_130189_2328089844)(Point2d129023 a0, Point2d129023 b0, Point2d129023 c0) {
	NF result0;
	nimfr("sgnArea", "basic2d.nim")
{	result0 = (NF)0;
	nimln(812, "basic2d.nim");
	result0 = ((NF)(((NF)(((NF)(((NF)(b0.x) - (NF)(c0.x))) * (NF)(((NF)(b0.y) - (NF)(a0.y))))) - (NF)(((NF)(((NF)(b0.y) - (NF)(c0.y))) * (NF)(((NF)(b0.x) - (NF)(a0.x))))))) * (NF)(5.0000000000000000e-01));
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result0;
}

N_NIMCALL(NF, area_130195_2328089844)(Point2d129023 a0, Point2d129023 b0, Point2d129023 c0) {
	NF result0;
	NF LOC1;
	nimfr("area", "basic2d.nim")
{	result0 = (NF)0;
	nimln(816, "basic2d.nim");
	LOC1 = (NF)0;
	LOC1 = sgnarea_130189_2328089844(a0, b0, c0);
	result0 = (LOC1 > 0? (LOC1) : -(LOC1));
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result0;
}

static N_INLINE(NI, addInt)(NI a0, NI b0) {
	NI result0;
{	result0 = (NI)0;
	result0 = (NI)((NU64)(a0) + (NU64)(b0));
	{
		NIM_BOOL LOC3;
		LOC3 = (NIM_BOOL)0;
		LOC3 = (((NI) 0) <= (NI)(result0 ^ a0));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result0 ^ b0));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result0;
}

N_NIMCALL(Point2d129023, closestpoint_130201_2328089844)(Point2d129023 p0, Point2d129023* pts0, NI pts0Len0) {
	Point2d129023 result0;
	NI bestidx0;
	NF bestdist0;
	NF curdist0;
	nimfr("closestPoint", "basic2d.nim")
	memset((void*)(&result0), 0, sizeof(result0));
	nimln(821, "basic2d.nim");
	{
		if (!!((((NI) 0) < pts0Len0))) goto LA3;
		failedassertimpl_91239_1689653243(((NimStringDesc*) &TMP188));
	}
	LA3: ;
	nimln(824, "basic2d.nim");
	bestidx0 = ((NI) 0);
	nimln(825, "basic2d.nim");
	if ((NU)(((NI) 0)) >= (NU)(pts0Len0)) raiseIndexError();
	bestdist0 = sqrdist_129908_2328089844(p0, pts0[((NI) 0)]);
	curdist0 = (NF)0;
	{
		NI idx_130413_2328089844;
		NI HEX3Atmp_130416_2328089844;
		NI res_130419_2328089844;
		idx_130413_2328089844 = (NI)0;
		HEX3Atmp_130416_2328089844 = (NI)0;
		nimln(828, "basic2d.nim");
		HEX3Atmp_130416_2328089844 = (pts0Len0-1);
		nimln(1875, "system.nim");
		res_130419_2328089844 = ((NI) 1);
		{
			nimln(1876, "system.nim");
			while (1) {
				NI TMP189;
				if (!(res_130419_2328089844 <= HEX3Atmp_130416_2328089844)) goto LA7;
				nimln(1877, "system.nim");
				idx_130413_2328089844 = res_130419_2328089844;
				nimln(829, "basic2d.nim");
				if ((NU)(idx_130413_2328089844) >= (NU)(pts0Len0)) raiseIndexError();
				curdist0 = sqrdist_129908_2328089844(p0, pts0[idx_130413_2328089844]);
				nimln(830, "basic2d.nim");
				{
					if (!(curdist0 < bestdist0)) goto LA10;
					nimln(831, "basic2d.nim");
					bestidx0 = idx_130413_2328089844;
					nimln(832, "basic2d.nim");
					bestdist0 = curdist0;
				}
				LA10: ;
				nimln(1896, "system.nim");
				TMP189 = addInt(res_130419_2328089844, ((NI) 1));
				res_130419_2328089844 = (NI)(TMP189);
			} LA7: ;
		}
	}
	nimln(834, "basic2d.nim");
	if ((NU)(bestidx0) >= (NU)(pts0Len0)) raiseIndexError();
	result0 = pts0[bestidx0];
	popFrame();
	return result0;
}

N_NIMCALL(NF, normangle_130423_2328089844)(NF ang0) {
	NF result0;
	nimfr("normAngle", "basic2d.nim")
{	result0 = (NF)0;
	nimln(844, "basic2d.nim");
	{
		NIM_BOOL LOC3;
		LOC3 = (NIM_BOOL)0;
		nimln(347, "system.nim");
		LOC3 = (0.0 <= ang0);
		if (!(LOC3)) goto LA4;
		nimln(844, "basic2d.nim");
		LOC3 = (ang0 < 6.2831853071795862e+00);
		LA4: ;
		if (!LOC3) goto LA5;
		nimln(845, "basic2d.nim");
		result0 = ang0;
		goto BeforeRet;
	}
	LA5: ;
	nimln(847, "basic2d.nim");
	result0 = mod_130428_1009420244(ang0, 6.2831853071795862e+00);
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result0;
}

static N_INLINE(NF, degtorad_130436_2328089844)(NF deg0) {
	NF result0;
	nimfr("degToRad", "basic2d.nim")
	result0 = (NF)0;
	nimln(850, "basic2d.nim");
	nimln(851, "basic2d.nim");
	result0 = ((NF)(deg0) / (NF)(5.7295779513082323e+01));
	popFrame();
	return result0;
}

static N_INLINE(NF, radtodeg_130440_2328089844)(NF rad0) {
	NF result0;
	nimfr("radToDeg", "basic2d.nim")
	result0 = (NF)0;
	nimln(854, "basic2d.nim");
	nimln(855, "basic2d.nim");
	result0 = ((NF)(rad0) * (NF)(5.7295779513082323e+01));
	popFrame();
	return result0;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_basic2dInit000)(void) {
	nimfr("basic2d", "basic2d.nim")
	nimln(95, "basic2d.nim");
	Idmatrix_129055_2328089844 = matrix2d_129039_2328089844(1.0000000000000000e+00, 0.0, 0.0, 1.0000000000000000e+00, 0.0, 0.0);
	nimln(97, "basic2d.nim");
	Origo_129056_2328089844 = point2d_129051_2328089844(0.0, 0.0);
	nimln(99, "basic2d.nim");
	Xaxis_129057_2328089844 = vector2d_129047_2328089844(1.0000000000000000e+00, 0.0);
	nimln(101, "basic2d.nim");
	Yaxis_129058_2328089844 = vector2d_129047_2328089844(0.0, 1.0000000000000000e+00);
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_basic2dDatInit000)(void) {
static TNimNode* TMP191[2];
static TNimNode* TMP192[2];
static TNimNode TMP182[6];
NTI129023.size = sizeof(Point2d129023);
NTI129023.kind = 18;
NTI129023.base = 0;
NTI129023.flags = 3;
TMP191[0] = &TMP182[1];
TMP182[1].kind = 1;
TMP182[1].offset = offsetof(Point2d129023, x);
TMP182[1].typ = (&NTI124);
TMP182[1].name = "x";
TMP191[1] = &TMP182[2];
TMP182[2].kind = 1;
TMP182[2].offset = offsetof(Point2d129023, y);
TMP182[2].typ = (&NTI124);
TMP182[2].name = "y";
TMP182[0].len = 2; TMP182[0].kind = 2; TMP182[0].sons = &TMP191[0];
NTI129023.node = &TMP182[0];
NTI129025.size = sizeof(Vector2d129025);
NTI129025.kind = 18;
NTI129025.base = 0;
NTI129025.flags = 3;
TMP192[0] = &TMP182[4];
TMP182[4].kind = 1;
TMP182[4].offset = offsetof(Vector2d129025, x);
TMP182[4].typ = (&NTI124);
TMP182[4].name = "x";
TMP192[1] = &TMP182[5];
TMP182[5].kind = 1;
TMP182[5].offset = offsetof(Vector2d129025, y);
TMP182[5].typ = (&NTI124);
TMP182[5].name = "y";
TMP182[3].len = 2; TMP182[3].kind = 2; TMP182[3].sons = &TMP192[0];
NTI129025.node = &TMP182[3];
}

