/* Generated by Nim Compiler v0.14.2 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/home/primat/programs/nim-0.14.2/lib -o /home/primat/projects/tests/nim/game_1/nimcache/stdlib_strutils.o /home/primat/projects/tests/nim/game_1/nimcache/stdlib_strutils.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <stdio.h>
typedef struct Slice90651 Slice90651;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
struct  Slice90651  {
NI a;
NI b;
};
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NU8 Floatformatmode113202;
typedef NIM_CHAR TY113408[6];
typedef NIM_CHAR TY113412[2501];
typedef NIM_CHAR TY113404[3];
static N_INLINE(NIM_BOOL, contains_113475_1689653243)(NIM_CHAR* a0, NI a0Len0, NIM_CHAR item0);
static N_INLINE(NI, find_113485_1689653243)(NIM_CHAR* a0, NI a0Len0, NIM_CHAR item0);
N_NOINLINE(void, raiseIndexError)(void);
static N_INLINE(NI, addInt)(NI a0, NI b0);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(void, nimFrame)(TFrame* s0);
N_NOINLINE(void, stackoverflow_22401_1689653243)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(NIM_BOOL, contains_113650_1689653243)(Slice90651 s0, NI value0);
N_NIMCALL(NF, round_113661_1009420244)(NF x0, NI places0);
static N_INLINE(void, HEX2AHEX3D_113691_1689653243)(NF* x0, NF y0);
static N_INLINE(void, HEX2BHEX3D_113701_1689653243)(NF* x0, NF y0);
N_NIMCALL(NimStringDesc*, nsuformatBiggestFloat)(NF f0, Floatformatmode113202 format0, NI precision0, NIM_CHAR decimalsep0);
N_NIMCALL(NimStringDesc*, mnewString)(NI len0);
N_NIMCALL(NimStringDesc*, mnewString)(NI len0);
NIM_CONST TY113404 floatformattochar_113401_4286263276 = {103,
102,
101}
;
extern TFrame* frameptr_19636_1689653243;

static N_INLINE(NI, addInt)(NI a0, NI b0) {
	NI result0;
{	result0 = (NI)0;
	result0 = (NI)((NU64)(a0) + (NU64)(b0));
	{
		NIM_BOOL LOC3;
		LOC3 = (NIM_BOOL)0;
		LOC3 = (((NI) 0) <= (NI)(result0 ^ a0));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result0 ^ b0));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result0;
}

static N_INLINE(void, nimFrame)(TFrame* s0) {
	NI LOC1;
	LOC1 = (NI)0;
	{
		if (!(frameptr_19636_1689653243 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_19636_1689653243).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s0).calldepth = ((NI16) (LOC1));
	(*s0).prev = frameptr_19636_1689653243;
	frameptr_19636_1689653243 = s0;
	{
		if (!((*s0).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_22401_1689653243();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_19636_1689653243 = (*frameptr_19636_1689653243).prev;
}

static N_INLINE(NI, find_113485_1689653243)(NIM_CHAR* a0, NI a0Len0, NIM_CHAR item0) {
	NI result0;
	nimfr("find", "system.nim")
{	result0 = (NI)0;
	{
		NIM_CHAR i_113519_1689653243;
		NI i_113532_1689653243;
		i_113519_1689653243 = (NIM_CHAR)0;
		nimln(1966, "system.nim");
		i_113532_1689653243 = ((NI) 0);
		{
			nimln(1967, "system.nim");
			while (1) {
				NI TMP172;
				NI TMP173;
				if (!(i_113532_1689653243 < a0Len0)) goto LA3;
				nimln(1968, "system.nim");
				if ((NU)(i_113532_1689653243) >= (NU)(a0Len0)) raiseIndexError();
				i_113519_1689653243 = a0[i_113532_1689653243];
				nimln(2191, "system.nim");
				{
					if (!((NU8)(i_113519_1689653243) == (NU8)(item0))) goto LA6;
					goto BeforeRet;
				}
				LA6: ;
				nimln(2192, "system.nim");
				TMP172 = addInt(result0, ((NI) 1));
				result0 = (NI)(TMP172);
				nimln(1969, "system.nim");
				TMP173 = addInt(i_113532_1689653243, ((NI) 1));
				i_113532_1689653243 = (NI)(TMP173);
			} LA3: ;
		}
	}
	nimln(2193, "system.nim");
	result0 = ((NI) -1);
	}BeforeRet: ;
	popFrame();
	return result0;
}

static N_INLINE(NIM_BOOL, contains_113475_1689653243)(NIM_CHAR* a0, NI a0Len0, NIM_CHAR item0) {
	NIM_BOOL result0;
	NI LOC1;
	nimfr("contains", "system.nim")
{	result0 = (NIM_BOOL)0;
	nimln(2198, "system.nim");
	nimln(346, "system.nim");
	nimln(347, "system.nim");
	nimln(2198, "system.nim");
	LOC1 = (NI)0;
	LOC1 = find_113485_1689653243(a0, a0Len0, item0);
	result0 = (((NI) 0) <= LOC1);
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result0;
}

static N_INLINE(NIM_BOOL, contains_113650_1689653243)(Slice90651 s0, NI value0) {
	NIM_BOOL result0;
	NIM_BOOL LOC1;
	nimfr("contains", "system.nim")
	result0 = (NIM_BOOL)0;
	nimln(1093, "system.nim");
	LOC1 = (NIM_BOOL)0;
	LOC1 = (((NI) (s0.a)) <= ((NI) (value0)));
	if (!(LOC1)) goto LA2;
	LOC1 = (((NI) (value0)) <= ((NI) (s0.b)));
	LA2: ;
	result0 = LOC1;
	popFrame();
	return result0;
}

static N_INLINE(void, HEX2AHEX3D_113691_1689653243)(NF* x0, NF y0) {
	nimfr("*=", "system.nim")
	nimln(3324, "system.nim");
	(*x0) = ((NF)((*x0)) * (NF)(y0));
	popFrame();
}

static N_INLINE(void, HEX2BHEX3D_113701_1689653243)(NF* x0, NF y0) {
	nimfr("+=", "system.nim")
	nimln(3314, "system.nim");
	(*x0) = ((NF)((*x0)) + (NF)(y0));
	popFrame();
}

N_NIMCALL(NimStringDesc*, nsuformatBiggestFloat)(NF f0, Floatformatmode113202 format0, NI precision0, NIM_CHAR decimalsep0) {
	NimStringDesc* result0;
	TY113408 frmtstr0;
	TY113412 buf0;
	int L0;
	nimfr("formatBiggestFloat", "strutils.nim")
	result0 = (NimStringDesc*)0;
	L0 = (int)0;
	frmtstr0[(((NI) 0))- 0] = 37;
	{
		if (!(((NI) 0) < ((NI) (precision0)))) goto LA3;
		frmtstr0[(((NI) 1))- 0] = 35;
		frmtstr0[(((NI) 2))- 0] = 46;
		frmtstr0[(((NI) 3))- 0] = 42;
		frmtstr0[(((NI) 4))- 0] = floatformattochar_113401_4286263276[(format0)- 0];
		frmtstr0[(((NI) 5))- 0] = 0;
		L0 = sprintf(((NCSTRING) (buf0)), ((NCSTRING) (frmtstr0)), precision0, f0);
	}
	goto LA1;
	LA3: ;
	{
		frmtstr0[(((NI) 1))- 0] = floatformattochar_113401_4286263276[(format0)- 0];
		frmtstr0[(((NI) 2))- 0] = 0;
		L0 = sprintf(((NCSTRING) (buf0)), ((NCSTRING) (frmtstr0)), f0);
	}
	LA1: ;
	result0 = mnewString(((NI) (L0)));
	{
		int i_113435_4286263276;
		int i_113453_4286263276;
		i_113435_4286263276 = (int)0;
		i_113453_4286263276 = ((int) 0);
		{
			while (1) {
				if (!(i_113453_4286263276 < L0)) goto LA8;
				i_113435_4286263276 = i_113453_4286263276;
				{
					if (!(((NU8)(buf0[(i_113435_4286263276)- 0])) == ((NU8)(46)) || ((NU8)(buf0[(i_113435_4286263276)- 0])) == ((NU8)(44)))) goto LA11;
					result0->data[i_113435_4286263276] = decimalsep0;
				}
				goto LA9;
				LA11: ;
				{
					result0->data[i_113435_4286263276] = buf0[(i_113435_4286263276)- 0];
				}
				LA9: ;
				i_113453_4286263276 += ((NI) 1);
			} LA8: ;
		}
	}
	popFrame();
	return result0;
}

N_NIMCALL(NimStringDesc*, nsuformatFloat)(NF f0, Floatformatmode113202 format0, NI precision0, NIM_CHAR decimalsep0) {
	NimStringDesc* result0;
	nimfr("formatFloat", "strutils.nim")
	result0 = (NimStringDesc*)0;
	result0 = nsuformatBiggestFloat(f0, format0, precision0, decimalsep0);
	popFrame();
	return result0;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsInit000)(void) {
	nimfr("strutils", "strutils.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsDatInit000)(void) {
}

