/* Generated by Nim Compiler v0.14.2 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/home/primat/programs/nim-0.14.2/lib -o /home/primat/projects/tests/nim/game_1/nimcache/test.o /home/primat/projects/tests/nim/game_1/nimcache/test.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#include <setjmp.h>
typedef struct PlayerHEX3Aobjecttype131015 PlayerHEX3Aobjecttype131015;
typedef struct TextureptrHEX3Aobjecttype116609 TextureptrHEX3Aobjecttype116609;
typedef struct Point2d129023 Point2d129023;
typedef struct Vector2d129025 Vector2d129025;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct GameHEX3Aobjecttype131020 GameHEX3Aobjecttype131020;
typedef struct RendererptrHEX3Aobjecttype116607 RendererptrHEX3Aobjecttype116607;
typedef struct Cell48305 Cell48305;
typedef struct Cellseq48321 Cellseq48321;
typedef struct Gcheap50818 Gcheap50818;
typedef struct Gcstack50816 Gcstack50816;
typedef struct Memregion30486 Memregion30486;
typedef struct Smallchunk30440 Smallchunk30440;
typedef struct Llchunk30480 Llchunk30480;
typedef struct Bigchunk30442 Bigchunk30442;
typedef struct Intset30414 Intset30414;
typedef struct Trunk30410 Trunk30410;
typedef struct Avlnode30484 Avlnode30484;
typedef struct Gcstat50814 Gcstat50814;
typedef struct Cellset48317 Cellset48317;
typedef struct Pagedesc48313 Pagedesc48313;
typedef struct Event116155 Event116155;
typedef struct Keyboardeventobj116167 Keyboardeventobj116167;
typedef struct Keysym116261 Keysym116261;
typedef struct TY131101 TY131101;
typedef struct Rect116265 Rect116265;
typedef struct Point116263 Point116263;
typedef struct Sdlexception131002 Sdlexception131002;
typedef struct Exception Exception;
typedef struct TNimObject TNimObject;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct TSafePoint TSafePoint;
typedef struct WindowptrHEX3Aobjecttype116605 WindowptrHEX3Aobjecttype116605;
typedef struct Basechunk30438 Basechunk30438;
typedef struct Freecell30430 Freecell30430;
struct  Point2d129023  {
NF x;
NF y;
};
struct  Vector2d129025  {
NF x;
NF y;
};
struct  PlayerHEX3Aobjecttype131015  {
TextureptrHEX3Aobjecttype116609* texture;
Point2d129023 pos;
Vector2d129025 vel;
};
typedef NU8 Tnimkind3203;
typedef NU8 Tnimtypeflag3209Set;
typedef N_NIMCALL_PTR(void, TY3289) (void* p0, NI op0);
typedef N_NIMCALL_PTR(void*, TY3294) (void* p0);
struct  TNimType  {
NI size;
Tnimkind3203 kind;
Tnimtypeflag3209Set flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3289 marker;
TY3294 deepcopy;
};
typedef NU8 Tnimnodekind3205;
struct  TNimNode  {
Tnimnodekind3205 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef NIM_BOOL TY131023[6];
struct  GameHEX3Aobjecttype131020  {
TY131023 inputs;
RendererptrHEX3Aobjecttype116607* renderer;
PlayerHEX3Aobjecttype131015* player;
Vector2d129025 camera;
};
typedef N_CDECL_PTR(TextureptrHEX3Aobjecttype116609*, TY128622) (RendererptrHEX3Aobjecttype116607* renderer0, NCSTRING file0);
struct  Cell48305  {
NI refcount;
TNimType* typ;
};
struct  Cellseq48321  {
NI len;
NI cap;
Cell48305** d;
};
typedef Smallchunk30440* TY30501[512];
typedef Trunk30410* Trunkbuckets30412[256];
struct  Intset30414  {
Trunkbuckets30412 data;
};
struct  Memregion30486  {
NI minlargeobj;
NI maxlargeobj;
TY30501 freesmallchunks;
Llchunk30480* llmem;
NI currmem;
NI maxmem;
NI freemem;
NI lastsize;
Bigchunk30442* freechunkslist;
Intset30414 chunkstarts;
Avlnode30484* root;
Avlnode30484* deleted;
Avlnode30484* last;
Avlnode30484* freeavlnodes;
NIM_BOOL locked;
};
struct  Gcstat50814  {
NI stackscans;
NI cyclecollections;
NI maxthreshold;
NI maxstacksize;
NI maxstackcells;
NI cycletablesize;
NI64 maxpause;
};
struct  Cellset48317  {
NI counter;
NI max;
Pagedesc48313* head;
Pagedesc48313** data;
};
struct  Gcheap50818  {
Gcstack50816* stack;
void* stackbottom;
NI cyclethreshold;
Cellseq48321 zct;
Cellseq48321 decstack;
Cellseq48321 tempstack;
NI recgclock;
Memregion30486 region;
Gcstat50814 stat;
Cellset48317 marked;
Cellseq48321 additionalroots;
};
typedef NU8 Input131004;
typedef NI32 Scancode115402;
typedef NI32 Eventtype116152;
typedef NU8 TY116342[52];
struct  Event116155  {
Eventtype116152 kind;
TY116342 padding;
};
typedef NI32 Bool32116255;
typedef N_CDECL_PTR(Bool32116255, TY126963) (Event116155* event0);
struct  Keysym116261  {
Scancode115402 scancode;
int sym;
NI16 modstate;
int unicode;
};
struct  Keyboardeventobj116167  {
Eventtype116152 kind;
NU32 timestamp;
NU32 windowid;
NU8 state;
NIM_BOOL repeat;
NU8 pad1;
NU8 pad2;
Keysym116261 keysym;
};
struct Rect116265 {
int Field0;
int Field1;
int Field2;
int Field3;
};
struct TY131101 {
Rect116265 Field0;
Rect116265 Field1;
int Field2;
};
typedef TY131101 TY131105[8];
typedef NI32 Sdlreturn116252;
typedef N_CDECL_PTR(Sdlreturn116252, TY126385) (RendererptrHEX3Aobjecttype116607* renderer0, TextureptrHEX3Aobjecttype116609* texture0, Rect116265* srcrect0, Rect116265* dstrect0, double angle0, Point116263* center0, int flip0);
typedef N_CDECL_PTR(int, TY126407) (RendererptrHEX3Aobjecttype116607* renderer0);
typedef N_CDECL_PTR(void, TY126418) (RendererptrHEX3Aobjecttype116607* renderer0);
typedef N_CDECL_PTR(Sdlreturn116252, TY126166) (int flags0);
struct  TNimObject  {
TNimType* m_type;
};
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct  Exception  {
  TNimObject Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
NimStringDesc* trace;
};
struct  Sdlexception131002  {
  Exception Sup;
};
typedef N_CDECL_PTR(NCSTRING, TY127012) (void);
typedef struct {
N_NIMCALL_PTR(NIM_BOOL, ClPrc) (Exception* e0, void* ClEnv);
void* ClEnv;
} TY18011;
struct  TSafePoint  {
TSafePoint* prev;
NI status;
jmp_buf context;
NIM_BOOL hasRaiseAction;
TY18011 raiseAction;
};
typedef N_CDECL_PTR(NIM_BOOL, TY127412) (NCSTRING name0, NCSTRING value0);
typedef N_CDECL_PTR(int, TY128605) (int flags0);
typedef N_CDECL_PTR(WindowptrHEX3Aobjecttype116605*, TY126731) (NCSTRING title0, int x0, int y0, int w0, int h0, NU32 flags0);
typedef N_CDECL_PTR(RendererptrHEX3Aobjecttype116607*, TY126206) (WindowptrHEX3Aobjecttype116605* window0, int index0, int flags0);
typedef N_CDECL_PTR(Sdlreturn116252, TY126018) (RendererptrHEX3Aobjecttype116607* renderer0, NU8 r0, NU8 g0, NU8 b0, NU8 a0);
typedef N_CDECL_PTR(void, TY126049) (RendererptrHEX3Aobjecttype116607* renderer0);
typedef N_CDECL_PTR(void, TY126763) (WindowptrHEX3Aobjecttype116605* window0);
typedef N_CDECL_PTR(void, TY128608) (void);
typedef N_CDECL_PTR(void, TY126178) (void);
struct  TextureptrHEX3Aobjecttype116609  {
char dummy;
};
struct  RendererptrHEX3Aobjecttype116607  {
char dummy;
};
struct  Gcstack50816  {
Gcstack50816* prev;
Gcstack50816* next;
void* starts;
void* pos;
NI maxstacksize;
};
struct  Basechunk30438  {
NI prevsize;
NI size;
NIM_BOOL used;
};
struct  Smallchunk30440  {
  Basechunk30438 Sup;
Smallchunk30440* next;
Smallchunk30440* prev;
Freecell30430* freelist;
NI free;
NI acc;
NF data;
};
struct  Llchunk30480  {
NI size;
NI acc;
Llchunk30480* next;
};
struct  Bigchunk30442  {
  Basechunk30438 Sup;
Bigchunk30442* next;
Bigchunk30442* prev;
NI align;
NF data;
};
typedef NI TY30419[8];
struct  Trunk30410  {
Trunk30410* next;
NI key;
TY30419 bits;
};
typedef Avlnode30484* TY30491[2];
struct  Avlnode30484  {
TY30491 link;
NI key;
NI upperbound;
NI level;
};
struct  Pagedesc48313  {
Pagedesc48313* next;
NI key;
TY30419 bits;
};
struct Point116263 {
int Field0;
int Field1;
};
struct  WindowptrHEX3Aobjecttype116605  {
char dummy;
};
struct  Freecell30430  {
Freecell30430* next;
NI zerofield;
};
N_NIMCALL(void, restartplayer_131043_2076107616)(PlayerHEX3Aobjecttype131015* player0);
static N_INLINE(Point2d129023, point2d_129051_2328089844)(NF x0, NF y0);
static N_INLINE(void, nimFrame)(TFrame* s0);
N_NOINLINE(void, stackoverflow_22401_1689653243)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(Vector2d129025, vector2d_129047_2328089844)(NF x0, NF y0);
N_NIMCALL(PlayerHEX3Aobjecttype131015*, newplayer_131052_2076107616)(TextureptrHEX3Aobjecttype116609* texture0);
N_NIMCALL(void, TMP193)(void* p, NI op);
N_NIMCALL(void*, newObj)(TNimType* typ0, NI size0);
N_NIMCALL(GameHEX3Aobjecttype131020*, newgame_131064_2076107616)(RendererptrHEX3Aobjecttype116607* renderer0);
N_NIMCALL(void, nimGCvisit)(void* d0, NI op0);
N_NIMCALL(void, TMP195)(void* p, NI op);
static N_INLINE(void, asgnRefNoCycle)(void** dest0, void* src0);
static N_INLINE(Cell48305*, usrtocell_52440_1689653243)(void* usr0);
static N_INLINE(void, rtladdzct_53601_1689653243)(Cell48305* c0);
N_NOINLINE(void, addzct_52417_1689653243)(Cellseq48321* s0, Cell48305* c0);
N_NIMCALL(Input131004, toinput_131076_2076107616)(Scancode115402 key0);
N_NIMCALL(void, handleinput_131086_2076107616)(GameHEX3Aobjecttype131020* game0);
N_NIMCALL(NIM_BOOL, tobool_116697_2197055214)(Bool32116255 some0);
N_NIMCALL(Keyboardeventobj116167*, key_118003_2197055214)(Event116155* event_117806_2197055214);
N_NIMCALL(void, rendertee_131093_2076107616)(RendererptrHEX3Aobjecttype116607* renderer0, TextureptrHEX3Aobjecttype116609* texture0, Point2d129023 pos0);
N_CDECL(Rect116265, rect_127392_2197055214)(int x0, int y0, int w0, int h0);
static N_INLINE(NI, subInt)(NI a0, NI b0);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(NI, addInt)(NI a0, NI b0);
N_NIMCALL(void, render_131177_2076107616)(GameHEX3Aobjecttype131020* game0);
static N_INLINE(Point2d129023, HEX2D_130005_2328089844)(Point2d129023 p0, Vector2d129025 v0);
N_NIMCALL(void, main_131189_2076107616)(void);
N_NIMCALL(NIM_BOOL, tobool_116702_2197055214)(Sdlreturn116252 some0);
N_NIMCALL(void, TMP213)(void* p, NI op);
static N_INLINE(void, appendString)(NimStringDesc* dest0, NimStringDesc* src0);
N_NIMCALL(NimStringDesc*, cstrToNimstr)(NCSTRING str0);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space0);
N_NIMCALL(void, raiseException)(Exception* e0, NCSTRING ename0);
static N_INLINE(void, pushSafePoint)(TSafePoint* s0);
static N_INLINE(void, popSafePoint)(void);
static N_INLINE(void, setFrame)(TFrame* s0);
N_NIMCALL(void, reraiseException)(void);
static N_INLINE(void, destroy_127334_2197055214)(WindowptrHEX3Aobjecttype116605* window0);
static N_INLINE(void, initStackBottomWith)(void* locals0);
N_NOINLINE(void, setStackBottom)(void* thestackbottom0);
NIM_EXTERNC N_NOINLINE(void, systemInit000)(void);
NIM_EXTERNC N_NOINLINE(void, systemDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_macrosInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_macrosDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_unsignedInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_unsignedDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, sdl2_sdl2Init000)(void);
NIM_EXTERNC N_NOINLINE(void, sdl2_sdl2DatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, sdl2_imageInit000)(void);
NIM_EXTERNC N_NOINLINE(void, sdl2_imageDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_basic2dInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_basic2dDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, testInit000)(void);
NIM_EXTERNC N_NOINLINE(void, testDatInit000)(void);
STRING_LITERAL(TMP214, "SDL2 initialization failed, SDL error: ", 39);
STRING_LITERAL(TMP216, "Linear texture filtering could not be enabled, SDL error: ", 58);
STRING_LITERAL(TMP217, "SDL2 Image initialization failed, SDL error: ", 45);
STRING_LITERAL(TMP219, "Window could not be created, SDL error: ", 40);
STRING_LITERAL(TMP221, "Renderer could not be created, SDL error: ", 42);
extern TFrame* frameptr_19636_1689653243;
TNimType NTI131015; /* Player:ObjectType */
extern TNimType NTI116576; /* TexturePtr */
extern TNimType NTI129023; /* Point2d */
extern TNimType NTI129025; /* Vector2d */
TNimType NTI131006; /* Player */
TNimType NTI131020; /* Game:ObjectType */
extern TNimType NTI130; /* bool */
TNimType NTI131023; /* array[Input, bool] */
extern TNimType NTI116574; /* RendererPtr */
TNimType NTI131008; /* Game */
extern TY128622 Dl_128621;
extern Gcheap50818 gch_50858_1689653243;
extern Event116155 defaultevent_127601_2197055214;
extern TY126963 Dl_126962;
extern TY126385 Dl_126384;
extern TY126407 Dl_126406;
extern TY126418 Dl_126417;
extern TY126166 Dl_126165;
extern TNimType NTI3424; /* Exception */
TNimType NTI131002; /* SDLException */
TNimType NTI131196; /* ref SDLException */
extern TY127012 Dl_127011;
extern TSafePoint* exchandler_19637_1689653243;
extern TY127412 Dl_127411;
extern TY128605 Dl_128604;
extern TY126731 Dl_126730;
extern TY126206 Dl_126205;
extern TY126018 Dl_126017;
extern TY126049 Dl_126048;
extern TY126763 Dl_126762;
extern TY128608 Dl_128607;
extern TY126178 Dl_126177;

static N_INLINE(void, nimFrame)(TFrame* s0) {
	NI LOC1;
	LOC1 = (NI)0;
	{
		if (!(frameptr_19636_1689653243 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_19636_1689653243).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s0).calldepth = ((NI16) (LOC1));
	(*s0).prev = frameptr_19636_1689653243;
	frameptr_19636_1689653243 = s0;
	{
		if (!((*s0).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_22401_1689653243();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_19636_1689653243 = (*frameptr_19636_1689653243).prev;
}

static N_INLINE(Point2d129023, point2d_129051_2328089844)(NF x0, NF y0) {
	Point2d129023 result0;
	nimfr("point2d", "basic2d.nim")
	nimln(654, "basic2d.nim");
	result0.x = x0;
	nimln(655, "basic2d.nim");
	result0.y = y0;
	popFrame();
	return result0;
}

static N_INLINE(Vector2d129025, vector2d_129047_2328089844)(NF x0, NF y0) {
	Vector2d129025 result0;
	nimfr("vector2d", "basic2d.nim")
	nimln(337, "basic2d.nim");
	result0.x = x0;
	nimln(338, "basic2d.nim");
	result0.y = y0;
	popFrame();
	return result0;
}

N_NIMCALL(void, restartplayer_131043_2076107616)(PlayerHEX3Aobjecttype131015* player0) {
	nimfr("restartPlayer", "test.nim")
	nimln(22, "test.nim");
	(*player0).pos = point2d_129051_2328089844(3.0000000000000000e+02, 3.0000000000000000e+02);
	nimln(23, "test.nim");
	(*player0).vel = vector2d_129047_2328089844(0.0, 0.0);
	popFrame();
}
N_NIMCALL(void, TMP193)(void* p, NI op) {
	PlayerHEX3Aobjecttype131015* a;
	a = (PlayerHEX3Aobjecttype131015*)p;
}

N_NIMCALL(PlayerHEX3Aobjecttype131015*, newplayer_131052_2076107616)(TextureptrHEX3Aobjecttype116609* texture0) {
	PlayerHEX3Aobjecttype131015* result0;
	nimfr("newPlayer", "test.nim")
	result0 = (PlayerHEX3Aobjecttype131015*)0;
	nimln(26, "test.nim");
	result0 = (PlayerHEX3Aobjecttype131015*) newObj((&NTI131006), sizeof(PlayerHEX3Aobjecttype131015));
	nimln(27, "test.nim");
	(*result0).texture = texture0;
	nimln(28, "test.nim");
	restartplayer_131043_2076107616(result0);
	popFrame();
	return result0;
}
N_NIMCALL(void, TMP195)(void* p, NI op) {
	GameHEX3Aobjecttype131020* a;
	NI LOC1;
	a = (GameHEX3Aobjecttype131020*)p;
	LOC1 = (NI)0;
	for (LOC1 = 0; LOC1 < 6; LOC1++) {
	}
	nimGCvisit((void*)(*a).player, op);
}

static N_INLINE(Cell48305*, usrtocell_52440_1689653243)(void* usr0) {
	Cell48305* result0;
	nimfr("usrToCell", "gc.nim")
	result0 = (Cell48305*)0;
	nimln(131, "gc.nim");
	result0 = ((Cell48305*) ((NI)((NU64)(((NI) (usr0))) - (NU64)(((NI)sizeof(Cell48305))))));
	popFrame();
	return result0;
}

static N_INLINE(void, rtladdzct_53601_1689653243)(Cell48305* c0) {
	nimfr("rtlAddZCT", "gc.nim")
	nimln(211, "gc.nim");
	addzct_52417_1689653243((&gch_50858_1689653243.zct), c0);
	popFrame();
}

static N_INLINE(void, asgnRefNoCycle)(void** dest0, void* src0) {
	nimfr("asgnRefNoCycle", "gc.nim")
	nimln(271, "gc.nim");
	{
		Cell48305* c0;
		nimln(343, "system.nim");
		if (!!((src0 == NIM_NIL))) goto LA3;
		nimln(272, "gc.nim");
		c0 = usrtocell_52440_1689653243(src0);
		nimln(179, "gc.nim");
		(*c0).refcount += ((NI) 8);
	}
	LA3: ;
	nimln(274, "gc.nim");
	{
		Cell48305* c0;
		nimln(343, "system.nim");
		if (!!(((*dest0) == NIM_NIL))) goto LA7;
		nimln(275, "gc.nim");
		c0 = usrtocell_52440_1689653243((*dest0));
		nimln(276, "gc.nim");
		{
			nimln(177, "gc.nim");
			(*c0).refcount -= ((NI) 8);
			nimln(178, "gc.nim");
			if (!((NU64)((*c0).refcount) < (NU64)(((NI) 8)))) goto LA11;
			nimln(277, "gc.nim");
			rtladdzct_53601_1689653243(c0);
		}
		LA11: ;
	}
	LA7: ;
	nimln(278, "gc.nim");
	(*dest0) = src0;
	popFrame();
}

N_NIMCALL(GameHEX3Aobjecttype131020*, newgame_131064_2076107616)(RendererptrHEX3Aobjecttype116607* renderer0) {
	GameHEX3Aobjecttype131020* result0;
	TextureptrHEX3Aobjecttype116609* LOC1;
	nimfr("newGame", "test.nim")
	result0 = (GameHEX3Aobjecttype131020*)0;
	nimln(31, "test.nim");
	result0 = (GameHEX3Aobjecttype131020*) newObj((&NTI131008), sizeof(GameHEX3Aobjecttype131020));
	nimln(32, "test.nim");
	(*result0).renderer = renderer0;
	nimln(33, "test.nim");
	LOC1 = (TextureptrHEX3Aobjecttype116609*)0;
	LOC1 = Dl_128621(renderer0, "player.png");
	asgnRefNoCycle((void**) (&(*result0).player), newplayer_131052_2076107616(LOC1));
	popFrame();
	return result0;
}

N_NIMCALL(Input131004, toinput_131076_2076107616)(Scancode115402 key0) {
	Input131004 result0;
	nimfr("toInput", "test.nim")
	result0 = (Input131004)0;
	nimln(36, "test.nim");
	switch (key0) {
	case ((Scancode115402) 4):
	{
		result0 = ((Input131004) 1);
	}
	break;
	case ((Scancode115402) 7):
	{
		result0 = ((Input131004) 2);
	}
	break;
	case ((Scancode115402) 44):
	{
		result0 = ((Input131004) 3);
	}
	break;
	case ((Scancode115402) 21):
	{
		result0 = ((Input131004) 4);
	}
	break;
	case ((Scancode115402) 20):
	{
		result0 = ((Input131004) 5);
	}
	break;
	default:
	{
		result0 = ((Input131004) 0);
	}
	break;
	}
	popFrame();
	return result0;
}

N_NIMCALL(void, handleinput_131086_2076107616)(GameHEX3Aobjecttype131020* game0) {
	Event116155 event0;
	nimfr("handleInput", "test.nim")
	nimln(45, "test.nim");
	event0 = defaultevent_127601_2197055214;
	{
		nimln(46, "test.nim");
		while (1) {
			Bool32116255 LOC3;
			NIM_BOOL LOC4;
			LOC3 = (Bool32116255)0;
			LOC3 = Dl_126962((&event0));
			LOC4 = (NIM_BOOL)0;
			LOC4 = tobool_116697_2197055214(LOC3);
			if (!LOC4) goto LA2;
			nimln(47, "test.nim");
			switch (event0.kind) {
			case ((Eventtype116152) 256):
			{
				nimln(49, "test.nim");
				(*game0).inputs[(((Input131004) 5))- 0] = NIM_TRUE;
			}
			break;
			case ((Eventtype116152) 768):
			{
				Keyboardeventobj116167* LOC7;
				Input131004 LOC8;
				nimln(51, "test.nim");
				LOC7 = (Keyboardeventobj116167*)0;
				LOC7 = key_118003_2197055214((&event0));
				LOC8 = (Input131004)0;
				LOC8 = toinput_131076_2076107616((*LOC7).keysym.scancode);
				(*game0).inputs[(LOC8)- 0] = NIM_TRUE;
			}
			break;
			case ((Eventtype116152) 769):
			{
				Keyboardeventobj116167* LOC10;
				Input131004 LOC11;
				nimln(53, "test.nim");
				LOC10 = (Keyboardeventobj116167*)0;
				LOC10 = key_118003_2197055214((&event0));
				LOC11 = (Input131004)0;
				LOC11 = toinput_131076_2076107616((*LOC10).keysym.scancode);
				(*game0).inputs[(LOC11)- 0] = NIM_FALSE;
			}
			break;
			default:
			{
			}
			break;
			}
		} LA2: ;
	}
	popFrame();
}

static N_INLINE(NI, subInt)(NI a0, NI b0) {
	NI result0;
{	result0 = (NI)0;
	result0 = (NI)((NU64)(a0) - (NU64)(b0));
	{
		NIM_BOOL LOC3;
		LOC3 = (NIM_BOOL)0;
		LOC3 = (((NI) 0) <= (NI)(result0 ^ a0));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result0 ^ (NI)((NU64) ~(b0))));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result0;
}

static N_INLINE(NI, addInt)(NI a0, NI b0) {
	NI result0;
{	result0 = (NI)0;
	result0 = (NI)((NU64)(a0) + (NU64)(b0));
	{
		NIM_BOOL LOC3;
		LOC3 = (NIM_BOOL)0;
		LOC3 = (((NI) 0) <= (NI)(result0 ^ a0));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result0 ^ b0));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result0;
}

N_NIMCALL(void, rendertee_131093_2076107616)(RendererptrHEX3Aobjecttype116607* renderer0, TextureptrHEX3Aobjecttype116609* texture0, Point2d129023 pos0) {
	int x0;
	int y0;
	TY131105 bodyparts0;
	NI TMP200;
	NI TMP201;
	NI TMP202;
	NI TMP203;
	NI TMP204;
	NI TMP205;
	NI TMP206;
	NI TMP207;
	NI TMP208;
	NI TMP209;
	NI TMP210;
	NI TMP211;
	nimfr("renderTee", "test.nim")
	nimln(60, "test.nim");
	x0 = ((int) (pos0.x));
	nimln(61, "test.nim");
	y0 = ((int) (pos0.y));
	memset((void*)bodyparts0, 0, sizeof(bodyparts0));
	nimln(63, "test.nim");
	nimln(64, "test.nim");
	bodyparts0[0].Field0 = rect_127392_2197055214(((int) 192), ((int) 64), ((int) 64), ((int) 32));
	TMP200 = subInt(x0, ((NI32) 60));
	if (TMP200 < (-2147483647 -1) || TMP200 > 2147483647) raiseOverflow();
	bodyparts0[0].Field1 = rect_127392_2197055214((NI32)(TMP200), y0, ((int) 96), ((int) 48));
	bodyparts0[0].Field2 = ((int) 0);
	nimln(66, "test.nim");
	bodyparts0[1].Field0 = rect_127392_2197055214(((int) 96), ((int) 0), ((int) 96), ((int) 96));
	TMP201 = subInt(x0, ((NI32) 48));
	if (TMP201 < (-2147483647 -1) || TMP201 > 2147483647) raiseOverflow();
	TMP202 = subInt(y0, ((NI32) 48));
	if (TMP202 < (-2147483647 -1) || TMP202 > 2147483647) raiseOverflow();
	bodyparts0[1].Field1 = rect_127392_2197055214((NI32)(TMP201), (NI32)(TMP202), ((int) 96), ((int) 96));
	bodyparts0[1].Field2 = ((int) 0);
	nimln(68, "test.nim");
	bodyparts0[2].Field0 = rect_127392_2197055214(((int) 192), ((int) 64), ((int) 64), ((int) 32));
	TMP203 = subInt(x0, ((NI32) 36));
	if (TMP203 < (-2147483647 -1) || TMP203 > 2147483647) raiseOverflow();
	bodyparts0[2].Field1 = rect_127392_2197055214((NI32)(TMP203), y0, ((int) 96), ((int) 48));
	bodyparts0[2].Field2 = ((int) 0);
	nimln(70, "test.nim");
	bodyparts0[3].Field0 = rect_127392_2197055214(((int) 192), ((int) 32), ((int) 64), ((int) 32));
	TMP204 = subInt(x0, ((NI32) 60));
	if (TMP204 < (-2147483647 -1) || TMP204 > 2147483647) raiseOverflow();
	bodyparts0[3].Field1 = rect_127392_2197055214((NI32)(TMP204), y0, ((int) 96), ((int) 48));
	bodyparts0[3].Field2 = ((int) 0);
	nimln(72, "test.nim");
	bodyparts0[4].Field0 = rect_127392_2197055214(((int) 0), ((int) 0), ((int) 96), ((int) 96));
	TMP205 = subInt(x0, ((NI32) 48));
	if (TMP205 < (-2147483647 -1) || TMP205 > 2147483647) raiseOverflow();
	TMP206 = subInt(y0, ((NI32) 48));
	if (TMP206 < (-2147483647 -1) || TMP206 > 2147483647) raiseOverflow();
	bodyparts0[4].Field1 = rect_127392_2197055214((NI32)(TMP205), (NI32)(TMP206), ((int) 96), ((int) 96));
	bodyparts0[4].Field2 = ((int) 0);
	nimln(74, "test.nim");
	bodyparts0[5].Field0 = rect_127392_2197055214(((int) 192), ((int) 32), ((int) 64), ((int) 32));
	TMP207 = subInt(x0, ((NI32) 36));
	if (TMP207 < (-2147483647 -1) || TMP207 > 2147483647) raiseOverflow();
	bodyparts0[5].Field1 = rect_127392_2197055214((NI32)(TMP207), y0, ((int) 96), ((int) 48));
	bodyparts0[5].Field2 = ((int) 0);
	nimln(76, "test.nim");
	bodyparts0[6].Field0 = rect_127392_2197055214(((int) 64), ((int) 96), ((int) 32), ((int) 32));
	TMP208 = subInt(x0, ((NI32) 18));
	if (TMP208 < (-2147483647 -1) || TMP208 > 2147483647) raiseOverflow();
	TMP209 = subInt(y0, ((NI32) 21));
	if (TMP209 < (-2147483647 -1) || TMP209 > 2147483647) raiseOverflow();
	bodyparts0[6].Field1 = rect_127392_2197055214((NI32)(TMP208), (NI32)(TMP209), ((int) 36), ((int) 36));
	bodyparts0[6].Field2 = ((int) 0);
	nimln(78, "test.nim");
	bodyparts0[7].Field0 = rect_127392_2197055214(((int) 64), ((int) 96), ((int) 32), ((int) 32));
	TMP210 = subInt(x0, ((NI32) 6));
	if (TMP210 < (-2147483647 -1) || TMP210 > 2147483647) raiseOverflow();
	TMP211 = subInt(y0, ((NI32) 21));
	if (TMP211 < (-2147483647 -1) || TMP211 > 2147483647) raiseOverflow();
	bodyparts0[7].Field1 = rect_127392_2197055214((NI32)(TMP210), (NI32)(TMP211), ((int) 36), ((int) 36));
	bodyparts0[7].Field2 = ((int) 1);
	{
		TY131101* part_131167_2076107616;
		NI i_131176_2076107616;
		part_131167_2076107616 = (TY131101*)0;
		nimln(1989, "system.nim");
		i_131176_2076107616 = ((NI) 0);
		nimln(1990, "system.nim");
		{
			if (!(((NI) (i_131176_2076107616)) <= ((NI) 7))) goto LA4;
			{
				nimln(1991, "system.nim");
				while (1) {
					Sdlreturn116252 LOC8;
					NI TMP212;
					nimln(1992, "system.nim");
					part_131167_2076107616 = (&bodyparts0[(i_131176_2076107616)- 0]);
					nimln(83, "test.nim");
					LOC8 = (Sdlreturn116252)0;
					LOC8 = Dl_126384(renderer0, texture0, (&(*part_131167_2076107616).Field0), (&(*part_131167_2076107616).Field1), 0.0, NIM_NIL, (*part_131167_2076107616).Field2);
					nimln(1993, "system.nim");
					{
						nimln(347, "system.nim");
						if (!(((NI) 7) <= ((NI) (i_131176_2076107616)))) goto LA11;
						nimln(1993, "system.nim");
						goto LA6;
					}
					LA11: ;
					nimln(1994, "system.nim");
					TMP212 = addInt(i_131176_2076107616, ((NI) 1));
					if (TMP212 < 0 || TMP212 > 7) raiseOverflow();
					i_131176_2076107616 = (NI)(TMP212);
				}
			} LA6: ;
		}
		LA4: ;
	}
	popFrame();
}

static N_INLINE(Point2d129023, HEX2D_130005_2328089844)(Point2d129023 p0, Vector2d129025 v0) {
	Point2d129023 result0;
	nimfr("-", "basic2d.nim")
	nimln(729, "basic2d.nim");
	result0.x = ((NF)(p0.x) - (NF)(v0.x));
	nimln(730, "basic2d.nim");
	result0.y = ((NF)(p0.y) - (NF)(v0.y));
	popFrame();
	return result0;
}

N_NIMCALL(void, render_131177_2076107616)(GameHEX3Aobjecttype131020* game0) {
	int LOC1;
	Point2d129023 LOC2;
	nimfr("render", "test.nim")
	nimln(88, "test.nim");
	LOC1 = (int)0;
	LOC1 = Dl_126406((*game0).renderer);
	nimln(89, "test.nim");
	LOC2 = HEX2D_130005_2328089844((*(*game0).player).pos, (*game0).camera);
	rendertee_131093_2076107616((*game0).renderer, (*(*game0).player).texture, LOC2);
	nimln(91, "test.nim");
	Dl_126417((*game0).renderer);
	popFrame();
}
N_NIMCALL(void, TMP213)(void* p, NI op) {
	Sdlexception131002* a;
	a = (Sdlexception131002*)p;
	nimGCvisit((void*)(*a).Sup.parent, op);
	nimGCvisit((void*)(*a).Sup.message, op);
	nimGCvisit((void*)(*a).Sup.trace, op);
}

static N_INLINE(void, appendString)(NimStringDesc* dest0, NimStringDesc* src0) {
	memcpy(((NCSTRING) ((&(*dest0).data[((*dest0).Sup.len)- 0]))), ((NCSTRING) ((*src0).data)), (NI)((*src0).Sup.len + ((NI) 1)));
	(*dest0).Sup.len += (*src0).Sup.len;
}

static N_INLINE(void, pushSafePoint)(TSafePoint* s0) {
	(*s0).hasRaiseAction = NIM_FALSE;
	(*s0).prev = exchandler_19637_1689653243;
	exchandler_19637_1689653243 = s0;
}

static N_INLINE(void, popSafePoint)(void) {
	exchandler_19637_1689653243 = (*exchandler_19637_1689653243).prev;
}

static N_INLINE(void, setFrame)(TFrame* s0) {
	frameptr_19636_1689653243 = s0;
}

static N_INLINE(void, destroy_127334_2197055214)(WindowptrHEX3Aobjecttype116605* window0) {
	nimfr("destroy", "sdl2.nim")
	nimln(1712, "sdl2.nim");
	Dl_126762(window0);
	popFrame();
}

N_NIMCALL(void, main_131189_2076107616)(void) {
	TSafePoint TMP215;
	nimfr("main", "test.nim")
	nimln(94, "test.nim");
	{
		Sdlreturn116252 LOC3;
		NIM_BOOL LOC4;
		Sdlexception131002* e_131195_2076107616;
		NimStringDesc* LOC7;
		NCSTRING LOC8;
		NimStringDesc* LOC9;
		nimln(98, "test.nim");
		LOC3 = (Sdlreturn116252)0;
		LOC3 = Dl_126165(((int) 16417));
		LOC4 = (NIM_BOOL)0;
		LOC4 = tobool_116702_2197055214(LOC3);
		if (!!(LOC4)) goto LA5;
		e_131195_2076107616 = (Sdlexception131002*)0;
		nimln(2514, "system.nim");
		e_131195_2076107616 = (Sdlexception131002*) newObj((&NTI131196), sizeof(Sdlexception131002));
		(*e_131195_2076107616).Sup.Sup.m_type = (&NTI131002);
		nimln(2515, "system.nim");
		nimln(95, "test.nim");
		LOC7 = (NimStringDesc*)0;
		LOC8 = (NCSTRING)0;
		LOC8 = Dl_127011();
		LOC9 = (NimStringDesc*)0;
		LOC9 = cstrToNimstr(LOC8);
		LOC7 = rawNewString(LOC9->Sup.len + 39);
appendString(LOC7, ((NimStringDesc*) &TMP214));
appendString(LOC7, LOC9);
		asgnRefNoCycle((void**) (&(*e_131195_2076107616).Sup.message), LOC7);
		nimln(94, "test.nim");
		raiseException((Exception*)e_131195_2076107616, "SDLException");
	}
	LA5: ;
	nimln(103, "test.nim");
	pushSafePoint(&TMP215);
	TMP215.status = setjmp(TMP215.context);
	if (TMP215.status == 0) {
		TSafePoint TMP218;
		nimln(94, "test.nim");
		{
			NIM_BOOL LOC13;
			Sdlexception131002* volatile e_131208_2076107616;
			NimStringDesc* LOC16;
			NCSTRING LOC17;
			NimStringDesc* LOC18;
			nimln(105, "test.nim");
			LOC13 = (NIM_BOOL)0;
			LOC13 = Dl_127411("SDL_RENDER_SCALE_QUALITY", "2");
			if (!!(LOC13)) goto LA14;
			e_131208_2076107616 = (Sdlexception131002*)0;
			nimln(2514, "system.nim");
			e_131208_2076107616 = (Sdlexception131002*) newObj((&NTI131196), sizeof(Sdlexception131002));
			(*e_131208_2076107616).Sup.Sup.m_type = (&NTI131002);
			nimln(2515, "system.nim");
			nimln(95, "test.nim");
			LOC16 = (NimStringDesc*)0;
			LOC17 = (NCSTRING)0;
			LOC17 = Dl_127011();
			LOC18 = (NimStringDesc*)0;
			LOC18 = cstrToNimstr(LOC17);
			LOC16 = rawNewString(LOC18->Sup.len + 58);
appendString(LOC16, ((NimStringDesc*) &TMP216));
appendString(LOC16, LOC18);
			asgnRefNoCycle((void**) (&(*e_131208_2076107616).Sup.message), LOC16);
			nimln(94, "test.nim");
			raiseException((Exception*)e_131208_2076107616, "SDLException");
		}
		LA14: ;
		{
			int LOC21;
			Sdlexception131002* volatile e_131222_2076107616;
			NimStringDesc* LOC24;
			NCSTRING LOC25;
			NimStringDesc* LOC26;
			nimln(343, "system.nim");
			nimln(109, "test.nim");
			LOC21 = (int)0;
			LOC21 = Dl_128604(((int) 2));
			if (!!((LOC21 == ((int) 2)))) goto LA22;
			e_131222_2076107616 = (Sdlexception131002*)0;
			nimln(2514, "system.nim");
			e_131222_2076107616 = (Sdlexception131002*) newObj((&NTI131196), sizeof(Sdlexception131002));
			(*e_131222_2076107616).Sup.Sup.m_type = (&NTI131002);
			nimln(2515, "system.nim");
			nimln(95, "test.nim");
			LOC24 = (NimStringDesc*)0;
			LOC25 = (NCSTRING)0;
			LOC25 = Dl_127011();
			LOC26 = (NimStringDesc*)0;
			LOC26 = cstrToNimstr(LOC25);
			LOC24 = rawNewString(LOC26->Sup.len + 45);
appendString(LOC24, ((NimStringDesc*) &TMP217));
appendString(LOC24, LOC26);
			asgnRefNoCycle((void**) (&(*e_131222_2076107616).Sup.message), LOC24);
			nimln(94, "test.nim");
			raiseException((Exception*)e_131222_2076107616, "SDLException");
		}
		LA22: ;
		nimln(111, "test.nim");
		pushSafePoint(&TMP218);
		TMP218.status = setjmp(TMP218.context);
		if (TMP218.status == 0) {
			WindowptrHEX3Aobjecttype116605* window0;
			TSafePoint TMP220;
			nimln(113, "test.nim");
			window0 = Dl_126730("\320\233\320\260\320\273\320\272\320\260", ((int) 805240832), ((int) 805240832), ((int) 800), ((int) 600), ((unsigned int) 4));
			nimln(94, "test.nim");
			{
				Sdlexception131002* volatile e_131246_2076107616;
				NimStringDesc* LOC32;
				NCSTRING LOC33;
				NimStringDesc* LOC34;
				nimln(116, "test.nim");
				if (!window0 == 0) goto LA30;
				e_131246_2076107616 = (Sdlexception131002*)0;
				nimln(2514, "system.nim");
				e_131246_2076107616 = (Sdlexception131002*) newObj((&NTI131196), sizeof(Sdlexception131002));
				(*e_131246_2076107616).Sup.Sup.m_type = (&NTI131002);
				nimln(2515, "system.nim");
				nimln(95, "test.nim");
				LOC32 = (NimStringDesc*)0;
				LOC33 = (NCSTRING)0;
				LOC33 = Dl_127011();
				LOC34 = (NimStringDesc*)0;
				LOC34 = cstrToNimstr(LOC33);
				LOC32 = rawNewString(LOC34->Sup.len + 40);
appendString(LOC32, ((NimStringDesc*) &TMP219));
appendString(LOC32, LOC34);
				asgnRefNoCycle((void**) (&(*e_131246_2076107616).Sup.message), LOC32);
				nimln(94, "test.nim");
				raiseException((Exception*)e_131246_2076107616, "SDLException");
			}
			LA30: ;
			nimln(117, "test.nim");
			pushSafePoint(&TMP220);
			TMP220.status = setjmp(TMP220.context);
			if (TMP220.status == 0) {
				RendererptrHEX3Aobjecttype116607* renderer0;
				TSafePoint TMP222;
				nimln(119, "test.nim");
				renderer0 = Dl_126205(window0, ((int) -1), ((NI32) 6));
				nimln(94, "test.nim");
				{
					Sdlexception131002* volatile e_131268_2076107616;
					NimStringDesc* LOC40;
					NCSTRING LOC41;
					NimStringDesc* LOC42;
					nimln(121, "test.nim");
					if (!renderer0 == 0) goto LA38;
					e_131268_2076107616 = (Sdlexception131002*)0;
					nimln(2514, "system.nim");
					e_131268_2076107616 = (Sdlexception131002*) newObj((&NTI131196), sizeof(Sdlexception131002));
					(*e_131268_2076107616).Sup.Sup.m_type = (&NTI131002);
					nimln(2515, "system.nim");
					nimln(95, "test.nim");
					LOC40 = (NimStringDesc*)0;
					LOC41 = (NCSTRING)0;
					LOC41 = Dl_127011();
					LOC42 = (NimStringDesc*)0;
					LOC42 = cstrToNimstr(LOC41);
					LOC40 = rawNewString(LOC42->Sup.len + 42);
appendString(LOC40, ((NimStringDesc*) &TMP221));
appendString(LOC40, LOC42);
					asgnRefNoCycle((void**) (&(*e_131268_2076107616).Sup.message), LOC40);
					nimln(94, "test.nim");
					raiseException((Exception*)e_131268_2076107616, "SDLException");
				}
				LA38: ;
				nimln(122, "test.nim");
				pushSafePoint(&TMP222);
				TMP222.status = setjmp(TMP222.context);
				if (TMP222.status == 0) {
					Sdlreturn116252 LOC44;
					GameHEX3Aobjecttype131020* game0;
					nimln(125, "test.nim");
					LOC44 = (Sdlreturn116252)0;
					LOC44 = Dl_126017(renderer0, ((NU8) 110), ((NU8) 132), ((NU8) 174), ((NU8) 255));
					nimln(126, "test.nim");
					game0 = newgame_131064_2076107616(renderer0);
					{
						nimln(135, "test.nim");
						while (1) {
							if (!!((*game0).inputs[(((Input131004) 5))- 0])) goto LA46;
							nimln(136, "test.nim");
							handleinput_131086_2076107616(game0);
							nimln(137, "test.nim");
							render_131177_2076107616(game0);
						} LA46: ;
					}
					popSafePoint();
				}
				else {
					popSafePoint();
					setFrame((TFrame*)&FR);
				}
				{
					nimln(122, "test.nim");
					Dl_126048(renderer0);
				}
				if (TMP222.status != 0) reraiseException();
				popSafePoint();
			}
			else {
				popSafePoint();
				setFrame((TFrame*)&FR);
			}
			{
				nimln(117, "test.nim");
				destroy_127334_2197055214(window0);
			}
			if (TMP220.status != 0) reraiseException();
			popSafePoint();
		}
		else {
			popSafePoint();
			setFrame((TFrame*)&FR);
		}
		{
			nimln(111, "test.nim");
			Dl_128607();
		}
		if (TMP218.status != 0) reraiseException();
		popSafePoint();
	}
	else {
		popSafePoint();
		setFrame((TFrame*)&FR);
	}
	{
		nimln(103, "test.nim");
		Dl_126177();
	}
	if (TMP215.status != 0) reraiseException();
	popFrame();
}

static N_INLINE(void, initStackBottomWith)(void* locals0) {
	setStackBottom(locals0);
}
void PreMainInner() {
	systemInit000();
	stdlib_macrosDatInit000();
	stdlib_unsignedDatInit000();
	stdlib_parseutilsDatInit000();
	stdlib_mathDatInit000();
	stdlib_strutilsDatInit000();
	sdl2_sdl2DatInit000();
	sdl2_imageDatInit000();
	stdlib_basic2dDatInit000();
	testDatInit000();
	stdlib_macrosInit000();
	stdlib_unsignedInit000();
	stdlib_parseutilsInit000();
	stdlib_mathInit000();
	stdlib_strutilsInit000();
	sdl2_sdl2Init000();
	sdl2_imageInit000();
	stdlib_basic2dInit000();
}

void PreMain() {
	void (*volatile inner)();
	systemDatInit000();
	inner = PreMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	testInit000();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)();
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

NIM_EXTERNC N_NOINLINE(void, testInit000)(void) {
	nimfr("test", "test.nim")
	nimln(139, "test.nim");
	main_131189_2076107616();
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, testDatInit000)(void) {
static TNimNode* TMP190[3];
static TNimNode* TMP194[4];
static TNimNode TMP139[10];
NTI131015.size = sizeof(PlayerHEX3Aobjecttype131015);
NTI131015.kind = 18;
NTI131015.base = 0;
NTI131015.flags = 3;
TMP190[0] = &TMP139[1];
TMP139[1].kind = 1;
TMP139[1].offset = offsetof(PlayerHEX3Aobjecttype131015, texture);
TMP139[1].typ = (&NTI116576);
TMP139[1].name = "texture";
TMP190[1] = &TMP139[2];
TMP139[2].kind = 1;
TMP139[2].offset = offsetof(PlayerHEX3Aobjecttype131015, pos);
TMP139[2].typ = (&NTI129023);
TMP139[2].name = "pos";
TMP190[2] = &TMP139[3];
TMP139[3].kind = 1;
TMP139[3].offset = offsetof(PlayerHEX3Aobjecttype131015, vel);
TMP139[3].typ = (&NTI129025);
TMP139[3].name = "vel";
TMP139[0].len = 3; TMP139[0].kind = 2; TMP139[0].sons = &TMP190[0];
NTI131015.node = &TMP139[0];
NTI131006.size = sizeof(PlayerHEX3Aobjecttype131015*);
NTI131006.kind = 22;
NTI131006.base = (&NTI131015);
NTI131006.flags = 2;
NTI131006.marker = TMP193;
NTI131020.size = sizeof(GameHEX3Aobjecttype131020);
NTI131020.kind = 18;
NTI131020.base = 0;
NTI131020.flags = 2;
TMP194[0] = &TMP139[5];
NTI131023.size = sizeof(TY131023);
NTI131023.kind = 16;
NTI131023.base = (&NTI130);
NTI131023.flags = 3;
TMP139[5].kind = 1;
TMP139[5].offset = offsetof(GameHEX3Aobjecttype131020, inputs);
TMP139[5].typ = (&NTI131023);
TMP139[5].name = "inputs";
TMP194[1] = &TMP139[6];
TMP139[6].kind = 1;
TMP139[6].offset = offsetof(GameHEX3Aobjecttype131020, renderer);
TMP139[6].typ = (&NTI116574);
TMP139[6].name = "renderer";
TMP194[2] = &TMP139[7];
TMP139[7].kind = 1;
TMP139[7].offset = offsetof(GameHEX3Aobjecttype131020, player);
TMP139[7].typ = (&NTI131006);
TMP139[7].name = "player";
TMP194[3] = &TMP139[8];
TMP139[8].kind = 1;
TMP139[8].offset = offsetof(GameHEX3Aobjecttype131020, camera);
TMP139[8].typ = (&NTI129025);
TMP139[8].name = "camera";
TMP139[4].len = 4; TMP139[4].kind = 2; TMP139[4].sons = &TMP194[0];
NTI131020.node = &TMP139[4];
NTI131008.size = sizeof(GameHEX3Aobjecttype131020*);
NTI131008.kind = 22;
NTI131008.base = (&NTI131020);
NTI131008.flags = 2;
NTI131008.marker = TMP195;
NTI131002.size = sizeof(Sdlexception131002);
NTI131002.kind = 17;
NTI131002.base = (&NTI3424);
TMP139[9].len = 0; TMP139[9].kind = 2;
NTI131002.node = &TMP139[9];
NTI131196.size = sizeof(Sdlexception131002*);
NTI131196.kind = 22;
NTI131196.base = (&NTI131002);
NTI131196.marker = TMP213;
}

